//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface ABTestConfigRequest : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasProductName;
    _Bool _hasIdentificationCode;
    NSMutableArray *_params;
    NSString *_productName;
    NSString *_identificationCode;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *identificationCode; // @synthesize identificationCode=_identificationCode;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) NSMutableArray *params; // @synthesize params=_params;
@property(readonly) _Bool hasIdentificationCode; // @synthesize hasIdentificationCode=_hasIdentificationCode;
@property(readonly) _Bool hasProductName; // @synthesize hasProductName=_hasProductName;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addParams:(id)arg1;
- (void)setParamsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

