//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface AcceptInitRequestPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *cardModelVersion; // @dynamic cardModelVersion;
@property(readonly) _Bool hasCardModelVersion; // @dynamic hasCardModelVersion;
@property(readonly) _Bool hasReceiverType; // @dynamic hasReceiverType;
@property(readonly) _Bool hasSendNo; // @dynamic hasSendNo;
@property(readonly) _Bool hasSenderUserId; // @dynamic hasSenderUserId;
@property(retain, nonatomic) NSString *receiverType; // @dynamic receiverType;
@property(retain, nonatomic) NSString *sendNo; // @dynamic sendNo;
@property(retain, nonatomic) NSString *senderUserId; // @dynamic senderUserId;

@end

