//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFDLoginConfigModel, AFDNaviPageConfigModel, NSString;

@interface AFDConfigModel : NSObject
{
    AFDLoginConfigModel *_loginModel;
    AFDLoginConfigModel *_sampleModel;
    AFDNaviPageConfigModel *_naviConfigModel;
    NSString *_noCameraPermissionWords;
}

@property(retain, nonatomic) NSString *noCameraPermissionWords; // @synthesize noCameraPermissionWords=_noCameraPermissionWords;
@property(retain, nonatomic) AFDNaviPageConfigModel *naviConfigModel; // @synthesize naviConfigModel=_naviConfigModel;
@property(retain, nonatomic) AFDLoginConfigModel *sampleModel; // @synthesize sampleModel=_sampleModel;
@property(retain, nonatomic) AFDLoginConfigModel *loginModel; // @synthesize loginModel=_loginModel;
- (void).cxx_destruct;
- (void)parseConfigJson:(id)arg1;

@end

