//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AFDMineConfigModel : NSObject
{
    _Bool _dscore;
    unsigned long long _vidminecnt;
}

+ (id)defaultModel;
+ (id)modelFromDict:(id)arg1;
@property(nonatomic) unsigned long long vidminecnt; // @synthesize vidminecnt=_vidminecnt;
@property(nonatomic) _Bool dscore; // @synthesize dscore=_dscore;

@end

