//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFEEyeConfig, AFENavigationConfig, AFESceneEnv, NSString;

@interface AFERemoteConfig : NSObject
{
    NSString *_ev;
    NSString *_version;
    long long _env;
    NSString *_noCamPermissionWords;
    AFEEyeConfig *_eye;
    AFENavigationConfig *_navigatepage;
    AFESceneEnv *_sceneEnv;
    long long _ui;
}

+ (id)defaultConfig;
@property(nonatomic) long long ui; // @synthesize ui=_ui;
@property(retain, nonatomic) AFESceneEnv *sceneEnv; // @synthesize sceneEnv=_sceneEnv;
@property(retain, nonatomic) AFENavigationConfig *navigatepage; // @synthesize navigatepage=_navigatepage;
@property(retain, nonatomic) AFEEyeConfig *eye; // @synthesize eye=_eye;
@property(retain, nonatomic) NSString *noCamPermissionWords; // @synthesize noCamPermissionWords=_noCamPermissionWords;
@property(nonatomic) long long env; // @synthesize env=_env;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *ev; // @synthesize ev=_ev;
- (void).cxx_destruct;
- (id)init;

@end

