//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFEBaseTask.h"

#import "AFEMotionDelegate.h"
#import "IStatusBarDelegate.h"
#import "ScanDelegate.h"

@class AFEScanParallelTask, NSMutableArray, NSString, NSTimer, UIView<AFEScanViewProtocol>;

@interface AFEScanBaseTask : AFEBaseTask <ScanDelegate, IStatusBarDelegate, AFEMotionDelegate>
{
    struct AFEEnvStatus_t envStatus;
    _Bool _isRunning;
    _Bool _finishMirror;
    int _eyeStatusCache;
    UIView<AFEScanViewProtocol> *_scanView;
    AFEScanParallelTask *_scanTask;
    NSTimer *_monitorTimer;
    long long _timerTrigerredTimes;
    NSMutableArray *_motionCache;
    NSMutableArray *_fullMotionCache;
}

@property(retain, nonatomic) NSMutableArray *fullMotionCache; // @synthesize fullMotionCache=_fullMotionCache;
@property(retain, nonatomic) NSMutableArray *motionCache; // @synthesize motionCache=_motionCache;
@property(nonatomic) long long timerTrigerredTimes; // @synthesize timerTrigerredTimes=_timerTrigerredTimes;
@property(nonatomic) int eyeStatusCache; // @synthesize eyeStatusCache=_eyeStatusCache;
@property(retain, nonatomic) NSTimer *monitorTimer; // @synthesize monitorTimer=_monitorTimer;
@property(nonatomic) __weak AFEScanParallelTask *scanTask; // @synthesize scanTask=_scanTask;
@property(nonatomic) _Bool finishMirror; // @synthesize finishMirror=_finishMirror;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(retain, nonatomic) UIView<AFEScanViewProtocol> *scanView; // @synthesize scanView=_scanView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)StructToArrayWithXValue:(float)arg1 yValue:(float)arg2 zValue:(float)arg3;
- (void)onMotionUpdateWithAccelerationData:(CDStruct_31142d93)arg1 rotationData:(CDStruct_31142d93)arg2 magneticData:(CDStruct_31142d93)arg3 attitudeData:(struct APBAttitude_t)arg4;
- (void)onStepFinished;
- (void)onDistanceChanged:(double)arg1;
- (void)onEyeCoordinateChanged:(struct CGRect)arg1 right:(struct CGRect)arg2;
- (void)onLightingStatusChanged:(long long)arg1 brightness:(double)arg2;
- (void)onEyeStatusChanged:(long long)arg1;
- (void)onSoundStatusChanged:(_Bool)arg1;
- (void)onButtonCancel;
- (void)updateStatus;
- (void)onMonitorTimer;
- (id)continueActionWithTitle:(id)arg1 Scene:(id)arg2;
- (void)processErrorMessage:(id)arg1 audioFilePath:(id)arg2;
- (void)reset;
- (void)processEvent:(id)arg1 withCompletionCallback:(CDUnknownBlockType)arg2;
- (void)invokeWithPipeInfo:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

