//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALCBaseCardView.h"

@class UIImageView, UILabel, UITapGestureRecognizer, UIView;

@interface ALCFirstCardView : ALCBaseCardView
{
    UIImageView *_iconView;
    UILabel *_captionLabel;
    UILabel *_mainContentLabel;
    UILabel *_secondContentLabel;
    UILabel *_thirdContentLabel;
    UIView *_stripView;
    UIImageView *_backgroundImageView;
    UIView *_actionView;
    UIView *_optionView;
    UIImageView *_optionImageView;
    UITapGestureRecognizer *_actionRecognizer;
}

+ (double)cardHeight:(id)arg1;
@property(retain, nonatomic) UITapGestureRecognizer *actionRecognizer; // @synthesize actionRecognizer=_actionRecognizer;
@property(retain, nonatomic) UIImageView *optionImageView; // @synthesize optionImageView=_optionImageView;
@property(retain, nonatomic) UIView *optionView; // @synthesize optionView=_optionView;
@property(retain, nonatomic) UIView *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIView *stripView; // @synthesize stripView=_stripView;
@property(retain, nonatomic) UILabel *thirdContentLabel; // @synthesize thirdContentLabel=_thirdContentLabel;
@property(retain, nonatomic) UILabel *secondContentLabel; // @synthesize secondContentLabel=_secondContentLabel;
@property(retain, nonatomic) UILabel *mainContentLabel; // @synthesize mainContentLabel=_mainContentLabel;
@property(retain, nonatomic) UILabel *captionLabel; // @synthesize captionLabel=_captionLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void).cxx_destruct;
- (void)adjustOptionView;
- (void)optionTapped;
- (void)initOptionView:(id)arg1;
- (void)layoutSubviews;
- (void)actionTouched:(id)arg1;
- (void)initSubviews:(id)arg1;
- (void)renewWithCard:(id)arg1;
- (id)initWithCard:(id)arg1;

@end

