//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALPAudioMessage;

@protocol ALPAudioRecordDelegate <NSObject>

@optional
- (void)recordWillFinishForTimeOut;
- (void)recordFinishWithALPAudioMessage:(ALPAudioMessage *)arg1 recordFinishState:(int)arg2;
@end

