//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class ALPAssetBankCardDetailHeaderCardView, ALPAssetBankCardDetailHeaderRepayView, AssetBankCardItem, NSArray, UIImageView, UILabel;

@interface ALPAssetBankCardDetailHeaderView : UIView
{
    ALPAssetBankCardDetailHeaderCardView *_cardView;
    UIView *_girdleView;
    UILabel *_girdleLabel;
    UIImageView *_girdleIconView;
    ALPAssetBankCardDetailHeaderRepayView *_repayView;
    AssetBankCardItem *_cardInfo;
    NSArray *_repayInfoArray;
    id <ALPAssetBankCardDetailHeaderDelegate> _delegate;
}

@property(nonatomic) __weak id <ALPAssetBankCardDetailHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateQuickPayCard;
- (void)buildGirdleView;
- (void)buildAllView;
- (void)layoutSubviews;
- (id)initWithBankCardItem:(id)arg1 repayInfoArray:(id)arg2;

@end

