//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEEDataController.h"

#import "ALPAssetBankCardDetailCellDelegate.h"
#import "ALPAssetBankCardDetailHeaderDelegate.h"
#import "PromotionCenterDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class APTableView, APWealthRpcCaller, AssetBankCardDetailRes, NSDictionary, NSString, UIView, UIWebView, WEALTHBankCard;

@interface ALPAssetBankCardDetailViewController : BEEDataController <UITableViewDataSource, UITableViewDelegate, UIActionSheetDelegate, PromotionCenterDelegate, ALPAssetBankCardDetailCellDelegate, ALPAssetBankCardDetailHeaderDelegate>
{
    APTableView *_tableView;
    UIView *_bannerView;
    APWealthRpcCaller *_rpcCaller;
    AssetBankCardDetailRes *_dateModal;
    WEALTHBankCard *_detailReq;
    NSDictionary *_launchOptions;
    _Bool _isSelfCard;
    UIWebView *_phoneCallView;
    long long _cardCount;
    NSString *_source;
}

@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(nonatomic) long long cardCount; // @synthesize cardCount=_cardCount;
- (void).cxx_destruct;
- (id)findLastViewController:(id)arg1;
- (void)updateBankCardQuickPay;
- (void)updatebankCardCallTel:(id)arg1;
- (void)updateBankCardGotoBill;
- (void)updateBankCardSearchMap;
- (void)updateBankCardDetailCell:(long long)arg1;
- (void)promotionViewDidFinishLoading:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)createViewForHeaderSection:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)cacheKey;
- (void)loadError:(id)arg1;
- (id)emptyText;
- (void)loadContent;
- (id)loadOnline;
- (void)queryBalance:(long long)arg1;
- (void)removeBankCard;
- (void)removeBankCardWithReq;
- (void)removeBankCardWithVIEngine;
- (id)createTableViewCell:(id)arg1;
- (void)updateAdView:(id)arg1;
- (void)requestAdFromPromtion;
- (_Bool)isDeleteCard;
- (void)clickMoreButtonForDeposit;
- (void)clickMoreButtonForCredit;
- (void)updateNavigationItem:(id)arg1;
- (void)clickOnFootView;
- (void)buildTableView;
- (void)buildAll;
- (void)clearInit;
- (id)initWithDetailManagerInfo:(id)arg1;
- (id)initWithDetailManager:(id)arg1 cardType:(id)arg2 instId:(id)arg3;
- (id)initWithDetailManager:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

