//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APWealthTableView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString;

@interface ALPFundProfitListView : APWealthTableView <UITableViewDataSource, UITableViewDelegate>
{
    NSArray *_itemArray;
    NSString *_min;
    NSString *_max;
    NSString *_minItemValue;
    long long _itenmMinLength;
}

@property(nonatomic) long long itenmMinLength; // @synthesize itenmMinLength=_itenmMinLength;
@property(retain, nonatomic) NSString *minItemValue; // @synthesize minItemValue=_minItemValue;
@property(retain, nonatomic) NSString *max; // @synthesize max=_max;
@property(retain, nonatomic) NSString *min; // @synthesize min=_min;
@property(retain, nonatomic) NSArray *itemArray; // @synthesize itemArray=_itemArray;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)getRate:(long long)arg1;
- (long long)getItemMinLength;
- (void)setListViewInfo:(id)arg1 min:(id)arg2 minItemValue:(id)arg3 max:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

