//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCDTViewController.h"

#import "MessagePhotoViewDelegate.h"
#import "UITextViewDelegate.h"

@class MessagePhotoView, NSString, SWTextView, UIImage, UILabel, UIView;

@interface ALPFeedbackViewController : SCDTViewController <MessagePhotoViewDelegate, UITextViewDelegate>
{
    id <SAAccountService> _accountService;
    _Bool _canEdit;
    SWTextView *_contentView;
    MessagePhotoView *_photoView;
    UIView *_baseView;
    UILabel *_remainNumberLabel;
    NSString *_tagString;
    NSString *_perfixString;
    UIImage *_defualtImage;
}

@property(retain, nonatomic) UIImage *defualtImage; // @synthesize defualtImage=_defualtImage;
@property(retain, nonatomic) NSString *perfixString; // @synthesize perfixString=_perfixString;
@property(retain, nonatomic) NSString *tagString; // @synthesize tagString=_tagString;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(retain, nonatomic) UILabel *remainNumberLabel; // @synthesize remainNumberLabel=_remainNumberLabel;
@property(retain, nonatomic) UIView *baseView; // @synthesize baseView=_baseView;
@property(retain, nonatomic) MessagePhotoView *photoView; // @synthesize photoView=_photoView;
@property(retain, nonatomic) SWTextView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getImageArray;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)buildReq:(id)arg1 mobilePhoneIfNotLogin:(id)arg2;
- (void)afterCommit:(id)arg1;
- (void)SubmitCompletion:(id)arg1 withException:(id)arg2;
- (void)submitBug;
- (void)didReceiveMemoryWarning;
- (void)addPicker:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)viewDidLoad;
- (id)initWith:(id)arg1 perfixString:(id)arg2 image:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

