//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALPListViewController.h"

@class ALPMainPassEmptyView, ALPMainPassListModel, ALPMainPassListViewDataSource, ALPMainPassListViewDelegate, ALPPassShareManager, APExceptionView, NSString;

@interface ALPMainPassListViewController : ALPListViewController
{
    _Bool _pageHasCacheData;
    long long _type;
    NSString *_uid;
    ALPMainPassListModel *_mainPassListModel;
    ALPMainPassListViewDataSource *_ds;
    ALPMainPassListViewDelegate *_dl;
    APExceptionView *_emptyView;
    APExceptionView *_errorView;
    ALPMainPassEmptyView *_mainEmptyView;
    ALPPassShareManager *_shareManager;
}

@property(retain, nonatomic) ALPPassShareManager *shareManager; // @synthesize shareManager=_shareManager;
@property(nonatomic) _Bool pageHasCacheData; // @synthesize pageHasCacheData=_pageHasCacheData;
@property(retain, nonatomic) ALPMainPassEmptyView *mainEmptyView; // @synthesize mainEmptyView=_mainEmptyView;
@property(retain, nonatomic) APExceptionView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) APExceptionView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) ALPMainPassListViewDelegate *dl; // @synthesize dl=_dl;
@property(retain, nonatomic) ALPMainPassListViewDataSource *ds; // @synthesize ds=_ds;
@property(retain, nonatomic) ALPMainPassListModel *mainPassListModel; // @synthesize mainPassListModel=_mainPassListModel;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)clickExclusiveRed;
- (void)removeData:(id)arg1;
- (void)removeCellWithItem:(id)arg1;
- (void)removeCacheWithPassId:(id)arg1;
- (void)updateCacheItemWithPassId:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)updateCacheObjectWithBlock:(CDUnknownBlockType)arg1;
- (void)cancelSharePassSuccess:(id)arg1 withStatus:(id)arg2 presentStatus:(_Bool)arg3;
- (void)cancelShareItem:(id)arg1;
- (void)sharePassSuccess:(id)arg1 withStatus:(id)arg2;
- (void)shareItem:(id)arg1;
- (void)presentPassFail:(id)arg1 result:(id)arg2;
- (void)presentPassSuccess:(id)arg1 withStatus:(id)arg2;
- (void)presentItem:(id)arg1;
- (void)shouldDeleteByNotifycation:(id)arg1;
- (void)presentSuccessByNotifycation:(id)arg1;
- (void)shareSuccessByNotifycation:(id)arg1;
- (void)cancelShareSuccessByNotifycation:(id)arg1;
- (id)findItemByPassId:(id)arg1;
- (void)clickHistoryBtn;
- (void)queryLocation;
- (void)gotoCellSelected:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)reload;
- (void)showModel:(id)arg1;
- (void)showError:(id)arg1 withModel:(id)arg2;
- (void)showNoResult:(id)arg1;
- (void)showLoading:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)pageSpm;
- (long long)preferredStatusBarStyle;
- (id)initWithType:(long long)arg1 from:(long long)arg2;
- (id)initWithType:(long long)arg1;

@end

