//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface aluAccountInfoBox : UIView
{
}

+ (id)accountInfoBoxWithFrame:(struct CGRect)arg1 HeadUrl:(id)arg2 defaultImage:(id)arg3 infoDic:(id)arg4;
- (id)addAccountInfo:(id)arg1 inFrame:(struct CGRect)arg2;

@end

