//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANXBaseResponse.h"

@class ApplyKeyResponse, OfflineKeyInfo;

@interface ANXApplyKeyResponse : ANXBaseResponse
{
    ApplyKeyResponse *_response;
}

@property(retain, nonatomic) ApplyKeyResponse *response; // @synthesize response=_response;
- (void).cxx_destruct;
- (id)baseInfo;
@property(readonly, nonatomic) OfflineKeyInfo *offlineKeyInfo;
- (id)reformWithResponse:(id)arg1;

@end

