//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTViewController.h"

@class UINavigationItem;

@interface ANXBaseOfflinePayViewController : DTViewController
{
    UINavigationItem *_containerNavigationItem;
}

@property(retain, nonatomic) UINavigationItem *containerNavigationItem; // @synthesize containerNavigationItem=_containerNavigationItem;
- (void).cxx_destruct;
- (void)initializeSetup;
- (void)initializeConstraints;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

