//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANXBaseOfflinePayViewController.h"

#import "UIViewControllerTransitioningDelegate.h"

@class ANXModalPresentAnimation, APButton, NSString, UIImageView, UILabel, UIView;

@interface ANXInstructionOfflinePayViewController : ANXBaseOfflinePayViewController <UIViewControllerTransitioningDelegate>
{
    CDUnknownBlockType _completion;
    UIView *_bgView;
    UIImageView *_content;
    UIView *_container;
    UILabel *_tips1;
    UILabel *_tips1Detail;
    UILabel *_tips2;
    UILabel *_tips3;
    UILabel *_tips3Detail;
    UIView *_seperateLine;
    UILabel *_tipsEnhance;
    UILabel *_tips;
    APButton *_closeButton;
    ANXModalPresentAnimation *_modalAnimator;
}

+ (void)showFromViewController:(id)arg1 onComplete:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) ANXModalPresentAnimation *modalAnimator; // @synthesize modalAnimator=_modalAnimator;
@property(nonatomic) __weak APButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak UILabel *tips; // @synthesize tips=_tips;
@property(nonatomic) __weak UILabel *tipsEnhance; // @synthesize tipsEnhance=_tipsEnhance;
@property(nonatomic) __weak UIView *seperateLine; // @synthesize seperateLine=_seperateLine;
@property(nonatomic) __weak UILabel *tips3Detail; // @synthesize tips3Detail=_tips3Detail;
@property(nonatomic) __weak UILabel *tips3; // @synthesize tips3=_tips3;
@property(nonatomic) __weak UILabel *tips2; // @synthesize tips2=_tips2;
@property(nonatomic) __weak UILabel *tips1Detail; // @synthesize tips1Detail=_tips1Detail;
@property(nonatomic) __weak UILabel *tips1; // @synthesize tips1=_tips1;
@property(nonatomic) __weak UIView *container; // @synthesize container=_container;
@property(nonatomic) __weak UIImageView *content; // @synthesize content=_content;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)didPressedBackView:(id)arg1;
- (void)initializeConstraints;
- (void)initializeSetup;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

