//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ANXPayOfflinePayModel, NSString;

@protocol ANXPayOfflinePayModelDelegate <NSObject>
- (void)model:(ANXPayOfflinePayModel *)arg1 isConnectedOverInternet:(_Bool)arg2;
- (void)model:(ANXPayOfflinePayModel *)arg1 closedServiceExceptionWithCode:(NSString *)arg2;
- (void)model:(ANXPayOfflinePayModel *)arg1 closedServiceFailWithCode:(NSString *)arg2 failTips:(NSString *)arg3;
@end

