//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APBEventProtocol.h"

@class APBEventListener, APBResponse, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer;

@interface APBReactor : NSObject <APBEventProtocol>
{
    NSMutableDictionary *_currentPipeInfo;
    APBEventListener *_eventListener;
    id <IBioAuthFactor> _factor;
    NSArray *_tasks;
    NSMutableArray *_parallelTasks;
    CDUnknownBlockType _rcb;
    id <IBioAuthTask> _currentTask;
    long long _currentTaskIndex;
    APBResponse *_response;
    NSTimer *_globalTimer;
    NSTimer *_taskTimer;
    NSDictionary *_globalConfig;
    NSDictionary *_taskConfig;
}

@property(retain, nonatomic) NSDictionary *taskConfig; // @synthesize taskConfig=_taskConfig;
@property(retain, nonatomic) NSDictionary *globalConfig; // @synthesize globalConfig=_globalConfig;
@property(retain, nonatomic) NSTimer *taskTimer; // @synthesize taskTimer=_taskTimer;
@property(retain, nonatomic) NSTimer *globalTimer; // @synthesize globalTimer=_globalTimer;
@property(retain, nonatomic) APBResponse *response; // @synthesize response=_response;
@property(nonatomic) long long currentTaskIndex; // @synthesize currentTaskIndex=_currentTaskIndex;
@property(nonatomic) __weak id <IBioAuthTask> currentTask; // @synthesize currentTask=_currentTask;
@property(copy, nonatomic) CDUnknownBlockType rcb; // @synthesize rcb=_rcb;
@property(retain, nonatomic) NSMutableArray *parallelTasks; // @synthesize parallelTasks=_parallelTasks;
@property(retain, nonatomic) NSArray *tasks; // @synthesize tasks=_tasks;
@property(retain, nonatomic) id <IBioAuthFactor> factor; // @synthesize factor=_factor;
@property(retain, nonatomic) APBEventListener *eventListener; // @synthesize eventListener=_eventListener;
@property(nonatomic) __weak NSMutableDictionary *currentPipeInfo; // @synthesize currentPipeInfo=_currentPipeInfo;
- (void).cxx_destruct;
- (void)eventTriggered:(id)arg1;
- (void)runTask:(long long)arg1 withPipeInfo:(id)arg2;
- (void)processParallelStateChange:(id)arg1 withObject:(id)arg2;
- (void)processStateChange:(id)arg1;
- (void)onTaskTimer:(id)arg1;
- (void)onGlobalTimer:(id)arg1;
- (void)internalExit;
- (void)externalExit;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)execBackwardCommand:(id)arg1;
- (void)exec:(id)arg1 withCompletionCallback:(CDUnknownBlockType)arg2;
- (void)runWithGlobalConfig:(id)arg1 withResponseCallback:(CDUnknownBlockType)arg2;
- (void)setTaskList:(id)arg1;
- (_Bool)isBusy;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

