//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APContactBaseViewController.h"

@class APContactMultiSelectView, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface APContactCombinedMultiSelectViewController : APContactBaseViewController
{
    _Bool _needMobileContact;
    _Bool _enableSelectNone;
    NSArray *_defaultSelects;
    NSString *_confirmBtnTitle;
    long long _maxMultiCount;
    NSString *_overMaxText;
    NSArray *_customRecentArray;
    NSArray *_multiSelectContacts;
    NSArray *_needAddItems;
    NSMutableArray *_selectedContactInfos;
    NSMutableDictionary *_selectedUids;
}

@property(nonatomic) _Bool enableSelectNone; // @synthesize enableSelectNone=_enableSelectNone;
@property(retain, nonatomic) NSMutableDictionary *selectedUids; // @synthesize selectedUids=_selectedUids;
@property(retain, nonatomic) NSMutableArray *selectedContactInfos; // @synthesize selectedContactInfos=_selectedContactInfos;
@property(retain, nonatomic) NSArray *needAddItems; // @synthesize needAddItems=_needAddItems;
@property(nonatomic) _Bool needMobileContact; // @synthesize needMobileContact=_needMobileContact;
@property(retain, nonatomic) NSArray *multiSelectContacts; // @synthesize multiSelectContacts=_multiSelectContacts;
@property(retain, nonatomic) NSArray *customRecentArray; // @synthesize customRecentArray=_customRecentArray;
@property(retain, nonatomic) NSString *overMaxText; // @synthesize overMaxText=_overMaxText;
@property(nonatomic) long long maxMultiCount; // @synthesize maxMultiCount=_maxMultiCount;
@property(retain, nonatomic) NSString *confirmBtnTitle; // @synthesize confirmBtnTitle=_confirmBtnTitle;
@property(retain, nonatomic) NSArray *defaultSelects; // @synthesize defaultSelects=_defaultSelects;
- (void).cxx_destruct;
- (id)getCommonLogArray;
- (id)cellClassNameInCommonView:(id)arg1 item:(id)arg2;
- (void)commonView:(id)arg1 configCell:(id)arg2 item:(id)arg3;
- (void)loadingViewShow:(_Bool)arg1;
- (void)refreshRightButtonWithCount:(long long)arg1;
- (void)selectionDidChangeInCommonView:(id)arg1;
- (void)dealClickConfirmBtn:(id)arg1 params:(id)arg2;
- (void)handleSubmition;
- (void)didClickConfirmBtn:(id)arg1;
- (id)defaultSelectedItemsInCommonView:(id)arg1;
- (void)reloadContacts;
- (void)loadContact;
- (void)adjustFrames;
- (void)setupSelectView;
- (void)setupRightBarBtnItem;
- (void)setupUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)configWithDict:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(retain, nonatomic) APContactMultiSelectView *selectView; // @dynamic selectView;

@end

