//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPassBaseBizViewController.h"

@class APExceptionView, NSString;

@interface APDeletedPassViewController : APPassBaseBizViewController
{
    NSString *_tips;
    APExceptionView *_emptyView;
}

@property(retain, nonatomic) APExceptionView *emptyView; // @synthesize emptyView=_emptyView;
@property(copy, nonatomic) NSString *tips; // @synthesize tips=_tips;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithTips:(id)arg1;

@end

