//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APFBaseTask.h"

#import "NlsRecognizerDelegate.h"

@class NSString, NlsRecognizer;

@interface APFASRParallelTask : APFBaseTask <NlsRecognizerDelegate>
{
    _Bool _isRunning;
    _Bool _setVadFlag;
    _Bool _isUserSpeaking;
    id <APFASRDelegate> _delegate;
    NlsRecognizer *_recognizer;
    long long _voiceVolum;
}

@property(nonatomic) long long voiceVolum; // @synthesize voiceVolum=_voiceVolum;
@property(nonatomic) _Bool isUserSpeaking; // @synthesize isUserSpeaking=_isUserSpeaking;
@property(nonatomic) _Bool setVadFlag; // @synthesize setVadFlag=_setVadFlag;
@property(retain, nonatomic) NlsRecognizer *recognizer; // @synthesize recognizer=_recognizer;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(nonatomic) __weak id <APFASRDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)recognizerDidStopRecording:(id)arg1;
- (void)recognizer:(id)arg1 recordingWithVoiceVolume:(unsigned long long)arg2;
- (void)recognizer:(id)arg1 didCompleteRecognizingWithResult:(id)arg2 error:(id)arg3;
- (void)pause;
- (void)stop;
- (void)reStart;
- (void)start;
- (void)invokeWithPipeInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

