//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class BisFaceContent, NSMutableArray, NSString;

@interface APFBisFaceUploadContent : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasPanoImage;
    NSMutableArray *_aliveImages;
    NSMutableArray *_actionImages;
    BisFaceContent *_panoImage;
    NSMutableArray *_monitorImages;
    NSMutableArray *_video;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *video; // @synthesize video=_video;
@property(retain, nonatomic) NSMutableArray *monitorImages; // @synthesize monitorImages=_monitorImages;
@property(retain, nonatomic) BisFaceContent *panoImage; // @synthesize panoImage=_panoImage;
@property(retain, nonatomic) NSMutableArray *actionImages; // @synthesize actionImages=_actionImages;
@property(retain, nonatomic) NSMutableArray *aliveImages; // @synthesize aliveImages=_aliveImages;
@property(readonly) _Bool hasPanoImage; // @synthesize hasPanoImage=_hasPanoImage;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addVideo:(id)arg1;
- (void)setVideoArray:(id)arg1;
- (void)addMonitorImages:(id)arg1;
- (void)setMonitorImagesArray:(id)arg1;
- (void)addActionImages:(id)arg1;
- (void)setActionImagesArray:(id)arg1;
- (void)addAliveImages:(id)arg1;
- (void)setAliveImagesArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

