//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface APFireWorkScene : UIView
{
    NSArray *_fireworks;
    NSArray *_trackLines;
}

@property(retain, nonatomic) NSArray *trackLines; // @synthesize trackLines=_trackLines;
@property(retain, nonatomic) NSArray *fireworks; // @synthesize fireworks=_fireworks;
- (void).cxx_destruct;
- (void)showFireWorkToTarget:(struct CGPoint)arg1 withColor:(id)arg2 bombBlock:(CDUnknownBlockType)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

