//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APHealthService.h"

@class CLLocation, NSDate, NSString, NSTimer;

@interface APHealthServiceImpl : NSObject <APHealthService>
{
    _Bool _readMotion;
    _Bool _closeBothSource;
    _Bool _syncing;
    _Bool _fetchHealthData;
    _Bool _readStepCounterSuccess;
    CLLocation *_location;
    NSString *_syncTimeStr;
    NSTimer *_timerOut;
    long long _stepCounter;
    NSString *_reportDeviceInfoTimeStr;
    NSDate *_doUpdateDate;
}

@property(retain) NSDate *doUpdateDate; // @synthesize doUpdateDate=_doUpdateDate;
@property(retain) NSString *reportDeviceInfoTimeStr; // @synthesize reportDeviceInfoTimeStr=_reportDeviceInfoTimeStr;
@property _Bool readStepCounterSuccess; // @synthesize readStepCounterSuccess=_readStepCounterSuccess;
@property long long stepCounter; // @synthesize stepCounter=_stepCounter;
@property _Bool fetchHealthData; // @synthesize fetchHealthData=_fetchHealthData;
@property(retain, nonatomic) NSTimer *timerOut; // @synthesize timerOut=_timerOut;
@property _Bool syncing; // @synthesize syncing=_syncing;
@property(retain) NSString *syncTimeStr; // @synthesize syncTimeStr=_syncTimeStr;
@property(retain) CLLocation *location; // @synthesize location=_location;
@property _Bool closeBothSource; // @synthesize closeBothSource=_closeBothSource;
@property _Bool readMotion; // @synthesize readMotion=_readMotion;
- (void).cxx_destruct;
- (_Bool)readReportDeviceInfoConfig;
- (long long)intervalEnterForeground;
- (long long)intervalReportDeviceInfo;
- (void)checkPedometerData;
- (_Bool)needReadPedometerData;
- (_Bool)forceReadPedometerConfig;
- (_Bool)readHealthConfig;
- (void)endDoUpdate;
- (void)syncUpdateTime;
- (id)getOnTheDayDate:(id)arg1;
- (void)doQueryStepWithSource:(id)arg1 resultHandle:(CDUnknownBlockType)arg2;
- (void)statisticsHealthData:(CDUnknownBlockType)arg1;
- (void)statisticsPedometerData:(CDUnknownBlockType)arg1;
- (void)requestMotionAuthorizationWithHandler:(CDUnknownBlockType)arg1;
- (void)readBothSourceWithBlock:(CDUnknownBlockType)arg1;
- (void)doUpdate;
- (_Bool)writeDoUpdate;
- (void)remoteDoUpdate:(id)arg1;
- (void)timerOutFired;
- (void)createTimerOut;
- (long long)getStepCount;
- (void)uploadHealthDataForce;
- (void)uploadWithEnterForeground;
- (void)requestDoUpdateHealthData;
- (void)doReportDeviceInfoNotificationSuccess;
- (void)reportDeviceInfoNotificationSuccess;
- (void)updateReadMotion:(_Bool)arg1;
- (void)start;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

