//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APChatTapTextDelegate.h"
#import "DTService.h"

@class NSArray, NSString;

@interface APIGService : NSObject <APChatTapTextDelegate, DTService>
{
    NSString *_targetId;
    NSString *_chatType;
    NSString *_msg;
    NSArray *_switchConfig;
    NSString *_switchStr;
}

@property(copy, nonatomic) NSString *switchStr; // @synthesize switchStr=_switchStr;
@property(retain, nonatomic) NSArray *switchConfig; // @synthesize switchConfig=_switchConfig;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(copy, nonatomic) NSString *chatType; // @synthesize chatType=_chatType;
@property(copy, nonatomic) NSString *targetId; // @synthesize targetId=_targetId;
- (void).cxx_destruct;
- (id)extractConfig;
- (void)handleScheme:(id)arg1;
- (_Bool)canHandleMessage:(id)arg1;
- (_Bool)handlerShouldHandleText:(id)arg1;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

