//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImage, UIImageView, UILabel;

@interface APIGScoreBoard : UIView
{
    long long _score;
    UIImage *_avatar;
    NSString *_nickname;
    UILabel *_titleLabel;
    UILabel *_scoreLabel;
    UILabel *_nickLabel;
    UIImageView *_avatarView;
}

@property(retain, nonatomic) UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UILabel *nickLabel; // @synthesize nickLabel=_nickLabel;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) long long score; // @synthesize score=_score;
- (void).cxx_destruct;
- (id)truncateString:(id)arg1 withLength:(long long)arg2;
- (void)layoutSubviews;
- (void)drawSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 score:(long long)arg2 avatar:(id)arg3 nickname:(id)arg4;

@end

