//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APLogViewControllerManagerHooker : NSObject
{
}

+ (void)updateViewController:(id)arg1 spmId:(id)arg2 entityId:(id)arg3 extendParam:(id)arg4;
+ (void)willDisappearViewController:(id)arg1;
+ (void)didAppearViewController:(id)arg1 spmId:(id)arg2 entityId:(id)arg3;
+ (_Bool)blacklistViewController:(id)arg1;
+ (_Bool)validViewController:(id)arg1;

@end

