//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APBaseAuthHandler.h"

#import "LBSAuthGuideDelegate.h"

@class NSString;

@interface APLocationAuthAdapter : APBaseAuthHandler <LBSAuthGuideDelegate>
{
    _Bool _force;
    double _customTimeout;
}

@property(nonatomic) double customTimeout; // @synthesize customTimeout=_customTimeout;
@property(nonatomic) _Bool force; // @synthesize force=_force;
- (_Bool)isShowing;
- (void)didCancelButtonClicked;
- (void)didActionButtonClicked:(long long)arg1;
- (long long)guideNecessaryState;
- (_Bool)tryToShowGuideWithBizType:(id)arg1 options:(id)arg2 andCallback:(CDUnknownBlockType)arg3;
- (void)resolveOptions:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

