//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSTimer;

@interface APLogManager : NSObject
{
    NSObject<OS_dispatch_queue> *_writeLogQueue;
    NSMutableArray *_crashTimestampArray;
    _Bool _uploadableByServer;
    _Bool _uploadableByUser;
    NSMutableArray *_indexArray;
    NSMutableDictionary *_bizTypeDictionary;
    NSMutableDictionary *_externalSwitchDict;
    unsigned long long _bgTask;
    NSTimer *_bgTaskKillTimer;
    _Bool _useSafeURL;
    _Bool _newManualSpm;
    double _profileUpdateTime;
}

+ (id)sharedInstance;
+ (void)initialize;
@property _Bool newManualSpm; // @synthesize newManualSpm=_newManualSpm;
@property _Bool useSafeURL; // @synthesize useSafeURL=_useSafeURL;
@property double profileUpdateTime; // @synthesize profileUpdateTime=_profileUpdateTime;
- (void).cxx_destruct;
- (void)checkLogs;
- (void)resumeLogUploading;
- (void)suspendLogUploadingForSeconds:(int)arg1;
- (_Bool)checkDate:(id)arg1 inCrashTimestmpArray:(id)arg2;
- (void)uploadLogInArray:(id)arg1 bizType:(id)arg2;
- (void)uploadLogInArray:(id)arg1;
- (void)flushLogsUseConfigs;
- (void)flushAllLog;
- (void)uploadUnsyncLogInFile:(id)arg1 bizType:(id)arg2 filterBlock:(CDUnknownBlockType)arg3;
- (void)uploadUnsyncLogInFile:(id)arg1 filterBlock:(CDUnknownBlockType)arg2;
- (void)uploadCrashLogInFile:(id)arg1;
- (id)APLogGetOldLogServerURL;
- (id)APLogGetNewLogServerURL;
- (void)uploadData:(id)arg1 bizType:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)logIndexForHeader:(id)arg1;
- (void)writeLogWithContext:(id)arg1;
- (_Bool)restoreInterface;
- (_Bool)switchWithKey:(id)arg1;
- (void)setupTimeForCheckFileSize;
- (void)fetchMessage:(id)arg1;
- (void)setupListenSyncNotification;
- (void)onBgTaskKill;
- (void)clearBgTaskKillTimer;
- (_Bool)startBgTaskKillTimer;
- (void)endBgTask;
- (_Bool)beginBgTask;
- (void)manualSpmWithExternalSwitch:(id)arg1;
- (void)safeURLWithExternalSwitch:(id)arg1;
- (id)externalSwitchValueForKey:(id)arg1;
- (void)setExternalSwitchValue:(id)arg1 forKey:(id)arg2;
- (void)setupExternalSwitch;
- (void)setupBackgroundRunning;
- (id)init;

@end

