//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSString;

@interface APLocationManager : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_coreLocationManager;
    id <APLocationManagerDelegate> _delegate;
    double _startTime;
}

@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) __weak id <APLocationManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CLLocationManager *coreLocationManager; // @synthesize coreLocationManager=_coreLocationManager;
- (void).cxx_destruct;
- (void)legacyLoggingWithMethodName:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (id)getLBSLocation:(id)arg1;
- (void)doProcessCachedLocation;
- (void)doProcessLocation:(id)arg1 manager:(id)arg2;
- (id)locationToDict:(id)arg1;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocationWithCacheTimeout:(int)arg1;
- (void)startUpdatingLocation;
- (void)setupLocationManager:(double)arg1 accuracy:(double)arg2;
- (void)addBehaviorLocationPointWithSuccess:(_Bool)arg1 usingCache:(_Bool)arg2 controllerName:(id)arg3 location:(id)arg4 errorCode:(long long)arg5;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

