//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APNumericKeyboardButtonDismiss.h"

@interface APNumericKeyboardButtonDismiss_IpadIos7 : APNumericKeyboardButtonDismiss
{
}

- (void)drawRect:(struct CGRect)arg1;

@end

