//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPassBaseViewController.h"

@class NSString;

@interface APPassBaseBizViewController : APPassBaseViewController
{
    NSString *_bizType;
}

@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)createSubviews;
- (id)initWithBizType:(id)arg1;
- (void)dealloc;

@end

