//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSDictionary, UIImageView, UILabel, UIView;

@interface APPathRouteTableViewCell : UITableViewCell
{
    UIImageView *icon;
    UILabel *detail;
    UILabel *number;
    UIView *lineView;
    _Bool _isFirst;
    _Bool _isLast;
    NSDictionary *_Content;
}

@property(retain, nonatomic) NSDictionary *Content; // @synthesize Content=_Content;
@property(nonatomic) _Bool isLast; // @synthesize isLast=_isLast;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)customUpdateUI;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

