//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppLoadCheckerObject : NSObject
{
    NSString *_clsName;
    NSString *_redirectURLStr;
    NSString *_exceptionalInfo;
}

@property(retain, nonatomic) NSString *exceptionalInfo; // @synthesize exceptionalInfo=_exceptionalInfo;
@property(retain, nonatomic) NSString *redirectURLStr; // @synthesize redirectURLStr=_redirectURLStr;
@property(retain, nonatomic) NSString *clsName; // @synthesize clsName=_clsName;
- (void).cxx_destruct;

@end

