//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AURichLayer.h"

@interface APRichLayer : AURichLayer
{
    struct __CTParagraphStyle *paragraphStyle;
}

- (id)description;
- (void)sizeToFits;
- (void)clearString;
- (struct CGSize)boundingSizeOfAtrributedString:(id)arg1 withWidth:(double)arg2;
- (struct CGSize)boundingSizeOfAtrributedString:(id)arg1;
- (struct CGSize)boundingSizeWithWidth:(double)arg1;
- (struct CGSize)boundingSize;
- (id)appendString:(id)arg1 withStyle:(id)arg2;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)init;

@end

