//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DTService.h"

@class APScanAREnvelope, NSString;

@interface APScanService : NSObject <DTService>
{
    APScanAREnvelope *_envelope;
}

@property(retain, nonatomic) APScanAREnvelope *envelope; // @synthesize envelope=_envelope;
- (void).cxx_destruct;
- (id)getConfigVia:(id)arg1;
- (id)constructDefaultAREConfig;
- (void)clearStatus;
- (void)appDidExitNotification:(id)arg1;
- (void)TabBarSelected:(id)arg1;
- (void)addCustomTab:(id)arg1;
- (void)dealloc;
- (void)willDestroy;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

