//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableArray, NSObject<OS_dispatch_queue>, NSOperationQueue, NSString;

@interface APSelfUploader : NSObject
{
    NSObject<OS_dispatch_queue> *workQueue;
    NSMutableArray *uploadFileArry;
    NSOperationQueue *_networkQueue;
    NSString *_serverURL;
    NSDictionary *_uplaodParam;
    NSString *_currentUser;
}

@property(retain, nonatomic) NSString *currentUser; // @synthesize currentUser=_currentUser;
- (void).cxx_destruct;
- (id)getServerURL;
- (id)getFileName:(id)arg1;
- (id)reFormatTime:(id)arg1;
- (id)buildFileName;
- (void)uploadFile;
- (void)zipFile;
- (void)checkFile;
- (void)enterBackground;
- (_Bool)isReachableViaWiFi;
- (void)stop;
- (void)dealloc;
- (void)startInQueue:(id)arg1;
- (id)initWithParam:(id)arg1;

@end

