//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class APSHOPCENTERNaviCardInfoPB, NSArray, NSString;

@interface APSHOPCENTERBaseShopInfoPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *address; // @dynamic address;
@property(retain, nonatomic) NSString *averagePrice; // @dynamic averagePrice;
@property(retain, nonatomic) NSString *businessHour; // @dynamic businessHour;
@property(nonatomic) int commentCount; // @dynamic commentCount;
@property(retain, nonatomic) NSString *desc; // @dynamic desc;
@property(retain, nonatomic) NSString *distance; // @dynamic distance;
@property(readonly) _Bool hasAddress; // @dynamic hasAddress;
@property(readonly) _Bool hasAveragePrice; // @dynamic hasAveragePrice;
@property(readonly) _Bool hasBusinessHour; // @dynamic hasBusinessHour;
@property(readonly) _Bool hasCommentCount; // @dynamic hasCommentCount;
@property(readonly) _Bool hasDesc; // @dynamic hasDesc;
@property(readonly) _Bool hasDistance; // @dynamic hasDistance;
@property(readonly) _Bool hasLatitude; // @dynamic hasLatitude;
@property(readonly) _Bool hasLogoUrl; // @dynamic hasLogoUrl;
@property(readonly) _Bool hasLongitude; // @dynamic hasLongitude;
@property(readonly) _Bool hasNaviCardInfo; // @dynamic hasNaviCardInfo;
@property(readonly) _Bool hasScore; // @dynamic hasScore;
@property(readonly) _Bool hasShopId; // @dynamic hasShopId;
@property(readonly) _Bool hasShopName; // @dynamic hasShopName;
@property(readonly) _Bool hasTag; // @dynamic hasTag;
@property(readonly) _Bool hasThumbnailLogoUrl; // @dynamic hasThumbnailLogoUrl;
@property(readonly) _Bool hasTotalImgs; // @dynamic hasTotalImgs;
@property(nonatomic) double latitude; // @dynamic latitude;
@property(retain, nonatomic) NSString *logoUrl; // @dynamic logoUrl;
@property(nonatomic) double longitude; // @dynamic longitude;
@property(retain, nonatomic) APSHOPCENTERNaviCardInfoPB *naviCardInfo; // @dynamic naviCardInfo;
@property(nonatomic) double score; // @dynamic score;
@property(retain, nonatomic) NSString *shopId; // @dynamic shopId;
@property(retain, nonatomic) NSString *shopName; // @dynamic shopName;
@property(retain, nonatomic) NSArray *shopServices; // @dynamic shopServices;
@property(retain, nonatomic) NSString *tag; // @dynamic tag;
@property(retain, nonatomic) NSArray *telNos; // @dynamic telNos;
@property(retain, nonatomic) NSString *thumbnailLogoUrl; // @dynamic thumbnailLogoUrl;
@property(nonatomic) int totalImgs; // @dynamic totalImgs;

@end

