//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface APSHOPCENTERCityPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *cityCode; // @dynamic cityCode;
@property(retain, nonatomic) NSString *cityName; // @dynamic cityName;
@property(readonly) _Bool hasCityCode; // @dynamic hasCityCode;
@property(readonly) _Bool hasCityName; // @dynamic hasCityName;

@end

