//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface APSHOPCENTERShopPhotoPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(readonly) _Bool hasImgDesc; // @dynamic hasImgDesc;
@property(readonly) _Bool hasImgTitle; // @dynamic hasImgTitle;
@property(readonly) _Bool hasImgType; // @dynamic hasImgType;
@property(readonly) _Bool hasOrignalUrl; // @dynamic hasOrignalUrl;
@property(readonly) _Bool hasThumbnailUrl; // @dynamic hasThumbnailUrl;
@property(retain, nonatomic) NSString *imgDesc; // @dynamic imgDesc;
@property(retain, nonatomic) NSString *imgTitle; // @dynamic imgTitle;
@property(retain, nonatomic) NSString *imgType; // @dynamic imgType;
@property(retain, nonatomic) NSString *orignalUrl; // @dynamic orignalUrl;
@property(retain, nonatomic) NSString *thumbnailUrl; // @dynamic thumbnailUrl;

@end

