//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface APSHOPCENTERShopDetailRequestPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(readonly) _Bool hasRecommendId; // @dynamic hasRecommendId;
@property(readonly) _Bool hasShopId; // @dynamic hasShopId;
@property(retain, nonatomic) NSString *recommendId; // @dynamic recommendId;
@property(retain, nonatomic) NSString *shopId; // @dynamic shopId;

@end

