//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HKHealthStore, HKQuery, NSOperationQueue, NSRecursiveLock, NSSet;

@interface APStepCounter : NSObject
{
    _Bool _isCMAuthPrompted;
    NSOperationQueue *_queryQueue;
    HKHealthStore *_healthStore;
    NSSet *_sources;
    NSRecursiveLock *_sourceLock;
    CDUnknownBlockType _fusionHandler;
    HKQuery *_observerQuery;
}

@property(retain, nonatomic) HKQuery *observerQuery; // @synthesize observerQuery=_observerQuery;
@property(copy, nonatomic) CDUnknownBlockType fusionHandler; // @synthesize fusionHandler=_fusionHandler;
@property _Bool isCMAuthPrompted; // @synthesize isCMAuthPrompted=_isCMAuthPrompted;
@property(retain, nonatomic) NSRecursiveLock *sourceLock; // @synthesize sourceLock=_sourceLock;
@property(retain, nonatomic) NSSet *sources; // @synthesize sources=_sources;
@property(retain, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
@property(retain, nonatomic) NSOperationQueue *queryQueue; // @synthesize queryQueue=_queryQueue;
- (void).cxx_destruct;
- (void)stopObserverQuery;
- (void)startExecuteObserverQueryWithCallback:(CDUnknownBlockType)arg1;
- (id)stepInfoFusion:(id)arg1 with:(id)arg2;
- (id)getDayStartTimeInNSDateFormateOfDate:(id)arg1;
- (void)queryAppleHKSourceWhenDone:(CDUnknownBlockType)arg1;
- (void)queryStepCountViaHealthKitWithSources:(id)arg1 from:(id)arg2 to:(id)arg3 whenDone:(CDUnknownBlockType)arg4;
- (void)queryTodayStepCountWithSourceOptions:(unsigned long long)arg1 timeout:(double)arg2 whenDone:(CDUnknownBlockType)arg3;
- (void)queryStepCountViaHealthKitFrom:(id)arg1 to:(id)arg2 whenDone:(CDUnknownBlockType)arg3;
- (void)queryStepCountViaMotionFrom:(id)arg1 to:(id)arg2 whenDone:(CDUnknownBlockType)arg3;
- (void)requestAuthForSource:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)authStatusForSource:(long long)arg1;
- (void)setStepCounterDataFusionHandler:(CDUnknownBlockType)arg1;
- (void)setCMAuthStatusDeterminated:(_Bool)arg1;
- (_Bool)isHealthKitAvailable;
- (_Bool)isCoreMotionAvailable;
- (id)init;

@end

