//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APXMMDetail, NSNumber, NSString;

@interface APXMMDetalTotal : NSObject
{
    NSString *_message;
    NSString *_request_id;
    NSNumber *_state;
    APXMMDetail *_data;
}

@property(retain, nonatomic) APXMMDetail *data; // @synthesize data=_data;
@property(retain, nonatomic) NSNumber *state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *request_id; // @synthesize request_id=_request_id;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;

@end

