//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface APXMMusicRemoteBuryModelMaker : NSObject
{
}

+ (id)buildBuryModel:(id)arg1 bizLogMonitor:(id)arg2;
+ (id)buildBuryModel:(id)arg1 ccard:(id)arg2;

@end

