//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class Location, NSString;

@interface ArCrowdAggregationInfo : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasAggregationCenter;
    _Bool _hasCount;
    _Bool _hasAggregationRadius;
    int _count;
    int _aggregationRadius;
    Location *_aggregationCenter;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic) int aggregationRadius; // @synthesize aggregationRadius=_aggregationRadius;
@property(nonatomic) int count; // @synthesize count=_count;
@property(retain, nonatomic) Location *aggregationCenter; // @synthesize aggregationCenter=_aggregationCenter;
@property(readonly) _Bool hasAggregationRadius; // @synthesize hasAggregationRadius=_hasAggregationRadius;
@property(readonly) _Bool hasCount; // @synthesize hasCount=_hasCount;
@property(readonly) _Bool hasAggregationCenter; // @synthesize hasAggregationCenter=_hasAggregationCenter;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

