//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ARResource : NSObject
{
    NSMutableDictionary *_resourceItems;
}

@property(retain, nonatomic) NSMutableDictionary *resourceItems; // @synthesize resourceItems=_resourceItems;
- (void).cxx_destruct;
- (id)initWithParam:(id)arg1 enginePath:(id)arg2;

@end

