//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ARRecognize : NSObject
{
    float _version;
    NSString *_engineEvent;
    NSString *_engineName;
    NSString *_recType;
    NSString *_engineConfigPath;
    NSString *_modelPath;
}

@property(nonatomic) float version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *modelPath; // @synthesize modelPath=_modelPath;
@property(retain, nonatomic) NSString *engineConfigPath; // @synthesize engineConfigPath=_engineConfigPath;
@property(retain, nonatomic) NSString *recType; // @synthesize recType=_recType;
@property(retain, nonatomic) NSString *engineName; // @synthesize engineName=_engineName;
@property(retain, nonatomic) NSString *engineEvent; // @synthesize engineEvent=_engineEvent;
- (void).cxx_destruct;
- (id)initWithParam:(id)arg1 recPath:(id)arg2;

@end

