//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface ArrivingTypePB : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasTypeName;
    _Bool _hasTypeValue;
    _Bool _hasAvaliableMoney;
    NSString *_typeName;
    NSString *_typeValue;
    NSString *_avaliableMoney;
    NSMutableArray *_arrivingTypeQuota;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *arrivingTypeQuota; // @synthesize arrivingTypeQuota=_arrivingTypeQuota;
@property(retain, nonatomic) NSString *avaliableMoney; // @synthesize avaliableMoney=_avaliableMoney;
@property(retain, nonatomic) NSString *typeValue; // @synthesize typeValue=_typeValue;
@property(retain, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(readonly) _Bool hasAvaliableMoney; // @synthesize hasAvaliableMoney=_hasAvaliableMoney;
@property(readonly) _Bool hasTypeValue; // @synthesize hasTypeValue=_hasTypeValue;
@property(readonly) _Bool hasTypeName; // @synthesize hasTypeName=_hasTypeName;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addArrivingTypeQuota:(id)arg1;
- (void)setArrivingTypeQuotaArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

