//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NYFuCardPopViewMerchantInfo;

@interface ARScanARLuckyModel : NSObject
{
    unsigned long long _luckyType;
    NSString *_coverImageCloudId;
    NYFuCardPopViewMerchantInfo *_luckyCardInfo;
}

@property(retain, nonatomic) NYFuCardPopViewMerchantInfo *luckyCardInfo; // @synthesize luckyCardInfo=_luckyCardInfo;
@property(copy, nonatomic) NSString *coverImageCloudId; // @synthesize coverImageCloudId=_coverImageCloudId;
@property(nonatomic) unsigned long long luckyType; // @synthesize luckyType=_luckyType;
- (void).cxx_destruct;

@end

