//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class ALAssetsGroup;

@interface AssetGroupViewCell : UITableViewCell
{
    ALAssetsGroup *_assetsGroup;
}

@property(retain, nonatomic) ALAssetsGroup *assetsGroup; // @synthesize assetsGroup=_assetsGroup;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)bind:(id)arg1;

@end

