//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTNavigationController.h"

@class ALAssetsFilter, NSMutableArray, NSPredicate;

@interface AssetPickerViewController : DTNavigationController
{
    _Bool _showCancelButton;
    _Bool _showEmptyGroups;
    _Bool _isFinishDismissViewController;
    ALAssetsFilter *_assetsFilter;
    NSMutableArray *_indexPathsForSelectedItems;
    long long _maximumNumberOfSelection;
    long long _minimumNumberOfSelection;
    NSPredicate *_selectionFilter;
}

@property(nonatomic) _Bool isFinishDismissViewController; // @synthesize isFinishDismissViewController=_isFinishDismissViewController;
@property(nonatomic) _Bool showEmptyGroups; // @synthesize showEmptyGroups=_showEmptyGroups;
@property(nonatomic) _Bool showCancelButton; // @synthesize showCancelButton=_showCancelButton;
@property(retain, nonatomic) NSPredicate *selectionFilter; // @synthesize selectionFilter=_selectionFilter;
@property(nonatomic) long long minimumNumberOfSelection; // @synthesize minimumNumberOfSelection=_minimumNumberOfSelection;
@property(nonatomic) long long maximumNumberOfSelection; // @synthesize maximumNumberOfSelection=_maximumNumberOfSelection;
@property(retain, nonatomic) NSMutableArray *indexPathsForSelectedItems; // @synthesize indexPathsForSelectedItems=_indexPathsForSelectedItems;
@property(retain, nonatomic) ALAssetsFilter *assetsFilter; // @synthesize assetsFilter=_assetsFilter;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(nonatomic) __weak id <UINavigationControllerDelegate><AssetPickerControllerDelegate> delegate; // @dynamic delegate;

@end

