//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CAGradientLayer, CAShapeLayer;

@interface AXPPeopleFindBtn : UIButton
{
    CAGradientLayer *_gradientLayer;
    CAShapeLayer *_sharpLayer;
}

- (void).cxx_destruct;
- (id)path:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)changeToIntermediateStatus:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

