//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface BackupVcardsReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasVersionId;
    _Bool _hasNeedCount;
    _Bool _hasCurPage;
    _Bool _hasTotalPage;
    _Bool _needCount;
    int _curPage;
    int _totalPage;
    NSMutableArray *_vcardInfos;
    NSString *_versionId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic) int totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) int curPage; // @synthesize curPage=_curPage;
@property(nonatomic) _Bool needCount; // @synthesize needCount=_needCount;
@property(retain, nonatomic) NSString *versionId; // @synthesize versionId=_versionId;
@property(retain, nonatomic) NSMutableArray *vcardInfos; // @synthesize vcardInfos=_vcardInfos;
@property(readonly) _Bool hasTotalPage; // @synthesize hasTotalPage=_hasTotalPage;
@property(readonly) _Bool hasCurPage; // @synthesize hasCurPage=_hasCurPage;
@property(readonly) _Bool hasNeedCount; // @synthesize hasNeedCount=_hasNeedCount;
@property(readonly) _Bool hasVersionId; // @synthesize hasVersionId=_hasVersionId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addVcardInfos:(id)arg1;
- (void)setVcardInfosArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

