//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface BaseRPCRequestInfo : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasTime;
    _Bool _hasIsRoot;
    _Bool _hasSystemType;
    _Bool _hasClientVersion;
    _Bool _hasApdidToken;
    _Bool _isRoot;
    unsigned long long _time;
    NSString *_systemType;
    NSString *_clientVersion;
    NSMutableArray *_extInfo;
    NSString *_apdidToken;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *apdidToken; // @synthesize apdidToken=_apdidToken;
@property(retain, nonatomic) NSMutableArray *extInfo; // @synthesize extInfo=_extInfo;
@property(retain, nonatomic) NSString *clientVersion; // @synthesize clientVersion=_clientVersion;
@property(retain, nonatomic) NSString *systemType; // @synthesize systemType=_systemType;
@property(nonatomic) _Bool isRoot; // @synthesize isRoot=_isRoot;
@property(nonatomic) unsigned long long time; // @synthesize time=_time;
@property(readonly) _Bool hasApdidToken; // @synthesize hasApdidToken=_hasApdidToken;
@property(readonly) _Bool hasClientVersion; // @synthesize hasClientVersion=_hasClientVersion;
@property(readonly) _Bool hasSystemType; // @synthesize hasSystemType=_hasSystemType;
@property(readonly) _Bool hasIsRoot; // @synthesize hasIsRoot=_hasIsRoot;
@property(readonly) _Bool hasTime; // @synthesize hasTime=_hasTime;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addExtInfo:(id)arg1;
- (void)setExtInfoArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

