//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEEFunctionTableController.h"

#import "BEEMusicViewClickDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, paramModel;

@interface BEEMusicListViewController : BEEFunctionTableController <BEEMusicViewClickDelegate, UIScrollViewDelegate>
{
    paramModel *_model;
    NSMutableArray *_resultArray;
    NSMutableArray *_showSongIds;
    _Bool _hasMoreMusicItem;
}

- (void).cxx_destruct;
- (void)openURL:(id)arg1 contentIds:(id)arg2 actionCode:(id)arg3;
- (void)remoteLogger:(id)arg1 actionCode:(id)arg2;
- (void)createTypeAndSource;
- (void)didClickMusicViewForDetailPage:(id)arg1 songId:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)hasNextPage;
- (id)emptyText;
- (void)loadError:(id)arg1;
- (void)loadSuccess:(id)arg1;
- (id)loadOnline;
- (id)tableView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithParamModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

