//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "APSKLaunchpadDelegate.h"

@class NSString, UIViewController;

@interface BEEShareUtil : NSObject <APSKLaunchpadDelegate>
{
    NSString *_title;
    NSString *_desc;
    id _image;
    NSString *_link;
    UIViewController *_controller;
    id _retained_self;
}

+ (void)shareWithTitle:(id)arg1 decs:(id)arg2 image:(id)arg3 link:(id)arg4 toChannels:(id)arg5 fromController:(id)arg6;
@property(retain, nonatomic) id retained_self; // @synthesize retained_self=_retained_self;
@property(retain, nonatomic) UIViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) id image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)sharingLaunchpadDidCancel:(id)arg1;
- (void)shareLink:(id)arg1 image:(id)arg2 extraInfo:(id)arg3 toChannel:(id)arg4;
- (void)shareShortLink:(id)arg1 image:(id)arg2 extraInfo:(id)arg3 toChannel:(id)arg4;
- (void)shareError:(id)arg1;
- (void)sharingLaunchpad:(id)arg1 didSelectChannel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

