//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface BindUserModel : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasMspTid;
    _Bool _hasUserId;
    _Bool _hasPushVersion;
    _Bool _hasAppId;
    _Bool _hasOsType;
    _Bool _hasClientId;
    _Bool _hasAppName;
    _Bool _hasDeviceId;
    _Bool _hasAppVersion;
    _Bool _hasIsPush;
    NSString *_mspTid;
    NSString *_userId;
    NSString *_pushVersion;
    NSString *_appId;
    NSString *_osType;
    NSString *_clientId;
    NSString *_appName;
    NSString *_deviceId;
    NSString *_appVersion;
    NSString *_isPush;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *isPush; // @synthesize isPush=_isPush;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) NSString *osType; // @synthesize osType=_osType;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *pushVersion; // @synthesize pushVersion=_pushVersion;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *mspTid; // @synthesize mspTid=_mspTid;
@property(readonly) _Bool hasIsPush; // @synthesize hasIsPush=_hasIsPush;
@property(readonly) _Bool hasAppVersion; // @synthesize hasAppVersion=_hasAppVersion;
@property(readonly) _Bool hasDeviceId; // @synthesize hasDeviceId=_hasDeviceId;
@property(readonly) _Bool hasAppName; // @synthesize hasAppName=_hasAppName;
@property(readonly) _Bool hasClientId; // @synthesize hasClientId=_hasClientId;
@property(readonly) _Bool hasOsType; // @synthesize hasOsType=_hasOsType;
@property(readonly) _Bool hasAppId; // @synthesize hasAppId=_hasAppId;
@property(readonly) _Bool hasPushVersion; // @synthesize hasPushVersion=_hasPushVersion;
@property(readonly) _Bool hasUserId; // @synthesize hasUserId=_hasUserId;
@property(readonly) _Bool hasMspTid; // @synthesize hasMspTid=_hasMspTid;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

