//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface BisBehavToken : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasToken;
    _Bool _hasType;
    _Bool _hasSampleMode;
    _Bool _hasUid;
    _Bool _hasApdid;
    _Bool _hasAppid;
    _Bool _hasBehid;
    _Bool _hasBizid;
    _Bool _hasVerifyid;
    _Bool _hasVtoken;
    int _type;
    int _sampleMode;
    NSString *_token;
    NSString *_uid;
    NSString *_apdid;
    NSString *_appid;
    NSString *_behid;
    NSString *_bizid;
    NSString *_verifyid;
    NSString *_vtoken;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *vtoken; // @synthesize vtoken=_vtoken;
@property(retain, nonatomic) NSString *verifyid; // @synthesize verifyid=_verifyid;
@property(retain, nonatomic) NSString *bizid; // @synthesize bizid=_bizid;
@property(retain, nonatomic) NSString *behid; // @synthesize behid=_behid;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
@property(retain, nonatomic) NSString *apdid; // @synthesize apdid=_apdid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(nonatomic) int sampleMode; // @synthesize sampleMode=_sampleMode;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(readonly) _Bool hasVtoken; // @synthesize hasVtoken=_hasVtoken;
@property(readonly) _Bool hasVerifyid; // @synthesize hasVerifyid=_hasVerifyid;
@property(readonly) _Bool hasBizid; // @synthesize hasBizid=_hasBizid;
@property(readonly) _Bool hasBehid; // @synthesize hasBehid=_hasBehid;
@property(readonly) _Bool hasAppid; // @synthesize hasAppid=_hasAppid;
@property(readonly) _Bool hasApdid; // @synthesize hasApdid=_hasApdid;
@property(readonly) _Bool hasUid; // @synthesize hasUid=_hasUid;
@property(readonly) _Bool hasSampleMode; // @synthesize hasSampleMode=_hasSampleMode;
@property(readonly) _Bool hasType; // @synthesize hasType=_hasType;
@property(readonly) _Bool hasToken; // @synthesize hasToken=_hasToken;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

