//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface BisHandWritingUploadContent : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasCanvasWidth;
    _Bool _hasCanvasHeight;
    _Bool _hasHwStat;
    int _canvasWidth;
    int _canvasHeight;
    NSMutableArray *_hwSeqList;
    NSString *_hwStat;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *hwStat; // @synthesize hwStat=_hwStat;
@property(retain, nonatomic) NSMutableArray *hwSeqList; // @synthesize hwSeqList=_hwSeqList;
@property(nonatomic) int canvasHeight; // @synthesize canvasHeight=_canvasHeight;
@property(nonatomic) int canvasWidth; // @synthesize canvasWidth=_canvasWidth;
@property(readonly) _Bool hasHwStat; // @synthesize hasHwStat=_hasHwStat;
@property(readonly) _Bool hasCanvasHeight; // @synthesize hasCanvasHeight=_hasCanvasHeight;
@property(readonly) _Bool hasCanvasWidth; // @synthesize hasCanvasWidth=_hasCanvasWidth;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addHwSeqList:(id)arg1;
- (void)setHwSeqListArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

