//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UILabel;

@interface BLLWHeadTitleView : UIView
{
    float _titleOffset;
    UILabel *_titleLabel;
    NSString *_title;
    NSString *_navTitle;
}

@property(nonatomic) float titleOffset; // @synthesize titleOffset=_titleOffset;
@property(retain, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutTitleView;
- (void)setHeadTitle:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

