//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, NSString;

@interface BLSearchDimmingView : UIView
{
    id <BLSearchDimmingViewDelegate> _delegate;
    NSString *_code;
    NSString *_name;
    NSArray *_data;
    NSMutableArray *_dataList;
    UIView *_panelView;
    double _panelHeight;
}

@property(nonatomic) double panelHeight; // @synthesize panelHeight=_panelHeight;
@property(retain, nonatomic) UIView *panelView; // @synthesize panelView=_panelView;
@property(retain, nonatomic) NSMutableArray *dataList; // @synthesize dataList=_dataList;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
@property(nonatomic) __weak id <BLSearchDimmingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clickCategoryButton:(id)arg1;
- (double)createButtons;
- (void)updateCategory:(id)arg1;
- (void)updateData:(id)arg1;
- (void)createSubviews;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 category:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2 category:(id)arg3;

@end

