//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CCContactCountView, UIView;

@interface CCBackupDetailCell : UITableViewCell
{
    CCContactCountView *_localView;
    CCContactCountView *_cloudView;
    UIView *_lineView;
    UIView *_topLine;
    UIView *_bottomLine;
}

@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) CCContactCountView *cloudView; // @synthesize cloudView=_cloudView;
@property(retain, nonatomic) CCContactCountView *localView; // @synthesize localView=_localView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

