//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCSyncBaseBiz.h"

@class NSArray, NSMutableArray, NSObject<OS_dispatch_semaphore>, NSString;

@interface CCBackupBiz : CCSyncBaseBiz
{
    _Bool _isLastPage;
    NSMutableArray *_addContactList;
    NSMutableArray *_editContactList;
    NSMutableArray *_deleteContactList;
    NSMutableArray *_uploadContactList;
    NSArray *_curUploadList;
    unsigned long long _pageSize;
    unsigned long long _amountSize;
    NSString *_versionID;
    unsigned long long _curPageNumber;
    unsigned long long _pagesCount;
    unsigned long long _addCount;
    unsigned long long _modifyCount;
    unsigned long long _deleteCount;
    long long _cloudContactsCount;
    NSObject<OS_dispatch_semaphore> *_semAlert;
}

@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *semAlert; // @synthesize semAlert=_semAlert;
@property(nonatomic) long long cloudContactsCount; // @synthesize cloudContactsCount=_cloudContactsCount;
@property(nonatomic) unsigned long long deleteCount; // @synthesize deleteCount=_deleteCount;
@property(nonatomic) unsigned long long modifyCount; // @synthesize modifyCount=_modifyCount;
@property(nonatomic) unsigned long long addCount; // @synthesize addCount=_addCount;
@property(nonatomic) unsigned long long pagesCount; // @synthesize pagesCount=_pagesCount;
@property(nonatomic) unsigned long long curPageNumber; // @synthesize curPageNumber=_curPageNumber;
@property(nonatomic) _Bool isLastPage; // @synthesize isLastPage=_isLastPage;
@property(retain, nonatomic) NSString *versionID; // @synthesize versionID=_versionID;
@property(nonatomic) unsigned long long amountSize; // @synthesize amountSize=_amountSize;
@property(nonatomic) unsigned long long pageSize; // @synthesize pageSize=_pageSize;
@property(retain, nonatomic) NSArray *curUploadList; // @synthesize curUploadList=_curUploadList;
@property(retain, nonatomic) NSMutableArray *uploadContactList; // @synthesize uploadContactList=_uploadContactList;
@property(retain, nonatomic) NSMutableArray *deleteContactList; // @synthesize deleteContactList=_deleteContactList;
@property(retain, nonatomic) NSMutableArray *editContactList; // @synthesize editContactList=_editContactList;
@property(retain, nonatomic) NSMutableArray *addContactList; // @synthesize addContactList=_addContactList;
- (void).cxx_destruct;
- (void)dealloc;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)updateCache;
- (void)updateContacts:(id)arg1 WithSidArray:(id)arg2;
- (_Bool)sendRequest;
- (void)diffWithCache;
- (void)taskDone;
- (void)doTask;
- (void)printLog;
- (void)reset;
- (id)init;

@end

