//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCSyncBaseBiz.h"

@class NSMutableArray;

@interface CCRestoreBiz : CCSyncBaseBiz
{
    _Bool _isLastPage;
    int _recoverPageSize;
    int _serverStoreCount;
    NSMutableArray *_contactCloudList;
    NSMutableArray *_addContactList;
    NSMutableArray *_editContactList;
    NSMutableArray *_deleteContactList;
    NSMutableArray *_notifyServerList;
    long long _addContactCount;
    long long _editContactCount;
    long long _deleteContactCount;
    long long _curRequestPage;
}

@property(nonatomic) _Bool isLastPage; // @synthesize isLastPage=_isLastPage;
@property(nonatomic) long long curRequestPage; // @synthesize curRequestPage=_curRequestPage;
@property(nonatomic) long long deleteContactCount; // @synthesize deleteContactCount=_deleteContactCount;
@property(nonatomic) long long editContactCount; // @synthesize editContactCount=_editContactCount;
@property(nonatomic) long long addContactCount; // @synthesize addContactCount=_addContactCount;
@property(retain, nonatomic) NSMutableArray *notifyServerList; // @synthesize notifyServerList=_notifyServerList;
@property(retain, nonatomic) NSMutableArray *deleteContactList; // @synthesize deleteContactList=_deleteContactList;
@property(retain, nonatomic) NSMutableArray *editContactList; // @synthesize editContactList=_editContactList;
@property(retain, nonatomic) NSMutableArray *addContactList; // @synthesize addContactList=_addContactList;
@property(retain, nonatomic) NSMutableArray *contactCloudList; // @synthesize contactCloudList=_contactCloudList;
@property(nonatomic) int serverStoreCount; // @synthesize serverStoreCount=_serverStoreCount;
@property(nonatomic) int recoverPageSize; // @synthesize recoverPageSize=_recoverPageSize;
- (void).cxx_destruct;
- (void)dealloc;
- (void)updateCache;
- (_Bool)updateLocal;
- (_Bool)sendRequest;
- (void)diffWithLocal;
- (id)findTheSamePerson:(id)arg1 inLocal:(id)arg2;
- (void)taskDone;
- (void)doTask;
- (int)recoverRequestTimes;
- (void)printLog;
- (void)reset;
- (id)init;

@end

