//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APCustomStorage;

@interface CloudContactRelationDataCache : NSObject
{
    id <CloudContactRelationDataCacheProtocol> _cloudContactRelationDataCacheProxy;
    APCustomStorage *_storage;
}

@property(retain, nonatomic) APCustomStorage *storage; // @synthesize storage=_storage;
- (void).cxx_destruct;
- (id)clearAllItems;
- (id)queryAllItems;
- (id)insertItemList:(id)arg1;
- (id)init;

@end

