//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"
#import "NSCoding.h"

@class NSString;

@interface CommunityMember : APPBGeneratedMessage <NSCoding, GeneratedMessageProtocol>
{
    _Bool _hasUserId;
    _Bool _hasShowName;
    _Bool _hasHaedImgUrl;
    _Bool _hasRole;
    _Bool _hasLoginId;
    NSString *_userId;
    NSString *_showName;
    NSString *_haedImgUrl;
    NSString *_role;
    NSString *_loginId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *loginId; // @synthesize loginId=_loginId;
@property(retain, nonatomic) NSString *role; // @synthesize role=_role;
@property(retain, nonatomic) NSString *haedImgUrl; // @synthesize haedImgUrl=_haedImgUrl;
@property(retain, nonatomic) NSString *showName; // @synthesize showName=_showName;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(readonly) _Bool hasLoginId; // @synthesize hasLoginId=_hasLoginId;
@property(readonly) _Bool hasRole; // @synthesize hasRole=_hasRole;
@property(readonly) _Bool hasHaedImgUrl; // @synthesize hasHaedImgUrl=_hasHaedImgUrl;
@property(readonly) _Bool hasShowName; // @synthesize hasShowName=_hasShowName;
@property(readonly) _Bool hasUserId; // @synthesize hasUserId=_hasUserId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

