//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface DisGroupBatchQueryResult : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasSuccess;
    _Bool _hasResultCode;
    _Bool _hasResultDesc;
    _Bool _hasRetry;
    _Bool _hasSyncMaxOpId;
    _Bool _success;
    _Bool _retry;
    int _resultCode;
    NSMutableArray *_groups;
    NSString *_resultDesc;
    NSMutableArray *_failGroupIds;
    NSString *_syncMaxOpId;
    NSMutableArray *_reasons;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *reasons; // @synthesize reasons=_reasons;
@property(retain, nonatomic) NSString *syncMaxOpId; // @synthesize syncMaxOpId=_syncMaxOpId;
@property(nonatomic) _Bool retry; // @synthesize retry=_retry;
@property(retain, nonatomic) NSMutableArray *failGroupIds; // @synthesize failGroupIds=_failGroupIds;
@property(retain, nonatomic) NSString *resultDesc; // @synthesize resultDesc=_resultDesc;
@property(nonatomic) int resultCode; // @synthesize resultCode=_resultCode;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(retain, nonatomic) NSMutableArray *groups; // @synthesize groups=_groups;
@property(readonly) _Bool hasSyncMaxOpId; // @synthesize hasSyncMaxOpId=_hasSyncMaxOpId;
@property(readonly) _Bool hasRetry; // @synthesize hasRetry=_hasRetry;
@property(readonly) _Bool hasResultDesc; // @synthesize hasResultDesc=_hasResultDesc;
@property(readonly) _Bool hasResultCode; // @synthesize hasResultCode=_hasResultCode;
@property(readonly) _Bool hasSuccess; // @synthesize hasSuccess=_hasSuccess;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addReasons:(id)arg1;
- (void)setReasonsArray:(id)arg1;
- (void)addFailGroupIds:(id)arg1;
- (void)setFailGroupIdsArray:(id)arg1;
- (void)addGroups:(id)arg1;
- (void)setGroupsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

