//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface DjangoTransaction : NSObject
{
    int _status;
    int _type;
    unsigned long long _chunkNumber;
    unsigned long long _createTime;
    unsigned long long _size;
    NSString *_djangoId;
    NSString *_gcid;
    NSDictionary *_ext;
    NSString *_md5;
    NSString *_code;
    NSString *_name;
    NSString *_appKey;
}

+ (id)createWithDictionary:(id)arg1;
@property(copy, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(copy, nonatomic) NSDictionary *ext; // @synthesize ext=_ext;
@property(copy, nonatomic) NSString *gcid; // @synthesize gcid=_gcid;
@property(copy, nonatomic) NSString *djangoId; // @synthesize djangoId=_djangoId;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) unsigned long long createTime; // @synthesize createTime=_createTime;
@property(nonatomic) unsigned long long chunkNumber; // @synthesize chunkNumber=_chunkNumber;
- (void).cxx_destruct;

@end

