//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface DynamicItemView : UIView
{
    UIImageView *_logoView;
    UILabel *_labelView;
}

@property(retain, nonatomic) UILabel *labelView; // @synthesize labelView=_labelView;
@property(retain, nonatomic) UIImageView *logoView; // @synthesize logoView=_logoView;
- (void).cxx_destruct;
- (void)setContentLogo:(id)arg1 defaultImage:(id)arg2 text:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

