//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface DynamicResourceItem : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasResId;
    _Bool _hasResVersion;
    _Bool _hasResType;
    _Bool _hasFileMd5;
    _Bool _hasFileUrl;
    _Bool _hasFileContent;
    _Bool _hasResStatus;
    _Bool _hasIssueDesc;
    _Bool _hasLazyLoad;
    int _resStatus;
    int _lazyLoad;
    int _quickRun;
    NSString *_resId;
    NSString *_resVersion;
    NSString *_resType;
    NSString *_fileMd5;
    NSString *_fileUrl;
    NSString *_fileContent;
    NSMutableArray *_resExtraData;
    NSString *_issueDesc;
    NSString *_frameworkId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic) int quickRun; // @synthesize quickRun=_quickRun;
@property(retain, nonatomic) NSString *frameworkId; // @synthesize frameworkId=_frameworkId;
@property(nonatomic) int lazyLoad; // @synthesize lazyLoad=_lazyLoad;
@property(retain, nonatomic) NSString *issueDesc; // @synthesize issueDesc=_issueDesc;
@property(retain, nonatomic) NSMutableArray *resExtraData; // @synthesize resExtraData=_resExtraData;
@property(nonatomic) int resStatus; // @synthesize resStatus=_resStatus;
@property(retain, nonatomic) NSString *fileContent; // @synthesize fileContent=_fileContent;
@property(retain, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(retain, nonatomic) NSString *fileMd5; // @synthesize fileMd5=_fileMd5;
@property(retain, nonatomic) NSString *resType; // @synthesize resType=_resType;
@property(retain, nonatomic) NSString *resVersion; // @synthesize resVersion=_resVersion;
@property(retain, nonatomic) NSString *resId; // @synthesize resId=_resId;
@property(readonly) _Bool hasLazyLoad; // @synthesize hasLazyLoad=_hasLazyLoad;
@property(readonly) _Bool hasIssueDesc; // @synthesize hasIssueDesc=_hasIssueDesc;
@property(readonly) _Bool hasResStatus; // @synthesize hasResStatus=_hasResStatus;
@property(readonly) _Bool hasFileContent; // @synthesize hasFileContent=_hasFileContent;
@property(readonly) _Bool hasFileUrl; // @synthesize hasFileUrl=_hasFileUrl;
@property(readonly) _Bool hasFileMd5; // @synthesize hasFileMd5=_hasFileMd5;
@property(readonly) _Bool hasResType; // @synthesize hasResType=_hasResType;
@property(readonly) _Bool hasResVersion; // @synthesize hasResVersion=_hasResVersion;
@property(readonly) _Bool hasResId; // @synthesize hasResId=_hasResId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addResExtraData:(id)arg1;
- (void)setResExtraDataArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

