//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ERTServiceObject.h"

@class NSDate;

@interface ERTCacheObject : ERTServiceObject
{
    id _cacheValue;
    NSDate *_expireDate;
    NSDate *_cachedDate;
}

+ (id)wrapperWithValue:(id)arg1 withExpires:(id)arg2;
@property(retain, nonatomic) NSDate *cachedDate; // @synthesize cachedDate=_cachedDate;
@property(retain, nonatomic) NSDate *expireDate; // @synthesize expireDate=_expireDate;
@property(retain, nonatomic) id cacheValue; // @synthesize cacheValue=_cacheValue;
- (void).cxx_destruct;

@end

