//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPVolumeView.h"

@class UISlider;

@interface EVVolumeWithoutHUDView : MPVolumeView
{
    _Bool _observingSliderFrame;
    _Bool _sliderReady;
    float _volume;
    UISlider *_slider;
}

@property(nonatomic, getter=isSliderReady) _Bool sliderReady; // @synthesize sliderReady=_sliderReady;
@property(nonatomic, getter=isObservingSliderFrame) _Bool observingSliderFrame; // @synthesize observingSliderFrame=_observingSliderFrame;
@property(nonatomic) float volume; // @synthesize volume=_volume;
@property(readonly, nonatomic) __weak UISlider *slider; // @synthesize slider=_slider;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)didAddSubview:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

