//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MOPItemCategory, UIColor, UIFont, UILabel;

@interface EWListMenuItem : UIView
{
    float _padding;
    id <EWTabMenuItemDelegate> _delegate;
    UILabel *_label;
    MOPItemCategory *_category;
    UIColor *_color;
    UIFont *_font;
}

@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(retain, nonatomic) MOPItemCategory *category; // @synthesize category=_category;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) float padding; // @synthesize padding=_padding;
@property(nonatomic) __weak id <EWTabMenuItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)inactive;
- (void)active;
- (void)tapHandle:(id)arg1;
- (void)bindEvent;
- (void)createViews;
- (id)initWithCategory:(id)arg1 padding:(unsigned long long)arg2 color:(id)arg3 tintColor:(id)arg4 font:(id)arg5;

@end

