//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface ExclusiveInfoDTO : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasItemId;
    _Bool _hasPartnerId;
    _Bool _hasPassName;
    _Bool _hasShopName;
    _Bool _hasDistance;
    _Bool _hasUrl;
    NSString *_itemId;
    NSString *_partnerId;
    NSString *_passName;
    NSString *_shopName;
    NSString *_distance;
    NSString *_url;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *shopName; // @synthesize shopName=_shopName;
@property(retain, nonatomic) NSString *passName; // @synthesize passName=_passName;
@property(retain, nonatomic) NSString *partnerId; // @synthesize partnerId=_partnerId;
@property(retain, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(readonly) _Bool hasUrl; // @synthesize hasUrl=_hasUrl;
@property(readonly) _Bool hasDistance; // @synthesize hasDistance=_hasDistance;
@property(readonly) _Bool hasShopName; // @synthesize hasShopName=_hasShopName;
@property(readonly) _Bool hasPassName; // @synthesize hasPassName=_hasPassName;
@property(readonly) _Bool hasPartnerId; // @synthesize hasPartnerId=_hasPartnerId;
@property(readonly) _Bool hasItemId; // @synthesize hasItemId=_hasItemId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

