//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol EyePrintDelegate <NSObject>
- (void)stepCompleted;
- (void)onStepFinished:(int)arg1 withCaptured:(struct eyeverify_capture_t *)arg2;
- (void)onDistanceChanged:(double)arg1;
- (void)onEyeStatusChanged:(long long)arg1;
- (void)onLightStatusChanged:(long long)arg1 brightness:(double)arg2;
@end

