//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FalconCardManagerViewControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class APBRPCManager, APToastView, BisClientConfigContent, FalconCardManagerViewController, NSDictionary, NSMutableDictionary, NSString, UIImagePickerController, UIView, UIViewController;

@interface FalconCardManager : NSObject <FalconCardManagerViewControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    UIViewController *rootViewController;
    UIView *vc;
    APToastView *waittoast;
    double timebegin1;
    FalconCardManagerViewController *cardview;
    NSString *bisToken;
    NSString *behid;
    NSDictionary *bizInfo;
    BisClientConfigContent *protocol;
    CDUnknownBlockType authCallback;
    NSString *RequestPage;
    NSString *RequestToken;
    NSString *certCode;
    NSString *RequestTotalPagesNum;
    NSString *RequestModel;
    NSString *tokenID;
    NSMutableDictionary *dictionryRst;
    long long processN;
    UIImagePickerController *picker;
    NSString *RequestCardType;
    NSString *businessID;
    _Bool _isBusy;
    id <FalconCardManagerDelegate> _delegatecm;
    APBRPCManager *_rpcManager;
}

+ (id)getMetaInfo;
@property(nonatomic) _Bool isBusy; // @synthesize isBusy=_isBusy;
@property(retain, nonatomic) APBRPCManager *rpcManager; // @synthesize rpcManager=_rpcManager;
@property(nonatomic) __weak id <FalconCardManagerDelegate> delegatecm; // @synthesize delegatecm=_delegatecm;
- (void).cxx_destruct;
- (void)dealloc;
- (void)exec:(id)arg1 withCompletionCallback:(CDUnknownBlockType)arg2;
- (void)uploadTask:(id)arg1;
- (id)buildRequest:(id)arg1;
- (id)getBehavLog;
- (void)startCardManager:(id)arg1;
- (void)authWithRequest:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)setDrmJson:(id)arg1;
- (void)setRootViewController:(id)arg1;
- (void)FalconCardManagerVC:(id)arg1 resultDict:(id)arg2;
- (id)convertToJSONData:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (id)scaleImg:(id)arg1 toScale:(float)arg2;
- (id)GetTokenWithDate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

