//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FavBaseCellView.h"

@class FavCloudIdImageView, FavKBRateView, NSString, UILabel;

@interface FavKBCellView : FavBaseCellView
{
    FavCloudIdImageView *_shopImageView;
    UILabel *_titleLabel;
    FavKBRateView *_rateView;
    UILabel *_priceLabel;
    UILabel *_tagsLabel;
    double _rateValue;
    NSString *_currentCloudId;
}

+ (double)cellHeight:(id)arg1;
@property(copy, nonatomic) NSString *currentCloudId; // @synthesize currentCloudId=_currentCloudId;
@property(nonatomic) double rateValue; // @synthesize rateValue=_rateValue;
@property(retain, nonatomic) UILabel *tagsLabel; // @synthesize tagsLabel=_tagsLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) FavKBRateView *rateView; // @synthesize rateView=_rateView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) FavCloudIdImageView *shopImageView; // @synthesize shopImageView=_shopImageView;
- (void).cxx_destruct;
- (void)buildCell:(id)arg1;
- (void)layoutSubviews;
- (void)buildSubView;
- (void)updateConstraints;
- (void)buildConstraint;

@end

