//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FaceDetectAgentDelegate.h"
#import "FaceDetectServiceDelegate.h"

@class AFDAudio, FDFaceInfo, FaceDetectService, NSDate, NSString;

@interface FDAlipayCollect : NSObject <FaceDetectAgentDelegate, FaceDetectServiceDelegate>
{
    int _logCountOfCapturePhase;
    int _logCountOfLDPhase;
    float _hqFrameCompressRatio;
    float _faceFrameCompressRatio;
    float _actionFrameCompressRatio;
    int _vTokenCode;
    FaceDetectService *_faceDetectService;
    NSDate *_lastLogTime;
    FDFaceInfo *_hqFrame;
    AFDAudio *_audioPlayer;
}

+ (id)stringFromActionType:(int)arg1;
+ (int)getDetectionType;
@property(retain, nonatomic) AFDAudio *audioPlayer; // @synthesize audioPlayer=_audioPlayer;
@property(nonatomic) int vTokenCode; // @synthesize vTokenCode=_vTokenCode;
@property(nonatomic) float actionFrameCompressRatio; // @synthesize actionFrameCompressRatio=_actionFrameCompressRatio;
@property(nonatomic) float faceFrameCompressRatio; // @synthesize faceFrameCompressRatio=_faceFrameCompressRatio;
@property(nonatomic) float hqFrameCompressRatio; // @synthesize hqFrameCompressRatio=_hqFrameCompressRatio;
@property(retain, nonatomic) FDFaceInfo *hqFrame; // @synthesize hqFrame=_hqFrame;
@property(retain, nonatomic) NSDate *lastLogTime; // @synthesize lastLogTime=_lastLogTime;
@property(nonatomic) int logCountOfLDPhase; // @synthesize logCountOfLDPhase=_logCountOfLDPhase;
@property(nonatomic) int logCountOfCapturePhase; // @synthesize logCountOfCapturePhase=_logCountOfCapturePhase;
@property(retain, nonatomic) FaceDetectService *faceDetectService; // @synthesize faceDetectService=_faceDetectService;
- (void).cxx_destruct;
- (void)upLoadMonitorDataWithContext:(id)arg1;
- (void)addMonitorPicPerFrame:(id)arg1 withContext:(id)arg2;
- (id)faceProperty:(id)arg1;
- (void)addRemoteLogPerFrame:(id)arg1 withContext:(id)arg2;
- (void)saveFaceInfoEx:(id)arg1 andActionInfo:(id)arg2;
- (void)onFrameDetected:(id)arg1 andTimeout:(float)arg2;
- (int)onDetectionSuccess:(id)arg1;
- (id)getQualityFrame:(id)arg1;
- (void)onDetectionFailed:(int)arg1;
- (_Bool)checkPhotoQuality;
- (void)updateBehModelWithContext:(id)arg1;
- (void)managePhase;
- (void)manageFinished;
- (void)manageActionEnd;
- (void)manageActionBegin;
- (void)manageCaptureFaceEnd;
- (void)manageCaptureFaceBegin;
- (void)manageInitFace;
- (void)showPhase;
- (void)initRmoteLogContext;
- (void)getModelLogInfo;
- (void)detectWithBuffer:(struct opaqueCMSampleBuffer *)arg1 orientation:(long long)arg2;
- (void)restartDetect;
- (void)startDetect;
- (void)closeDetect;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

