//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MGLivenessDetectionFrame;

@protocol FDViewDelegate <NSObject>
- (void)onVolumeNotify:(float)arg1;
- (void)onGoBack;
- (void)onShowProgressView;
- (void)onRestartDetect;
- (void)onApplicationDidBecomeActive;
- (void)onApplicationWillResignActive;
- (void)showEnvironmentView:(MGLivenessDetectionFrame *)arg1;
- (void)playPhaseSound;
- (void)showPhaseView;
@end

