//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface FetchGroupCardReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasGroupId;
    _Bool _hasExt;
    _Bool _hasLastFeedId;
    NSString *_groupId;
    NSString *_ext;
    NSString *_lastFeedId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *lastFeedId; // @synthesize lastFeedId=_lastFeedId;
@property(retain, nonatomic) NSString *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(readonly) _Bool hasLastFeedId; // @synthesize hasLastFeedId=_hasLastFeedId;
@property(readonly) _Bool hasExt; // @synthesize hasExt=_hasExt;
@property(readonly) _Bool hasGroupId; // @synthesize hasGroupId=_hasGroupId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

