//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface FriendOfFriendResult : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasSuccess;
    _Bool _hasResultCode;
    _Bool _hasResultDesc;
    _Bool _hasLocalCalculateMutualFriend;
    _Bool _hasIndex;
    _Bool _success;
    _Bool _localCalculateMutualFriend;
    int _resultCode;
    NSMutableArray *_mutualFriends;
    NSMutableArray *_allFriends;
    NSString *_resultDesc;
    NSString *_index;
    NSMutableArray *_firstPageIds;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *firstPageIds; // @synthesize firstPageIds=_firstPageIds;
@property(retain, nonatomic) NSString *index; // @synthesize index=_index;
@property(nonatomic) _Bool localCalculateMutualFriend; // @synthesize localCalculateMutualFriend=_localCalculateMutualFriend;
@property(retain, nonatomic) NSString *resultDesc; // @synthesize resultDesc=_resultDesc;
@property(nonatomic) int resultCode; // @synthesize resultCode=_resultCode;
@property(nonatomic) _Bool success; // @synthesize success=_success;
@property(retain, nonatomic) NSMutableArray *allFriends; // @synthesize allFriends=_allFriends;
@property(retain, nonatomic) NSMutableArray *mutualFriends; // @synthesize mutualFriends=_mutualFriends;
@property(readonly) _Bool hasIndex; // @synthesize hasIndex=_hasIndex;
@property(readonly) _Bool hasLocalCalculateMutualFriend; // @synthesize hasLocalCalculateMutualFriend=_hasLocalCalculateMutualFriend;
@property(readonly) _Bool hasResultDesc; // @synthesize hasResultDesc=_hasResultDesc;
@property(readonly) _Bool hasResultCode; // @synthesize hasResultCode=_hasResultCode;
@property(readonly) _Bool hasSuccess; // @synthesize hasSuccess=_hasSuccess;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addFirstPageIds:(id)arg1;
- (void)setFirstPageIdsArray:(id)arg1;
- (void)addAllFriends:(id)arg1;
- (void)setAllFriendsArray:(id)arg1;
- (void)addMutualFriends:(id)arg1;
- (void)setMutualFriendsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

