//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface FundApplyTransferOutReqPB : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasFundCode;
    _Bool _hasTransferType;
    NSString *_fundCode;
    NSString *_transferType;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *transferType; // @synthesize transferType=_transferType;
@property(retain, nonatomic) NSString *fundCode; // @synthesize fundCode=_fundCode;
@property(readonly) _Bool hasTransferType; // @synthesize hasTransferType=_hasTransferType;
@property(readonly) _Bool hasFundCode; // @synthesize hasFundCode=_hasFundCode;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

