//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class APButton;

@interface GifSearchNetErrorView : UIView
{
    APButton *_tipsLabelButton;
}

@property(retain, nonatomic) APButton *tipsLabelButton; // @synthesize tipsLabelButton=_tipsLabelButton;
- (void).cxx_destruct;
- (void)commonInit;
- (id)tipsLabel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

