//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIScrollViewDelegate.h"

@class GifSearchNetErrorView, GifSearchNoResultView, NSArray, NSString, UICollectionView;

@interface GifSearchResultView : UIView <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate>
{
    _Bool _doesHideMoreCell;
    UICollectionView *_gifCollectionView;
    GifSearchNoResultView *_noResultView;
    GifSearchNetErrorView *_netErrorView;
    id <GifSearchResultDelegate> _delegate;
    NSArray *_gifDataSource;
}

@property(nonatomic) _Bool doesHideMoreCell; // @synthesize doesHideMoreCell=_doesHideMoreCell;
@property(retain, nonatomic) NSArray *gifDataSource; // @synthesize gifDataSource=_gifDataSource;
@property(nonatomic) __weak id <GifSearchResultDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GifSearchNetErrorView *netErrorView; // @synthesize netErrorView=_netErrorView;
@property(retain, nonatomic) GifSearchNoResultView *noResultView; // @synthesize noResultView=_noResultView;
@property(retain, nonatomic) UICollectionView *gifCollectionView; // @synthesize gifCollectionView=_gifCollectionView;
- (void).cxx_destruct;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)noResultMoreBtnClick:(id)arg1;
- (void)netErrorRetryButtonClick:(id)arg1;
- (void)showNetErrorView;
- (void)showNoResultView;
- (void)showSearchResultView:(id)arg1;
- (void)reloadData;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

