//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface giftprodActVo : NSObject
{
    NSArray *_addresses;
    NSString *_eventId;
    NSString *_picModel;
    NSString *_md5String;
    NSString *_tag;
}

+ (Class)addressesElementClass;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *md5String; // @synthesize md5String=_md5String;
@property(retain, nonatomic) NSString *picModel; // @synthesize picModel=_picModel;
@property(retain, nonatomic) NSString *eventId; // @synthesize eventId=_eventId;
@property(retain, nonatomic) NSArray *addresses; // @synthesize addresses=_addresses;
- (void).cxx_destruct;

@end

