//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class EmotionShowView, GifSearchResultItem;

@interface GifViewCollectionCell : UICollectionViewCell
{
    _Bool _isDownloadSuccess;
    EmotionShowView *_emotionView;
    GifSearchResultItem *_gifInfo;
}

+ (id)reuseIdentifier;
@property(nonatomic) _Bool isDownloadSuccess; // @synthesize isDownloadSuccess=_isDownloadSuccess;
@property(retain, nonatomic) GifSearchResultItem *gifInfo; // @synthesize gifInfo=_gifInfo;
@property(retain, nonatomic) EmotionShowView *emotionView; // @synthesize emotionView=_emotionView;
- (void).cxx_destruct;
- (void)initemotionView;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

