//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, UIImage, UIImageView, UILabel;

@interface GO2OShopHeaderView : UIControl
{
    NSString *_imageUrlString;
    long long _imageNumber;
    UIImage *_logoImage;
    UIImageView *_imageLogoView;
    UILabel *_imageNumberLabel;
    UIImageView *_backgroundImageView;
}

@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UILabel *imageNumberLabel; // @synthesize imageNumberLabel=_imageNumberLabel;
@property(retain, nonatomic) UIImageView *imageLogoView; // @synthesize imageLogoView=_imageLogoView;
@property(retain, nonatomic) UIImage *logoImage; // @synthesize logoImage=_logoImage;
@property(nonatomic) long long imageNumber; // @synthesize imageNumber=_imageNumber;
@property(retain, nonatomic) NSString *imageUrlString; // @synthesize imageUrlString=_imageUrlString;
- (void).cxx_destruct;
- (void)stretch:(double)arg1;
- (void)initView;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

