//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GO2OServiceObject.h"

@class NSString;

@interface GO2OShopDetailRequest : GO2OServiceObject
{
    NSString *_shopId;
    NSString *_recommendId;
}

@property(retain, nonatomic) NSString *recommendId; // @synthesize recommendId=_recommendId;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
- (void).cxx_destruct;

@end

