//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GO2OTableViewCell.h"

@class GO2OShopBriefExpandView, GO2OShopInfo, O2OStarView, UILabel, UIView;

@interface GO2OShopBriefTableViewCell : GO2OTableViewCell
{
    GO2OShopInfo *_shopInfo;
    GO2OShopBriefExpandView *_briefView;
    UILabel *_shopNameLabel;
    O2OStarView *_starView;
    UIView *_starContainerView;
    UILabel *_specailLabel;
    UILabel *_priceLabel;
}

@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *specailLabel; // @synthesize specailLabel=_specailLabel;
@property(retain, nonatomic) UIView *starContainerView; // @synthesize starContainerView=_starContainerView;
@property(retain, nonatomic) O2OStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *shopNameLabel; // @synthesize shopNameLabel=_shopNameLabel;
@property(retain, nonatomic) GO2OShopBriefExpandView *briefView; // @synthesize briefView=_briefView;
@property(retain, nonatomic) GO2OShopInfo *shopInfo; // @synthesize shopInfo=_shopInfo;
- (void).cxx_destruct;
- (void)addExpandDescriptionViewTarget:(id)arg1 selector:(SEL)arg2;
- (void)initCell;
- (double)heightOfTitle;
- (id)specialString:(id)arg1;
- (void)configureCellWithShopInfo:(id)arg1 expanded:(_Bool)arg2;

@end

