//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface H5AutoLogger : NSObject
{
}

+ (long long)findSeedNumberWithSeedStr:(id)arg1;
+ (id)encodeURI:(id)arg1;
+ (void)getAppId:(id *)arg1 publicId:(id *)arg2 openAppId:(id *)arg3 shopId:(id *)arg4 customParams:(id *)arg5 version:(id *)arg6 sourceId:(id *)arg7 bizScenario:(id *)arg8;
+ (_Bool)isMatchString:(id)arg1 byRrange:(id)arg2;
+ (_Bool)isAllowLogByRange:(id)arg1 appId:(id)arg2 publicId:(id)arg3 url:(id)arg4;
+ (void)logWithOptions:(id)arg1;
+ (id)getLogConfigByLid:(long long)arg1;
+ (id)getLogSwitchByLid:(long long)arg1;

@end

