//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, UIDatePicker, UIView;

@interface H5DatePicker : NSObject
{
    UIView *_superView;
    _Bool _isIDCard;
    NSString *_target;
    UIView *_dateView;
    UIDatePicker *_datePicker;
    CDUnknownBlockType _clickCallback;
    long long _mode;
    NSDate *_minDate;
    NSDate *_maxDate;
    long long _minuteInterval;
    NSDate *_beginDate;
    NSString *_format;
}

@property(retain, nonatomic) NSString *format; // @synthesize format=_format;
@property(nonatomic) _Bool isIDCard; // @synthesize isIDCard=_isIDCard;
@property(retain, nonatomic) NSDate *beginDate; // @synthesize beginDate=_beginDate;
@property(nonatomic) long long minuteInterval; // @synthesize minuteInterval=_minuteInterval;
@property(retain, nonatomic) NSDate *maxDate; // @synthesize maxDate=_maxDate;
@property(retain, nonatomic) NSDate *minDate; // @synthesize minDate=_minDate;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(copy, nonatomic) CDUnknownBlockType clickCallback; // @synthesize clickCallback=_clickCallback;
@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain, nonatomic) UIView *dateView; // @synthesize dateView=_dateView;
@property(retain, nonatomic) NSString *target; // @synthesize target=_target;
- (void).cxx_destruct;
- (void)compelteDatePicker;
- (void)hideDatePicker;
- (void)cancelDatePicker;
- (void)destroy;
- (void)longPeriodTap;
- (void)showDatePickerInview:(id)arg1 clickOkButtonBlock:(CDUnknownBlockType)arg2;
- (id)stringFromDate:(id)arg1;
- (id)dateFromString:(id)arg1;
- (id)initWithParams:(id)arg1;

@end

