//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NBOptions.h"

@class NSNumber, NSString;

@interface H5Options : NBOptions
{
    _Bool _ssoLoginEnabled;
    _Bool _offlineH5SsoLoginFirst;
    _Bool _closeAfterPayFinish;
    _Bool _proxy;
    _Bool _prefetchLocation;
    _Bool _smartToolBar;
    _Bool _isSsoLoginProMode;
    _Bool _showFavorites;
    _Bool _showReportBtn;
    _Bool _interceptJump;
    _Bool _transparent;
    _Bool _networkIndicator;
    _Bool _preSSOLogin;
    _Bool _preSSOLoginBindingPage;
    _Bool _hasBgColor;
    _Bool _originReadTitle;
    int _titleBarColor;
    int _bounceTopColor;
    int _bounceBottomColor;
    int _backBtnTextColor;
    int _titleColor;
    NSString *_safePayContext;
    NSString *_webAppId;
    NSString *_appId;
    NSString *_publicId;
    double _paddingBottom;
    double _waitRender;
    NSString *_shareChannels;
    NSString *_transparentTitle;
    double _scrollDistance;
    NSString *_preSSOLoginUrl;
    NSString *_navSeachBar_type;
    NSString *_navSeachBar_placeholder;
    NSString *_navSeachBar_value;
    NSString *_navSeachBar_editType;
    NSNumber *_navSeachBar_maxLength;
    NSNumber *_navSeachBar_showVoiceBtn;
    NSString *_backBtnImage;
    NSString *_originDefaultTitle;
}

@property(nonatomic) _Bool originReadTitle; // @synthesize originReadTitle=_originReadTitle;
@property(copy, nonatomic) NSString *originDefaultTitle; // @synthesize originDefaultTitle=_originDefaultTitle;
@property(nonatomic) _Bool hasBgColor; // @synthesize hasBgColor=_hasBgColor;
@property(nonatomic) int titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) int backBtnTextColor; // @synthesize backBtnTextColor=_backBtnTextColor;
@property(copy, nonatomic) NSString *backBtnImage; // @synthesize backBtnImage=_backBtnImage;
@property(retain, nonatomic) NSNumber *navSeachBar_showVoiceBtn; // @synthesize navSeachBar_showVoiceBtn=_navSeachBar_showVoiceBtn;
@property(retain, nonatomic) NSNumber *navSeachBar_maxLength; // @synthesize navSeachBar_maxLength=_navSeachBar_maxLength;
@property(retain, nonatomic) NSString *navSeachBar_editType; // @synthesize navSeachBar_editType=_navSeachBar_editType;
@property(retain, nonatomic) NSString *navSeachBar_value; // @synthesize navSeachBar_value=_navSeachBar_value;
@property(retain, nonatomic) NSString *navSeachBar_placeholder; // @synthesize navSeachBar_placeholder=_navSeachBar_placeholder;
@property(retain, nonatomic) NSString *navSeachBar_type; // @synthesize navSeachBar_type=_navSeachBar_type;
@property(copy, nonatomic) NSString *preSSOLoginUrl; // @synthesize preSSOLoginUrl=_preSSOLoginUrl;
@property(nonatomic) _Bool preSSOLoginBindingPage; // @synthesize preSSOLoginBindingPage=_preSSOLoginBindingPage;
@property(nonatomic) _Bool preSSOLogin; // @synthesize preSSOLogin=_preSSOLogin;
@property(nonatomic) int bounceBottomColor; // @synthesize bounceBottomColor=_bounceBottomColor;
@property(nonatomic) int bounceTopColor; // @synthesize bounceTopColor=_bounceTopColor;
@property(nonatomic) double scrollDistance; // @synthesize scrollDistance=_scrollDistance;
@property(nonatomic) int titleBarColor; // @synthesize titleBarColor=_titleBarColor;
@property(copy, nonatomic) NSString *transparentTitle; // @synthesize transparentTitle=_transparentTitle;
@property(nonatomic) _Bool networkIndicator; // @synthesize networkIndicator=_networkIndicator;
@property(nonatomic) _Bool transparent; // @synthesize transparent=_transparent;
@property(nonatomic) _Bool interceptJump; // @synthesize interceptJump=_interceptJump;
@property(nonatomic) _Bool showReportBtn; // @synthesize showReportBtn=_showReportBtn;
@property(nonatomic) _Bool showFavorites; // @synthesize showFavorites=_showFavorites;
@property(nonatomic) _Bool isSsoLoginProMode; // @synthesize isSsoLoginProMode=_isSsoLoginProMode;
@property(copy, nonatomic) NSString *shareChannels; // @synthesize shareChannels=_shareChannels;
@property(nonatomic) double waitRender; // @synthesize waitRender=_waitRender;
@property(nonatomic) double paddingBottom; // @synthesize paddingBottom=_paddingBottom;
@property(nonatomic) _Bool smartToolBar; // @synthesize smartToolBar=_smartToolBar;
@property(nonatomic) _Bool prefetchLocation; // @synthesize prefetchLocation=_prefetchLocation;
@property(nonatomic) _Bool proxy; // @synthesize proxy=_proxy;
@property(copy, nonatomic) NSString *publicId; // @synthesize publicId=_publicId;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(nonatomic) _Bool closeAfterPayFinish; // @synthesize closeAfterPayFinish=_closeAfterPayFinish;
@property(copy, nonatomic) NSString *webAppId; // @synthesize webAppId=_webAppId;
@property(copy, nonatomic) NSString *safePayContext; // @synthesize safePayContext=_safePayContext;
@property(nonatomic) _Bool offlineH5SsoLoginFirst; // @synthesize offlineH5SsoLoginFirst=_offlineH5SsoLoginFirst;
@property(nonatomic) _Bool ssoLoginEnabled; // @synthesize ssoLoginEnabled=_ssoLoginEnabled;
- (void).cxx_destruct;
- (id)normalize:(id)arg1;
- (void)changeTitleImage:(id)arg1 override:(_Bool)arg2;
- (void)mergeWithDictionary:(id)arg1;
- (id)initWithOptions:(id)arg1 overrides:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

