//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NBContentViewPageProfile.h"

@class H5PerformanceTiming, NSDate, NSMutableString, NSString;

@interface H5PagePerformance : NBContentViewPageProfile
{
    _Bool _isReport;
    _Bool _isWK;
    _Bool _loadWithSPDY;
    _Bool _isSPDYError;
    _Bool _canReportProfile;
    _Bool _isWaitForStopLoading;
    _Bool _isWaitForStopLoadingWithLoc;
    int _instanceId;
    int _loadingReqs;
    int _loadingReqsWithLoc;
    int _jsApiNum;
    NSString *_url;
    NSString *_ipAddress;
    double _startTime;
    double _stopLoadingTime;
    double _stopLoadingTimeWithLoc;
    H5PerformanceTiming *_performanceTiming;
    NSString *_generateFirst;
    NSString *_jsApiNames;
    NSString *_xContentVersion;
    NSDate *_firstAsyncStartDate;
    double _waitForStopTime;
    double _waitForStopTimeWithLoc;
    NSString *_errorType;
    NSString *_errorDomain;
    NSString *_errorCode;
    NSString *_errorExtra;
    NSString *_errorTrigger;
    NSString *_relatedImg;
    NSMutableString *_jsErrorsDetail;
}

+ (id)getMCC_MNC;
@property(retain, nonatomic) NSMutableString *jsErrorsDetail; // @synthesize jsErrorsDetail=_jsErrorsDetail;
@property(copy, nonatomic) NSString *relatedImg; // @synthesize relatedImg=_relatedImg;
@property(copy, nonatomic) NSString *errorTrigger; // @synthesize errorTrigger=_errorTrigger;
@property(copy, nonatomic) NSString *errorExtra; // @synthesize errorExtra=_errorExtra;
@property(copy, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *errorDomain; // @synthesize errorDomain=_errorDomain;
@property(copy, nonatomic) NSString *errorType; // @synthesize errorType=_errorType;
@property(nonatomic) double waitForStopTimeWithLoc; // @synthesize waitForStopTimeWithLoc=_waitForStopTimeWithLoc;
@property(nonatomic) double waitForStopTime; // @synthesize waitForStopTime=_waitForStopTime;
@property(nonatomic) _Bool isWaitForStopLoadingWithLoc; // @synthesize isWaitForStopLoadingWithLoc=_isWaitForStopLoadingWithLoc;
@property(nonatomic) _Bool isWaitForStopLoading; // @synthesize isWaitForStopLoading=_isWaitForStopLoading;
@property(retain, nonatomic) NSDate *firstAsyncStartDate; // @synthesize firstAsyncStartDate=_firstAsyncStartDate;
@property(nonatomic) _Bool canReportProfile; // @synthesize canReportProfile=_canReportProfile;
@property(nonatomic) _Bool isSPDYError; // @synthesize isSPDYError=_isSPDYError;
@property(copy, nonatomic) NSString *xContentVersion; // @synthesize xContentVersion=_xContentVersion;
@property(nonatomic) _Bool loadWithSPDY; // @synthesize loadWithSPDY=_loadWithSPDY;
@property(copy, nonatomic) NSString *jsApiNames; // @synthesize jsApiNames=_jsApiNames;
@property(nonatomic) int jsApiNum; // @synthesize jsApiNum=_jsApiNum;
@property(copy, nonatomic) NSString *generateFirst; // @synthesize generateFirst=_generateFirst;
@property(nonatomic) int loadingReqsWithLoc; // @synthesize loadingReqsWithLoc=_loadingReqsWithLoc;
@property(nonatomic) int loadingReqs; // @synthesize loadingReqs=_loadingReqs;
@property(nonatomic) _Bool isWK; // @synthesize isWK=_isWK;
@property(nonatomic) _Bool isReport; // @synthesize isReport=_isReport;
@property(retain, nonatomic) H5PerformanceTiming *performanceTiming; // @synthesize performanceTiming=_performanceTiming;
@property(nonatomic) double stopLoadingTimeWithLoc; // @synthesize stopLoadingTimeWithLoc=_stopLoadingTimeWithLoc;
@property(nonatomic) double stopLoadingTime; // @synthesize stopLoadingTime=_stopLoadingTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *ipAddress; // @synthesize ipAddress=_ipAddress;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int instanceId; // @synthesize instanceId=_instanceId;
- (void).cxx_destruct;
- (void)reportLoadWithXContentVersion:(id)arg1;
- (void)reportLoadWithSPDY;
- (void)reportPageAbnormalWithPerformance:(id)arg1;
- (void)reportPageAbnormal;
- (void)reportPageAbnormalWithErrorType:(id)arg1 withError:(id)arg2;
- (void)reportPageAbnormalWithErrorType:(id)arg1 andErrorCode:(id)arg2;
- (void)reportSyncAjax;
- (void)reportJSErrorsDetail;
- (void)reportPerformance;
- (void)printLog;
- (void)reportDidFinishedLoadDate:(id)arg1;
- (void)reportRenderTime:(id)arg1;
- (void)reportReportWithReason:(id)arg1 notes:(id)arg2;
- (void)reportReport;
- (void)reportJSReport:(id)arg1;
- (void)reportJSMonitor:(id)arg1;
- (void)screenShotHandler;
- (void)screenShot;
- (void)reportPSDType:(id)arg1;
- (void)reportCreateDate:(id)arg1;
- (void)stopLoadingWithLoc;
- (void)stopLoading;
- (void)stopWaitForStopLoading;
- (void)waitForStopLoading;
- (void)stopWaitForStopLoadingWithLoc;
- (void)waitForStopLoadingWithLoc;
- (void)reportLocEnd;
- (void)reportLocStart;
- (void)reportReqEnd;
- (void)reportReqStart;
- (void)mergeProfile:(id)arg1;
- (id)init;

@end

