//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, UIImage;

@interface HPAd : NSObject <NSCoding, NSCopying>
{
    NSString *_adId;
    NSString *_appId;
    NSString *_content;
    NSString *_hrefUrl;
    NSString *_adType;
    NSString *_behavior;
    long long _gmtStart;
    long long _gmtEnd;
    UIImage *_adImage;
    double _adInterval;
}

+ (id)adWithDictionary:(id)arg1;
@property(nonatomic) double adInterval; // @synthesize adInterval=_adInterval;
@property(retain, nonatomic) UIImage *adImage; // @synthesize adImage=_adImage;
@property(nonatomic) long long gmtEnd; // @synthesize gmtEnd=_gmtEnd;
@property(nonatomic) long long gmtStart; // @synthesize gmtStart=_gmtStart;
@property(retain, nonatomic) NSString *behavior; // @synthesize behavior=_behavior;
@property(retain, nonatomic) NSString *adType; // @synthesize adType=_adType;
@property(retain, nonatomic) NSString *hrefUrl; // @synthesize hrefUrl=_hrefUrl;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *adId; // @synthesize adId=_adId;
- (void).cxx_destruct;
- (_Bool)isExpired;
- (double)bannerTimeInterval;
- (id)bannerAdSchemeUrl;
- (id)bannerAdImageUrl;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)prepareAdImage;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

