//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HSMSToString.h"

@class HSMSTid, NSDictionary, NSString;

@interface HSMSCancelApproveReq : HSMSToString
{
    NSDictionary *_mobileOperationEnvironment;
    HSMSTid *_tid;
    NSString *_approveId;
    NSString *_approveType;
    NSString *_scope;
    NSString *_appId;
}

+ (Class)mobileOperationEnvironmentElementClass;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(retain, nonatomic) NSString *approveType; // @synthesize approveType=_approveType;
@property(retain, nonatomic) NSString *approveId; // @synthesize approveId=_approveId;
@property(retain, nonatomic) HSMSTid *tid; // @synthesize tid=_tid;
@property(retain, nonatomic) NSDictionary *mobileOperationEnvironment; // @synthesize mobileOperationEnvironment=_mobileOperationEnvironment;
- (void).cxx_destruct;

@end

