//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HSMSMobileSecurityResult.h"

@class NSString;

@interface HSMSConfirmApproveRes : HSMSMobileSecurityResult
{
    NSString *_authCode;
    NSString *_openId;
}

@property(retain, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(retain, nonatomic) NSString *authCode; // @synthesize authCode=_authCode;
- (void).cxx_destruct;

@end

