//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface HXEntranceMgr : NSObject
{
    NSDictionary *_bizDataDic;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool bizEffect;
- (id)badgeId;
- (id)content;
- (id)actionUrl;
- (id)iconUrl;
- (void)cdpReportClick;
- (void)cdpReportShow;
- (void)setBizData:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)saveCache:(id)arg1;
- (void)resetCache;
- (id)init;

@end

