//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMPAutoRotateVC.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ImmPaySettingService, NSMutableArray, NSString, UITableView;

@interface ImmPayNoPwdSetting : MMPAutoRotateVC <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *_tableView;
    NSMutableArray *_dataSource;
    NSMutableArray *_sectionHeaderArr;
    ImmPaySettingService *_settingService;
}

@property(nonatomic) __weak ImmPaySettingService *settingService; // @synthesize settingService=_settingService;
@property(retain, nonatomic) NSMutableArray *sectionHeaderArr; // @synthesize sectionHeaderArr=_sectionHeaderArr;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)doClickNaviLeftAction:(id)arg1;
- (void)updatePaySettingNopwdCredit;
- (void)updateSetting;
- (void)showThirdParty;
- (void)showNoPwdCreditSetting;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
@property(readonly, nonatomic) _Bool showThirdPartyNoPwd;
@property(readonly, nonatomic) _Bool showOurNoPwd;
- (void)setupDataSource;
- (void)viewDidLoad;
- (id)initWithSetting:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

