//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface IndoorParser : NSObject
{
    int _position;
    NSMutableData *_data;
}

@property(nonatomic) int position; // @synthesize position=_position;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)getData:(int)arg1;
- (id)getData;
- (id)getString:(int)arg1;
- (id)getString;
- (double)getDouble;
- (float)getFloat;
- (long long)getInt64;
- (long long)getInt48;
- (int)getInt32;
- (short)getInt16;
- (BOOL)getInt8;
- (void)appendData:(id)arg1;
- (void)replaceInt32:(int)arg1 position:(int)arg2;
- (void)replaceInt16:(int)arg1 position:(int)arg2;
- (void)appendUuid:(id)arg1;
- (void)appendStr:(id)arg1;
- (void)appendString:(id)arg1;
- (void)appendDouble:(double)arg1;
- (void)appendFloat:(float)arg1;
- (void)appendInt64:(long long)arg1;
- (void)appendInt48:(long long)arg1;
- (void)appendInt32:(int)arg1;
- (void)appendInt16:(int)arg1;
- (void)appendInt8:(int)arg1;
@property(readonly, nonatomic) int remaining;
- (void)reset;
- (id)initWithData:(id)arg1;
- (id)init;

@end

