//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"
#import "LocationMotionDelegate.h"

@class CLLocationManager, IndoorSensorOC, LocationMotion, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, NSTimer;

@interface IndoorSensorSingle : NSObject <LocationMotionDelegate, CLLocationManagerDelegate>
{
    int _step;
    float _orientation;
    float _pressure;
    float _heading;
    int _mTimes;
    NSString *_debugString;
    NSMutableSet *_delegates;
    IndoorSensorOC *_pdrService;
    LocationMotion *_locationMotion;
    CLLocationManager *_locationManager;
    unsigned long long _mStatus;
    NSObject<OS_dispatch_queue> *_mQueue;
    NSTimer *_mTimer;
}

+ (void)stopSensor:(id)arg1;
+ (id)startSensor:(id)arg1;
@property(nonatomic) int mTimes; // @synthesize mTimes=_mTimes;
@property(retain, nonatomic) NSTimer *mTimer; // @synthesize mTimer=_mTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *mQueue; // @synthesize mQueue=_mQueue;
@property(nonatomic) unsigned long long mStatus; // @synthesize mStatus=_mStatus;
@property(nonatomic) float heading; // @synthesize heading=_heading;
@property(nonatomic) float pressure; // @synthesize pressure=_pressure;
@property(nonatomic) float orientation; // @synthesize orientation=_orientation;
@property(nonatomic) int step; // @synthesize step=_step;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) LocationMotion *locationMotion; // @synthesize locationMotion=_locationMotion;
@property(retain, nonatomic) IndoorSensorOC *pdrService; // @synthesize pdrService=_pdrService;
@property(retain, nonatomic) NSMutableSet *delegates; // @synthesize delegates=_delegates;
@property(readonly, nonatomic) NSString *debugString; // @synthesize debugString=_debugString;
- (void).cxx_destruct;
- (void)dealloc;
- (void)locationManager:(id)arg1 didUpdateHeading:(id)arg2;
- (void)locationMotion:(id)arg1 didUpdatePressure:(long long)arg2 pressure:(double)arg3;
- (void)locationMotion:(id)arg1 didUpdateUncalibrateMagneto:(long long)arg2 x:(double)arg3 y:(double)arg4 z:(double)arg5;
- (void)locationMotion:(id)arg1 didUpdateMagneto:(long long)arg2 x:(double)arg3 y:(double)arg4 z:(double)arg5;
- (void)locationMotion:(id)arg1 didUpdateGyro:(long long)arg2 x:(double)arg3 y:(double)arg4 z:(double)arg5;
- (void)locationMotion:(id)arg1 didUpdateGravity:(long long)arg2 x:(double)arg3 y:(double)arg4 z:(double)arg5;
- (void)locationMotion:(id)arg1 didUpdateAcceleration:(long long)arg2 lx:(double)arg3 ly:(double)arg4 lz:(double)arg5 x:(double)arg6 y:(double)arg7 z:(double)arg8;
- (void)onTimer:(id)arg1;
- (int)stopSensor;
- (int)startSensor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

