//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KABAOPRODToString.h"

@class NSString;

@interface KABAOPRODFundAsset : KABAOPRODToString
{
    NSString *_fundTotalAmount;
    NSString *_fundTotalUseShare;
    NSString *_fundAvailableQuotient;
    NSString *_fundTotalFreezeShare;
    NSString *_fundTotalProfit;
}

@property(retain, nonatomic) NSString *fundTotalProfit; // @synthesize fundTotalProfit=_fundTotalProfit;
@property(retain, nonatomic) NSString *fundTotalFreezeShare; // @synthesize fundTotalFreezeShare=_fundTotalFreezeShare;
@property(retain, nonatomic) NSString *fundAvailableQuotient; // @synthesize fundAvailableQuotient=_fundAvailableQuotient;
@property(retain, nonatomic) NSString *fundTotalUseShare; // @synthesize fundTotalUseShare=_fundTotalUseShare;
@property(retain, nonatomic) NSString *fundTotalAmount; // @synthesize fundTotalAmount=_fundTotalAmount;
- (void).cxx_destruct;

@end

