//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface KBShopReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasLongitude;
    _Bool _hasLatitude;
    NSString *_longitude;
    NSString *_latitude;
    NSMutableArray *_passId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *passId; // @synthesize passId=_passId;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(readonly) _Bool hasLatitude; // @synthesize hasLatitude=_hasLatitude;
@property(readonly) _Bool hasLongitude; // @synthesize hasLongitude=_hasLongitude;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addPassId:(id)arg1;
- (void)setPassIdArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

