//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLLocation, LBSAddressInfo, LBSLocator, NSError;

@protocol LBSLocatorDelegate <NSObject>

@optional
- (void)locator:(LBSLocator *)arg1 didFailWithError:(NSError *)arg2;
- (void)locator:(LBSLocator *)arg1 didFinishReversingGeocode:(LBSAddressInfo *)arg2 fromLocation:(CLLocation *)arg3;
- (void)locator:(LBSLocator *)arg1 didFinishLocating:(CLLocation *)arg2;
@end

