//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class LFCPBObjectInfo, LFCPBUserInfo, NSString;

@interface LFCPBReplyInfo : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasObjectInfo;
    _Bool _hasClientId;
    _Bool _hasServerId;
    _Bool _hasUserInfo;
    _Bool _hasToServerId;
    _Bool _hasToUserInfo;
    _Bool _hasContent;
    _Bool _hasGmtCreate;
    _Bool _hasGmtModify;
    _Bool _hasExtend;
    LFCPBObjectInfo *_objectInfo;
    NSString *_clientId;
    NSString *_serverId;
    LFCPBUserInfo *_userInfo;
    NSString *_toServerId;
    LFCPBUserInfo *_toUserInfo;
    NSString *_content;
    long long _gmtCreate;
    long long _gmtModify;
    NSString *_extend;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *extend; // @synthesize extend=_extend;
@property(nonatomic) long long gmtModify; // @synthesize gmtModify=_gmtModify;
@property(nonatomic) long long gmtCreate; // @synthesize gmtCreate=_gmtCreate;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) LFCPBUserInfo *toUserInfo; // @synthesize toUserInfo=_toUserInfo;
@property(retain, nonatomic) NSString *toServerId; // @synthesize toServerId=_toServerId;
@property(retain, nonatomic) LFCPBUserInfo *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSString *serverId; // @synthesize serverId=_serverId;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) LFCPBObjectInfo *objectInfo; // @synthesize objectInfo=_objectInfo;
@property(readonly) _Bool hasExtend; // @synthesize hasExtend=_hasExtend;
@property(readonly) _Bool hasGmtModify; // @synthesize hasGmtModify=_hasGmtModify;
@property(readonly) _Bool hasGmtCreate; // @synthesize hasGmtCreate=_hasGmtCreate;
@property(readonly) _Bool hasContent; // @synthesize hasContent=_hasContent;
@property(readonly) _Bool hasToUserInfo; // @synthesize hasToUserInfo=_hasToUserInfo;
@property(readonly) _Bool hasToServerId; // @synthesize hasToServerId=_hasToServerId;
@property(readonly) _Bool hasUserInfo; // @synthesize hasUserInfo=_hasUserInfo;
@property(readonly) _Bool hasServerId; // @synthesize hasServerId=_hasServerId;
@property(readonly) _Bool hasClientId; // @synthesize hasClientId=_hasClientId;
@property(readonly) _Bool hasObjectInfo; // @synthesize hasObjectInfo=_hasObjectInfo;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

