//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class LFCPBObjectInfo, LFCPBUserInfo, NSString;

@interface LFCPBRewardInfo : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasObjectInfo;
    _Bool _hasClientId;
    _Bool _hasServerId;
    _Bool _hasFromUser;
    _Bool _hasToUser;
    _Bool _hasBillNo;
    _Bool _hasMoney;
    _Bool _hasGmtCreate;
    _Bool _hasGmtModify;
    _Bool _hasExtend;
    _Bool _hasRewardSource;
    LFCPBObjectInfo *_objectInfo;
    NSString *_clientId;
    NSString *_serverId;
    LFCPBUserInfo *_fromUser;
    LFCPBUserInfo *_toUser;
    NSString *_billNo;
    NSString *_money;
    long long _gmtCreate;
    long long _gmtModify;
    NSString *_extend;
    long long _rewardSource;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic) long long rewardSource; // @synthesize rewardSource=_rewardSource;
@property(retain, nonatomic) NSString *extend; // @synthesize extend=_extend;
@property(nonatomic) long long gmtModify; // @synthesize gmtModify=_gmtModify;
@property(nonatomic) long long gmtCreate; // @synthesize gmtCreate=_gmtCreate;
@property(retain, nonatomic) NSString *money; // @synthesize money=_money;
@property(retain, nonatomic) NSString *billNo; // @synthesize billNo=_billNo;
@property(retain, nonatomic) LFCPBUserInfo *toUser; // @synthesize toUser=_toUser;
@property(retain, nonatomic) LFCPBUserInfo *fromUser; // @synthesize fromUser=_fromUser;
@property(retain, nonatomic) NSString *serverId; // @synthesize serverId=_serverId;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) LFCPBObjectInfo *objectInfo; // @synthesize objectInfo=_objectInfo;
@property(readonly) _Bool hasRewardSource; // @synthesize hasRewardSource=_hasRewardSource;
@property(readonly) _Bool hasExtend; // @synthesize hasExtend=_hasExtend;
@property(readonly) _Bool hasGmtModify; // @synthesize hasGmtModify=_hasGmtModify;
@property(readonly) _Bool hasGmtCreate; // @synthesize hasGmtCreate=_hasGmtCreate;
@property(readonly) _Bool hasMoney; // @synthesize hasMoney=_hasMoney;
@property(readonly) _Bool hasBillNo; // @synthesize hasBillNo=_hasBillNo;
@property(readonly) _Bool hasToUser; // @synthesize hasToUser=_hasToUser;
@property(readonly) _Bool hasFromUser; // @synthesize hasFromUser=_hasFromUser;
@property(readonly) _Bool hasServerId; // @synthesize hasServerId=_hasServerId;
@property(readonly) _Bool hasClientId; // @synthesize hasClientId=_hasClientId;
@property(readonly) _Bool hasObjectInfo; // @synthesize hasObjectInfo=_hasObjectInfo;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

