//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface LFDynamicView : UIView
{
    NSArray *_dynamicInfos;
}

@property(retain, nonatomic) NSArray *dynamicInfos; // @synthesize dynamicInfos=_dynamicInfos;
- (void).cxx_destruct;
- (id)numberToString:(long long)arg1;
- (id)getLabelText:(long long)arg1 info:(id)arg2;
- (id)refreshDynamicView:(id)arg1;
- (void)refreshItemView:(int)arg1 itemInfo:(id)arg2;
- (void)refreshItemInfo:(id)arg1 isAdd:(_Bool)arg2;
- (void)addItemViews;
- (id)initWithFrame:(struct CGRect)arg1 dynamicInfos:(id)arg2;

@end

