//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LFHomeCardTransfer : NSObject
{
}

+ (void)resetCssDic:(id)arg1 tag:(id)arg2 string:(id)arg3;
+ (id)recallMessageId:(id)arg1;
+ (void)replaceCard:(id)arg1 withPraiseCount:(long long)arg2 replyCount:(long long)arg3 hasPraised:(_Bool)arg4;
+ (void)replaceCard:(id)arg1 withPraiseOptionState:(int *)arg2;
+ (void)replaceCard:(id)arg1 withAction:(id)arg2;
+ (void)replaceCard:(id)arg1 withPublicInfo:(id)arg2;
+ (void)replaceCardList:(id)arg1 withPublicInfo:(id)arg2;
+ (id)cardsFromLFHomeCardModels:(id)arg1;
+ (id)extDic:(id)arg1;
+ (id)cardFromLFHomeCardModel:(id)arg1;
+ (id)actions:(id)arg1 templateCode:(unsigned long long)arg2 actionId:(id)arg3 action:(id)arg4 publicBizType:(id)arg5;
+ (id)gotoDetail:(id)arg1 actionName:(id)arg2;
+ (id)comment:(id)arg1 actionId:(id)arg2 action:(id)arg3 publicBizType:(id)arg4;
+ (id)praise:(id)arg1 actionId:(id)arg2 publicBizType:(id)arg3;
+ (_Bool)setTemplateDataArticle:(id)arg1 ToDataDic:(id)arg2 templateCode:(unsigned long long)arg3 publicBizType:(id)arg4 contents:(id)arg5 cssDic:(id)arg6;
+ (id)setTemplateData:(id)arg1 mType:(id)arg2 templateCode:(unsigned long long)arg3 ToCardTemplateDataDic:(id)arg4 publicBizType:(id)arg5 contents:(id)arg6 cssDic:(id)arg7;
+ (id)topBar:(id)arg1 syncReceivedTime:(long long)arg2;
+ (id)infoArea:(id)arg1;
+ (id)cardTemplateData:(id)arg1 mType:(id)arg2 templateCode:(unsigned long long)arg3 syncReceivedTime:(long long)arg4 actionId:(id)arg5 publicBizType:(id)arg6 bizLogMonitor:(id)arg7;
+ (id)getCardWithSyncData:(id)arg1 syncReceivedTime:(long long)arg2;
+ (id)getCardList:(id)arg1 publicId:(id)arg2;

@end

