//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEEDataController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "WWPhotoBrowserDelegate.h"

@class CLoadMoreView, NSString, UICollectionView;

@interface LifePhotoGridViewController : BEEDataController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, WWPhotoBrowserDelegate>
{
    NSString *_publicId;
    _Bool _disableMoreLoading;
    NSString *_lastReadedId;
    UICollectionView *_collectionView;
    CLoadMoreView *_loadMoreView;
}

- (void).cxx_destruct;
- (id)photoAtIndex:(unsigned long long)arg1;
- (id)photoBrowser:(id)arg1 thumbPhotoAtIndex:(unsigned long long)arg2;
- (id)photoBrowser:(id)arg1 photoAtIndex:(unsigned long long)arg2;
- (unsigned long long)numberOfPhotosInPhotoBrowser:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)cacheKey;
- (id)emptyText;
- (void)loadMore;
- (void)loadContent;
- (id)loadOnline;
- (void)viewDidLoad;
- (id)initWithPublicId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

