//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LifeCardViewController.h"

#import "AUSearchTitleViewDelegate.h"
#import "LFInfoViewDelegate.h"
#import "LFPhotoViewDelegate.h"

@class APCustomNavigationView, APExceptionView, AUSearchTitleView, LFHomeCardModel, LFHomeCardMonitor, LFInfoView, LifeHomeResult, NSString, UIAlertView;

@interface LifeHomeViewController : LifeCardViewController <LFPhotoViewDelegate, LFInfoViewDelegate, AUSearchTitleViewDelegate>
{
    _Bool _isUpgrade;
    _Bool _hasGotoUrl;
    _Bool _hasCache;
    _Bool _isMenuLoading;
    _Bool _isRefreshing;
    _Bool _isViewAppear;
    _Bool _isWhiteNavigationBar;
    NSString *_publicId;
    NSString *_sourceId;
    NSString *_extArgs;
    NSString *_gotoUrl;
    LifeHomeResult *_homeInfo;
    APCustomNavigationView *_navigationView;
    AUSearchTitleView *_searchView;
    LFInfoView *_infoView;
    LFHomeCardModel *_lastDeleteBoardMessage;
    APExceptionView *_networkErrorView;
    UIAlertView *_alertView;
    long long _lastMenuFinishLoading;
    LFHomeCardMonitor *_homeCardMonitor;
}

@property(retain, nonatomic) LFHomeCardMonitor *homeCardMonitor; // @synthesize homeCardMonitor=_homeCardMonitor;
@property(nonatomic) _Bool isWhiteNavigationBar; // @synthesize isWhiteNavigationBar=_isWhiteNavigationBar;
@property(nonatomic) _Bool isViewAppear; // @synthesize isViewAppear=_isViewAppear;
@property(nonatomic) _Bool isRefreshing; // @synthesize isRefreshing=_isRefreshing;
@property(nonatomic) long long lastMenuFinishLoading; // @synthesize lastMenuFinishLoading=_lastMenuFinishLoading;
@property(nonatomic) _Bool isMenuLoading; // @synthesize isMenuLoading=_isMenuLoading;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) APExceptionView *networkErrorView; // @synthesize networkErrorView=_networkErrorView;
@property(retain, nonatomic) LFHomeCardModel *lastDeleteBoardMessage; // @synthesize lastDeleteBoardMessage=_lastDeleteBoardMessage;
@property(retain, nonatomic) LFInfoView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) AUSearchTitleView *searchView; // @synthesize searchView=_searchView;
@property(retain, nonatomic) APCustomNavigationView *navigationView; // @synthesize navigationView=_navigationView;
@property(retain, nonatomic) LifeHomeResult *homeInfo; // @synthesize homeInfo=_homeInfo;
@property(nonatomic) _Bool hasCache; // @synthesize hasCache=_hasCache;
@property(nonatomic) _Bool hasGotoUrl; // @synthesize hasGotoUrl=_hasGotoUrl;
@property(nonatomic) _Bool isUpgrade; // @synthesize isUpgrade=_isUpgrade;
@property(retain, nonatomic) NSString *gotoUrl; // @synthesize gotoUrl=_gotoUrl;
@property(retain, nonatomic) NSString *extArgs; // @synthesize extArgs=_extArgs;
@property(retain, nonatomic) NSString *sourceId; // @synthesize sourceId=_sourceId;
@property(retain, nonatomic) NSString *publicId; // @synthesize publicId=_publicId;
- (void).cxx_destruct;
- (void)didPressedTitleView:(id)arg1;
- (long long)customStatusBarStytle;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (_Bool)autohideNavigationBar;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)gotoPhotoList;
- (void)settingClicked;
- (void)setStatusBarStyle:(_Bool)arg1;
- (double)getAnnouncementViewHeight;
- (void)setNavigationViewAlphaAndIcon:(double)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateMessageList:(id)arg1;
- (void)loadMoreHomeCard:(id)arg1 andExt:(id)arg2;
- (void)checkLoadMore;
- (void)checkHasMore:(id)arg1;
- (void)lifeMsgDetail:(id)arg1;
- (void)optionChanged:(id)arg1;
- (void)menuRPCLoading:(id)arg1;
- (void)doInsertScrollAnimation;
- (void)homecardDelete:(id)arg1;
- (void)homecardInsert:(id)arg1;
- (void)resetExtendView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)onNetworkErrorView;
- (id)networkErrorView:(int)arg1;
- (void)reportLocation;
- (void)handleCardList:(id)arg1 actionList:(id)arg2 originCardList:(id)arg3 isCacheData:(_Bool)arg4 isRefresh:(_Bool)arg5;
- (void)homeInfoRPCWithBoardcastList:(id)arg1 syncList:(id)arg2 originCardList:(id)arg3;
- (void)getCacheDataAndRPCRequest;
- (void)startLoading;
- (void)setTitleBarAndHomeView:(id)arg1;
- (id)addNavigationView;
- (id)promotionBizInfo;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)addObserverNotifications;
- (void)viewDidLoad;
- (id)initWithOptions:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

