//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LIVETRADEPRODOnsiteBaseRes.h"

@class NSString;

@interface LIVETRADEPRODCreatePayeeQrcodeRes : LIVETRADEPRODOnsiteBaseRes
{
    NSString *_qrcode;
    NSString *_qrcodeImageUrl;
}

@property(retain, nonatomic) NSString *qrcodeImageUrl; // @synthesize qrcodeImageUrl=_qrcodeImageUrl;
@property(retain, nonatomic) NSString *qrcode; // @synthesize qrcode=_qrcode;
- (void).cxx_destruct;

@end

