//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LIVETRADEPRODOnsiteBaseRes.h"

@class NSArray;

@interface LIVETRADEPRODQuerySellerRes : LIVETRADEPRODOnsiteBaseRes
{
    NSArray *_tradeInfo;
}

+ (Class)tradeInfoElementClass;
@property(retain, nonatomic) NSArray *tradeInfo; // @synthesize tradeInfo=_tradeInfo;
- (void).cxx_destruct;

@end

