//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMAltimeter, CMMotionManager, NSOperationQueue;

@interface LocationMotion : NSObject
{
    CMAltimeter *motionAltimeter;
    CDStruct_31142d93 acceleration;
    id <LocationMotionDelegate> _delegate;
    NSOperationQueue *_motionQueue;
    CMMotionManager *_motionManager;
}

@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(retain, nonatomic) NSOperationQueue *motionQueue; // @synthesize motionQueue=_motionQueue;
@property(nonatomic) __weak id <LocationMotionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stop;
- (void)start;
- (id)initWithDelegate:(id)arg1;

@end

