//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LoginLogsMSToString.h"

@interface LoginLogsMSSetLoginNotifyStatReq : LoginLogsMSToString
{
    _Bool _open;
}

@property(nonatomic) _Bool open; // @synthesize open=_open;

@end

