//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CTGrowingTextViewDelegate.h"
#import "UITextFieldDelegate.h"

@class CAGradientLayer, CTGrowingTextView, NSString, UIButton, UIView;

@interface LSCreateLiveWidget : NSObject <UITextFieldDelegate, CTGrowingTextViewDelegate>
{
    _Bool _keyboardShow;
    CDUnknownBlockType _createBlock;
    UIView *_superView;
    UIView *_createLiveContainerView;
    UIButton *_createLiveBtn;
    CAGradientLayer *_maskLayer;
    double _startLocY;
    CTGrowingTextView *_growingText;
}

+ (id)createLiveViewWithLocY:(double)arg1 inSuperView:(id)arg2 createLiveBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) CTGrowingTextView *growingText; // @synthesize growingText=_growingText;
@property(nonatomic) _Bool keyboardShow; // @synthesize keyboardShow=_keyboardShow;
@property(nonatomic) double startLocY; // @synthesize startLocY=_startLocY;
@property(retain, nonatomic) CAGradientLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) UIButton *createLiveBtn; // @synthesize createLiveBtn=_createLiveBtn;
@property(retain, nonatomic) UIView *createLiveContainerView; // @synthesize createLiveContainerView=_createLiveContainerView;
@property(nonatomic) __weak UIView *superView; // @synthesize superView=_superView;
@property(copy, nonatomic) CDUnknownBlockType createBlock; // @synthesize createBlock=_createBlock;
- (void).cxx_destruct;
- (void)clearWidget;
- (void)createLive;
- (void)resignTextField;
- (void)doCreateLive:(id)arg1;
- (id)mCreateLiveBtn;
- (_Bool)inputShouldChangeNewString:(id)arg1 range:(struct _NSRange)arg2 originString:(id)arg3 maxLen:(long long)arg4;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)growingTextViewDidChange:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)registerNotification;
- (void)growingTextView:(id)arg1 willChangeHeight:(float)arg2;
- (void)hideWithAnimated:(_Bool)arg1;
- (void)showWithAnimated:(_Bool)arg1;
- (void)buildCreateLiveWidget:(double)arg1;
@property(readonly, nonatomic) _Bool visibleState;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

