//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface LSErrorInfo : NSObject
{
    long long _errorCode;
    NSString *_errorMemo;
    NSDictionary *_extendInfo;
}

@property(retain, nonatomic) NSDictionary *extendInfo; // @synthesize extendInfo=_extendInfo;
@property(retain, nonatomic) NSString *errorMemo; // @synthesize errorMemo=_errorMemo;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
- (void).cxx_destruct;
- (id)init;

@end

