//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class APContactInfo, NSDate, NSDictionary, NSString;

@interface LSOptionInfo : NSObject <NSCopying>
{
    _Bool _isLocal;
    _Bool _isReplay;
    APContactInfo *_userInfo;
    long long _optionType;
    NSString *_optionId;
    NSString *_liveId;
    NSDate *_date;
    double _offset;
    NSString *_content;
    NSDictionary *_extend;
}

+ (id)countDownOption:(int)arg1;
+ (id)countDownRemindOption:(int)arg1;
+ (id)closeLiveOptionInfo;
@property(nonatomic) _Bool isReplay; // @synthesize isReplay=_isReplay;
@property(nonatomic) _Bool isLocal; // @synthesize isLocal=_isLocal;
@property(retain, nonatomic) NSDictionary *extend; // @synthesize extend=_extend;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *liveId; // @synthesize liveId=_liveId;
@property(retain, nonatomic) NSString *optionId; // @synthesize optionId=_optionId;
@property(nonatomic) long long optionType; // @synthesize optionType=_optionType;
@property(retain, nonatomic) APContactInfo *userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateWithReplayDeletePayload:(id)arg1;
- (void)updateWithMessagePayload:(id)arg1;
- (void)updateWithSyncPayload:(id)arg1;
- (void)updateWithRewardSyncPayload:(id)arg1;
- (void)updateWithCloseLivePayload:(id)arg1;
- (void)updateWithWatcherChangePayload:(id)arg1;
- (void)updateWithPraiseSyncPayload:(id)arg1;
@property(readonly, nonatomic) long long participateType;
@property(readonly, nonatomic) NSString *closeReasonMemo;
@property(readonly, nonatomic) long long sendCloseType;
@property(readonly, nonatomic) long long closeLiveType;

@end

