//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LSPraiseDataManager, LSSyncUpDataManager, NSOperationQueue;

@interface LSOptionDataManager : NSObject
{
    NSOperationQueue *_optionQueue;
    LSSyncUpDataManager *_syncManager;
    LSPraiseDataManager *_praiseManager;
}

+ (id)buildLiveShowParticipateOptionWithLiveId:(id)arg1 participateType:(long long)arg2;
+ (id)buildLiveShowRewardOptionWithLiveId:(id)arg1 amount:(id)arg2;
+ (id)buildLiveShowCloseLiveOptionWithLiveId:(id)arg1 closeType:(long long)arg2;
+ (id)buildLiveShowPraiseOptionWithLiveId:(id)arg1;
+ (id)buildLiveShowCommentOptionWithLiveId:(id)arg1 content:(id)arg2;
@property(retain, nonatomic) LSPraiseDataManager *praiseManager; // @synthesize praiseManager=_praiseManager;
@property(retain, nonatomic) LSSyncUpDataManager *syncManager; // @synthesize syncManager=_syncManager;
@property(retain, nonatomic) NSOperationQueue *optionQueue; // @synthesize optionQueue=_optionQueue;
- (void).cxx_destruct;
- (void)clear;
- (void)mockPraiseOption;
- (void)addStartLive:(id)arg1;
- (void)addCloseLive:(id)arg1 callback:(CDUnknownFunctionPointerType)arg2;
- (void)addLiveShowReward:(id)arg1 callback:(CDUnknownFunctionPointerType)arg2;
- (void)addLiveShowPraise:(id)arg1 callback:(CDUnknownFunctionPointerType)arg2;
- (void)addLiveShowComment:(id)arg1 callback:(CDUnknownFunctionPointerType)arg2;
- (id)mPraiseDataManager;
- (id)mSyncManager;
- (id)init;

@end

