//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"
#import "AVAudioRecorderDelegate.h"

@class AVAudioPlayer, AVAudioRecorder, LWAMRPlayer, NSError, NSString, NSURL;

@interface LWAudioRecorder : NSObject <AVAudioRecorderDelegate, AVAudioPlayerDelegate>
{
    NSURL *recordedTmpFile;
    NSError *error;
    AVAudioRecorder *recorder;
    LWAMRPlayer *amrplayer;
    AVAudioPlayer *avAudioPlayer;
    unsigned long long lastPlayIdentifier;
    _Bool earphoneModeEnabled;
    CDUnknownBlockType onSwitchToSpeaker;
    CDUnknownBlockType onPlayDidStopped;
    double _maxDuration;
    id <AudioRecordFinishDelegate> _delegate;
}

+ (id)sharedAudioRecorder;
@property(nonatomic) id <AudioRecordFinishDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double maxDuration; // @synthesize maxDuration=_maxDuration;
@property(copy, nonatomic) CDUnknownBlockType onPlayDidStopped; // @synthesize onPlayDidStopped;
@property(copy, nonatomic) CDUnknownBlockType onSwitchToSpeaker; // @synthesize onSwitchToSpeaker;
@property(nonatomic) _Bool earphoneModeEnabled; // @synthesize earphoneModeEnabled;
@property(readonly, nonatomic) unsigned long long lastPlayIdentifier; // @synthesize lastPlayIdentifier;
- (double)currentTime:(unsigned long long)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)stopPlay;
- (_Bool)isPlaying;
- (_Bool)isPlaying:(unsigned long long)arg1;
- (void)sendStatus:(int)arg1;
- (void)play:(id)arg1 playIdentifier:(unsigned long long)arg2;
- (void)playWave:(id)arg1 playIdentifier:(unsigned long long)arg2;
- (void)playAmr:(id)arg1 playIdentifier:(unsigned long long)arg2;
- (void)keepLastPlayMode;
- (id)decodeAmr:(id)arg1;
- (float)peakPowerForChannel;
- (_Bool)isRecording;
- (id)stopRecord;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)startRecordWithDelegate:(id)arg1;
- (void)startRecord;
- (double)getAudioTime:(id)arg1;
- (void)audioUnActive;
- (void)audioActive;
- (void)replay;
- (void)sensorStateChange:(id)arg1;
- (void)initAudioSession;
- (void)setProximityMonitoringEnabled:(_Bool)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

