//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MASSDownBaseMethod.h"

@class NSDictionary, NSString;

@interface MASSTFSDownMethod : MASSDownBaseMethod
{
    _Bool _otherUrl;
    NSString *_url;
    NSDictionary *_externHeaders;
}

@property(nonatomic) _Bool otherUrl; // @synthesize otherUrl=_otherUrl;
@property(retain, nonatomic) NSDictionary *externHeaders; // @synthesize externHeaders=_externHeaders;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;

@end

