//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MAAccess, NSDictionary;

@protocol MAStatusInterface <NSObject>

@optional
- (void)appEnterForground;
- (void)reLoginNotice;
- (void)connectStatistic:(NSDictionary *)arg1;
- (void)noticeShortChannelIsOpen:(_Bool)arg1;
- (void)connectStatus:(long long)arg1;
- (void)accessOnLoginOut:(MAAccess *)arg1;
- (void)accessOnLogin:(MAAccess *)arg1;
- (void)accessDidInit:(MAAccess *)arg1;
@end

