//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MBPushMsgInfoItem : NSObject
{
    NSString *_msgID;
    long long _createTime;
    long long _staleTime;
}

@property(nonatomic) long long staleTime; // @synthesize staleTime=_staleTime;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *msgID; // @synthesize msgID=_msgID;
- (void).cxx_destruct;

@end

