//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface Menu : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasMenuName;
    _Bool _hasMenuUrl;
    NSString *_menuName;
    NSString *_menuUrl;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *menuUrl; // @synthesize menuUrl=_menuUrl;
@property(retain, nonatomic) NSString *menuName; // @synthesize menuName=_menuName;
@property(readonly) _Bool hasMenuUrl; // @synthesize hasMenuUrl=_hasMenuUrl;
@property(readonly) _Bool hasMenuName; // @synthesize hasMenuName=_hasMenuName;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

