//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface MGLivenessDetectionFrameEncodedData : NSObject
{
    NSData *_00396;
    struct MGFaceAttr _00507;
}

@property(readonly) struct MGFaceAttr attr; // @synthesize attr=_00507;
@property(readonly) NSData *data; // @synthesize data=_00396;
- (id).cxx_construct;
- (void)dealloc;
- (id)initWithData:(id)arg1 andMGAttr:(struct MGFaceAttr)arg2;

@end

