//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILEBILLToString.h"

@class NSString;

@interface MOBILEBILLQueryContactAddressReq : MOBILEBILLToString
{
    NSString *_bizInNo;
    NSString *_bizType;
    NSString *_bizSubType;
    long long _gmtCreate;
}

@property(nonatomic) long long gmtCreate; // @synthesize gmtCreate=_gmtCreate;
@property(retain, nonatomic) NSString *bizSubType; // @synthesize bizSubType=_bizSubType;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSString *bizInNo; // @synthesize bizInNo=_bizInNo;
- (void).cxx_destruct;

@end

