//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILECSABaseRpcResponse.h"

@class NSArray, NSString;

@interface MOBILECSACommentQueryResponse : MOBILECSABaseRpcResponse
{
    int _pageSize;
    NSArray *_briefTags;
    NSArray *_commentDetails;
    NSString *_totalCommentSum;
    NSString *_totalTags;
    NSString *_type;
    NSString *_friendCommentSum;
    double _evarScore;
    double _star;
    NSString *_lastCommentId;
    NSArray *_tabs;
    NSString *_topStandH5Url;
}

+ (Class)tabsElementClass;
+ (Class)commentDetailsElementClass;
+ (Class)briefTagsElementClass;
@property(retain, nonatomic) NSString *topStandH5Url; // @synthesize topStandH5Url=_topStandH5Url;
@property(retain, nonatomic) NSArray *tabs; // @synthesize tabs=_tabs;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(retain, nonatomic) NSString *lastCommentId; // @synthesize lastCommentId=_lastCommentId;
@property(nonatomic) double star; // @synthesize star=_star;
@property(nonatomic) double evarScore; // @synthesize evarScore=_evarScore;
@property(retain, nonatomic) NSString *friendCommentSum; // @synthesize friendCommentSum=_friendCommentSum;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *totalTags; // @synthesize totalTags=_totalTags;
@property(retain, nonatomic) NSString *totalCommentSum; // @synthesize totalCommentSum=_totalCommentSum;
@property(retain, nonatomic) NSArray *commentDetails; // @synthesize commentDetails=_commentDetails;
@property(retain, nonatomic) NSArray *briefTags; // @synthesize briefTags=_briefTags;
- (void).cxx_destruct;

@end

