//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILEPROMOADToString.h"

@class NSString;

@interface MOBILEPROMOADAdSpaceBehaviorReq : MOBILEPROMOADToString
{
    NSString *_spaceCode;
    NSString *_adId;
    NSString *_adBehavior;
}

@property(retain, nonatomic) NSString *adBehavior; // @synthesize adBehavior=_adBehavior;
@property(retain, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(retain, nonatomic) NSString *spaceCode; // @synthesize spaceCode=_spaceCode;
- (void).cxx_destruct;

@end

