//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILECSABaseRpcRequestV2.h"

@class NSString;

@interface MOBILECSAAppConfigRequestV2 : MOBILECSABaseRpcRequestV2
{
    NSString *_type;
    long long _lastModified;
}

@property(nonatomic) long long lastModified; // @synthesize lastModified=_lastModified;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

