//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILEPROMOADToString.h"

@class NSString;

@interface MOBILEPROMOADAdObjectInfo : MOBILEPROMOADToString
{
    int _hoverTime;
    NSString *_adId;
    NSString *_type;
    NSString *_behavior;
    NSString *_appId;
    NSString *_content;
    NSString *_hrefUrl;
    long long _gmtStart;
    long long _gmtEnd;
}

@property(nonatomic) long long gmtEnd; // @synthesize gmtEnd=_gmtEnd;
@property(nonatomic) long long gmtStart; // @synthesize gmtStart=_gmtStart;
@property(nonatomic) int hoverTime; // @synthesize hoverTime=_hoverTime;
@property(retain, nonatomic) NSString *hrefUrl; // @synthesize hrefUrl=_hrefUrl;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *behavior; // @synthesize behavior=_behavior;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *adId; // @synthesize adId=_adId;
- (void).cxx_destruct;

@end

