//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MOBILEPROMOADCommonResult.h"

@interface MOBILEPROMOADAdSpaceBehaviorResult : MOBILEPROMOADCommonResult
{
    _Bool _close;
}

@property(nonatomic) _Bool close; // @synthesize close=_close;

@end

