//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MS_HPUploadHeadImgReq : NSObject
{
    NSString *_headImg;
}

@property(retain, nonatomic) NSString *headImg; // @synthesize headImg=_headImg;
- (void).cxx_destruct;

@end

