//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSToString.h"

@class NSString;

@interface MSDeviceLockReq : MSToString
{
    NSString *_plateForm;
    NSString *_tid;
}

@property(retain, nonatomic) NSString *tid; // @synthesize tid=_tid;
@property(retain, nonatomic) NSString *plateForm; // @synthesize plateForm=_plateForm;
- (void).cxx_destruct;

@end

