//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSCommonRes.h"

@class NSString;

@interface MSGetSmsInNoRes : MSCommonRes
{
    NSString *_smsInNO;
    NSString *_sessionId;
}

@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) NSString *smsInNO; // @synthesize smsInNO=_smsInNO;
- (void).cxx_destruct;

@end

