//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSToString.h"

@class NSString;

@interface MSMobileBindQueryUpSmsReq : MSToString
{
    NSString *_sessionId;
    NSString *_logonId;
}

@property(retain, nonatomic) NSString *logonId; // @synthesize logonId=_logonId;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;

@end

