//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSToString.h"

@class NSString;

@interface MSOperationsLog : MSToString
{
    NSString *_logId;
    NSString *_title;
    NSString *_content;
    NSString *_address;
    NSString *_operateTime;
    NSString *_normType;
    NSString *_subType;
    NSString *_status;
}

@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *subType; // @synthesize subType=_subType;
@property(retain, nonatomic) NSString *normType; // @synthesize normType=_normType;
@property(retain, nonatomic) NSString *operateTime; // @synthesize operateTime=_operateTime;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *logId; // @synthesize logId=_logId;
- (void).cxx_destruct;

@end

