//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MSQUserInfoSupplementReq : NSObject
{
    NSString *_logonId;
    NSString *_userName;
    NSString *_payPassword;
    NSString *_clientID;
    NSString *_loginPassword;
}

@property(retain, nonatomic) NSString *loginPassword; // @synthesize loginPassword=_loginPassword;
@property(retain, nonatomic) NSString *clientID; // @synthesize clientID=_clientID;
@property(retain, nonatomic) NSString *payPassword; // @synthesize payPassword=_payPassword;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *logonId; // @synthesize logonId=_logonId;
- (void).cxx_destruct;

@end

