//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MSRpcCommonReq : NSObject
{
    NSString *_longonId;
}

@property(retain, nonatomic) NSString *longonId; // @synthesize longonId=_longonId;
- (void).cxx_destruct;

@end

