//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSToString.h"

@class NSString;

@interface MSSecurityLevel : MSToString
{
    int _score;
    NSString *_level;
    NSString *_memo;
}

@property(retain, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property(nonatomic) int score; // @synthesize score=_score;
@property(retain, nonatomic) NSString *level; // @synthesize level=_level;
- (void).cxx_destruct;

@end

