//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSRpcCommonRes.h"

@class NSString;

@interface MSSetMobilePayPwdRes : MSRpcCommonRes
{
    _Bool _mobileUser;
    NSString *_userStatus;
}

@property(retain, nonatomic) NSString *userStatus; // @synthesize userStatus=_userStatus;
@property(nonatomic) _Bool mobileUser; // @synthesize mobileUser=_mobileUser;
- (void).cxx_destruct;

@end

