//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSToString.h"

@class NSString;

@interface MSSecuritySettings : MSToString
{
    _Bool _certified;
    _Bool _mobileBinded;
    _Bool _setSecurityQA;
    _Bool _openedUKey;
    _Bool _openedDigitalCert;
    _Bool _openedDynamicPwd;
    _Bool _openedMobileOtp;
    _Bool _certifiedAndMobileBind;
    _Bool _setHeadPic;
    _Bool _setGesture;
    _Bool _setDeviceAuthentication;
    _Bool _openPush;
    NSString *_mobileBindNo;
    NSString *_userName;
}

@property(nonatomic) _Bool openPush; // @synthesize openPush=_openPush;
@property(nonatomic) _Bool setDeviceAuthentication; // @synthesize setDeviceAuthentication=_setDeviceAuthentication;
@property(nonatomic) _Bool setGesture; // @synthesize setGesture=_setGesture;
@property(nonatomic) _Bool setHeadPic; // @synthesize setHeadPic=_setHeadPic;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *mobileBindNo; // @synthesize mobileBindNo=_mobileBindNo;
@property(nonatomic) _Bool certifiedAndMobileBind; // @synthesize certifiedAndMobileBind=_certifiedAndMobileBind;
@property(nonatomic) _Bool openedMobileOtp; // @synthesize openedMobileOtp=_openedMobileOtp;
@property(nonatomic) _Bool openedDynamicPwd; // @synthesize openedDynamicPwd=_openedDynamicPwd;
@property(nonatomic) _Bool openedDigitalCert; // @synthesize openedDigitalCert=_openedDigitalCert;
@property(nonatomic) _Bool openedUKey; // @synthesize openedUKey=_openedUKey;
@property(nonatomic) _Bool setSecurityQA; // @synthesize setSecurityQA=_setSecurityQA;
@property(nonatomic) _Bool mobileBinded; // @synthesize mobileBinded=_mobileBinded;
@property(nonatomic) _Bool certified; // @synthesize certified=_certified;
- (void).cxx_destruct;

@end

