//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVTableRow.h"

@class NSString;

@interface MVFilmDetailCommentErrorRow : MVTableRow
{
    long long _errorType;
    NSString *_errorMessage;
}

@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(nonatomic) long long errorType; // @synthesize errorType=_errorType;
- (void).cxx_destruct;
- (void)actionClicked:(id)arg1;
- (double)cellHeight;
- (void)updateCell:(id)arg1 indexPath:(id)arg2;
- (id)cellForTableView:(id)arg1 indexPath:(id)arg2;
- (id)initWithCommentErrorType:(long long)arg1 errorMessage:(id)arg2;

@end

