//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSString;

@interface MVOrderTicketControl : UIView
{
    _Bool _isShowSalesGood;
    _Bool _alwaysGO;
    NSString *_showName;
    NSString *_cinema;
    NSString *_hall;
    NSString *_showTime;
    NSString *_showEndTime;
    NSString *_showVersion;
    NSString *_seatNames;
    NSString *_phoneNumber;
    double _ticketDetailHeight;
    NSArray *_specialSchedules;
}

+ (struct CGSize)sizeWithLable:(id)arg1;
+ (id)addLabel:(id)arg1 string:(id)arg2 size:(double)arg3 color:(unsigned int)arg4 isBold:(_Bool)arg5;
@property(copy, nonatomic) NSArray *specialSchedules; // @synthesize specialSchedules=_specialSchedules;
@property(nonatomic) _Bool alwaysGO; // @synthesize alwaysGO=_alwaysGO;
@property(nonatomic) _Bool isShowSalesGood; // @synthesize isShowSalesGood=_isShowSalesGood;
@property(nonatomic) double ticketDetailHeight; // @synthesize ticketDetailHeight=_ticketDetailHeight;
@property(copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(copy, nonatomic) NSString *seatNames; // @synthesize seatNames=_seatNames;
@property(copy, nonatomic) NSString *showVersion; // @synthesize showVersion=_showVersion;
@property(copy, nonatomic) NSString *showEndTime; // @synthesize showEndTime=_showEndTime;
@property(copy, nonatomic) NSString *showTime; // @synthesize showTime=_showTime;
@property(copy, nonatomic) NSString *hall; // @synthesize hall=_hall;
@property(copy, nonatomic) NSString *cinema; // @synthesize cinema=_cinema;
@property(copy, nonatomic) NSString *showName; // @synthesize showName=_showName;
- (void).cxx_destruct;
- (id)showTimeAttributeString:(id)arg1;
- (double)initTicketDetail;
- (void)updateFrame:(id)arg1 yPosition:(double)arg2;
- (void)initView;
- (id)initWithShowName:(id)arg1 cinema:(id)arg2 hall:(id)arg3 showTime:(id)arg4 showEndTime:(id)arg5 showVerion:(id)arg6 seatNames:(id)arg7 phoneNumber:(id)arg8 specialSchedules:(id)arg9 isShowSalesGood:(_Bool)arg10 alwaysGO:(_Bool)arg11;

@end

