//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVTableRow.h"

@class MVActivityModel;

@interface MVScheduleFilmActivityRow : MVTableRow
{
    _Bool _folded;
    MVActivityModel *_activityModel;
    unsigned long long _numberOfActivities;
}

@property(nonatomic) _Bool folded; // @synthesize folded=_folded;
@property(nonatomic) unsigned long long numberOfActivities; // @synthesize numberOfActivities=_numberOfActivities;
@property(retain, nonatomic) MVActivityModel *activityModel; // @synthesize activityModel=_activityModel;
- (void).cxx_destruct;
- (void)toggleActivity:(id)arg1;
- (double)cellHeight;
- (void)updateCell:(id)arg1 indexPath:(id)arg2;
- (id)cellForTableView:(id)arg1 indexPath:(id)arg2;
- (id)initWithActivityModel:(id)arg1;

@end

