//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVTableViewController.h"

#import "MVFilmListCollectionViewControllerDeleagte.h"
#import "UITableViewDelegate.h"

@class APExceptionView, MVActivityNoticeView, MVBannerModel, MVBluredBackgroundChanger, MVCinemaModel, MVFilmBannerRow, MVFilmHeaderView, MVFilmListCollectionPicker, MVScheduleBankActivityRow, MVScheduleBottomNoticeBar, MVScheduleCinemaInfoRow, MVScheduleCinemaInfoView, MVScheduleFilmActivityRow, MVScheduleListModel, MVScheduleLogicController, MVScheduleRow, MVScheduleSection, MVScheduleTopActivityView, MVSegmentControl, MVShowModel, MVTableSection, MVTableViewDataSource, NSArray, NSDate, NSDictionary, NSMutableArray, NSString, UIImage, UILabel, UIView;

@interface MVScheduleListViewController : MVTableViewController <UITableViewDelegate, MVFilmListCollectionViewControllerDeleagte>
{
    UILabel *closeTimeTipLabel_;
    MVScheduleSection *closeTimeSection_;
    MVScheduleSection *filmActivitySection_;
    MVTableViewDataSource *_listSource;
    MVFilmListCollectionPicker *_collectionViewController;
    UIView *_floatingView;
    MVBluredBackgroundChanger *_blurBackground;
    MVScheduleListModel *_scheduleListModel;
    MVFilmHeaderView *_filmHeader;
    MVSegmentControl *_segmentControl;
    MVScheduleSection *_segmentControlSection;
    MVScheduleRow *_segmentControlRow;
    MVScheduleSection *_generalTopSection;
    MVScheduleCinemaInfoRow *_cinemaInfoRow;
    MVScheduleRow *_filmHeaderRow;
    MVActivityNoticeView *_noticeView;
    MVScheduleRow *_noticeViewRow;
    _Bool _lastRefreshManual;
    MVScheduleLogicController *_logicController;
    _Bool _isDisplayFullActivityList;
    _Bool _setNeedsRefresh;
    MVScheduleCinemaInfoView *_cinemaInfoView;
    MVScheduleRow *_filmListRow;
    UIView *_tableViewIndicator;
    APExceptionView *_netErrorView;
    MVTableSection *_bannerBottomSection;
    MVFilmBannerRow *_bannerBottomRow;
    MVScheduleBottomNoticeBar *_bottomBar;
    _Bool _isLogged;
    _Bool _presaleRedeemMode;
    _Bool _isDisplayFullMcardActivityList;
    MVShowModel *_currentShowModel;
    MVCinemaModel *_currentCinemaModel;
    long long _mode;
    NSString *_activityId;
    NSDictionary *_showIdFilter;
    NSDictionary *_scheduleIdFilter;
    UIImage *_blurBackgroundImage;
    NSDate *_preSelectedDate;
    MVBannerModel *_noticeBannerModel;
    NSString *_presaleNoticeText;
    NSMutableArray *_mcardFoldableRows;
    NSMutableArray *_foldableRows;
    MVScheduleFilmActivityRow *_activityRowWithFoldButton;
    MVScheduleFilmActivityRow *_mcardActivityRowWithFoldButton;
    long long _selectedDayIndex;
    NSArray *_bankActivityArray;
    MVScheduleBankActivityRow *_bankActivityRow;
    MVScheduleTopActivityView *_cinemaActivityView;
}

@property(nonatomic) _Bool isDisplayFullMcardActivityList; // @synthesize isDisplayFullMcardActivityList=_isDisplayFullMcardActivityList;
@property(retain, nonatomic) MVScheduleTopActivityView *cinemaActivityView; // @synthesize cinemaActivityView=_cinemaActivityView;
@property(retain, nonatomic) MVScheduleBankActivityRow *bankActivityRow; // @synthesize bankActivityRow=_bankActivityRow;
@property(retain, nonatomic) NSArray *bankActivityArray; // @synthesize bankActivityArray=_bankActivityArray;
@property(nonatomic) long long selectedDayIndex; // @synthesize selectedDayIndex=_selectedDayIndex;
@property(nonatomic) __weak MVScheduleFilmActivityRow *mcardActivityRowWithFoldButton; // @synthesize mcardActivityRowWithFoldButton=_mcardActivityRowWithFoldButton;
@property(nonatomic) __weak MVScheduleFilmActivityRow *activityRowWithFoldButton; // @synthesize activityRowWithFoldButton=_activityRowWithFoldButton;
@property(retain, nonatomic) NSMutableArray *foldableRows; // @synthesize foldableRows=_foldableRows;
@property(retain, nonatomic) NSMutableArray *mcardFoldableRows; // @synthesize mcardFoldableRows=_mcardFoldableRows;
@property(retain, nonatomic) NSString *presaleNoticeText; // @synthesize presaleNoticeText=_presaleNoticeText;
@property(retain, nonatomic) MVBannerModel *noticeBannerModel; // @synthesize noticeBannerModel=_noticeBannerModel;
@property(retain, nonatomic) NSDate *preSelectedDate; // @synthesize preSelectedDate=_preSelectedDate;
@property(nonatomic) _Bool presaleRedeemMode; // @synthesize presaleRedeemMode=_presaleRedeemMode;
@property(retain, nonatomic) UIImage *blurBackgroundImage; // @synthesize blurBackgroundImage=_blurBackgroundImage;
@property(retain, nonatomic) NSDictionary *scheduleIdFilter; // @synthesize scheduleIdFilter=_scheduleIdFilter;
@property(retain, nonatomic) NSDictionary *showIdFilter; // @synthesize showIdFilter=_showIdFilter;
@property(retain, nonatomic) NSString *activityId; // @synthesize activityId=_activityId;
@property(readonly, nonatomic) long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) MVCinemaModel *currentCinemaModel; // @synthesize currentCinemaModel=_currentCinemaModel;
@property(retain, nonatomic) MVShowModel *currentShowModel; // @synthesize currentShowModel=_currentShowModel;
- (void).cxx_destruct;
- (id)deleteRepeatActivityWithArray:(id)arg1;
- (void)reloadScheduleIfNeeded:(id)arg1;
- (void)dealloc;
- (void)scheduleDateSelected:(id)arg1;
- (void)showNextScheduleDay:(id)arg1;
- (void)setSelectedDayIndex:(long long)arg1 forceUpdate:(_Bool)arg2 animated:(_Bool)arg3;
- (id)rowListFromModelArray:(id)arg1;
- (void)checkScrollLogic;
- (void)replaceCurrentSchedulesDataWithReponse:(id)arg1;
- (void)refreshBackgroundWithNewImage:(id)arg1;
- (void)refreshBackgroundWithBlurredImage:(id)arg1 animated:(_Bool)arg2;
- (void)collectionViewDidFinishLoadingFilmList:(id)arg1;
- (void)showWholeViewException:(id)arg1;
- (void)collectionViewDidErrorLoadingFilmList:(id)arg1;
- (void)collectionView:(id)arg1 tappedOnCenteredMovie:(id)arg2 atIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didScrollToMovie:(id)arg2;
- (void)collectionView:(id)arg1 didSelectMovie:(id)arg2 atIndexPath:(id)arg3;
- (void)triggerScheduleListRefresh;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)switchTransparentBarToTop;
- (id)findScrollIndicator;
- (void)_ensureView:(id)arg1 floatAfterOffset:(double)arg2;
- (void)hideCoverLoadingView;
- (void)didReceiveMemoryWarning;
- (void)initCollectionView;
- (void)refreshControlDidTriggerRefresh;
- (void)refreshControlDidTriggerRefreshManual:(_Bool)arg1;
- (void)updateFilmHeaderWithShowModel:(id)arg1;
- (void)resetDataSource;
- (void)didTapCinema:(id)arg1;
- (void)buildFilmListSection;
- (void)buildBottomGeneralSection;
- (void)didToggleActivityExpand:(id)arg1;
- (void)didToggleMcardActivityExpand:(id)arg1;
- (void)buildCinemaActivitySection;
- (id)buildFilmActivitySectionWithSchedule:(id)arg1;
- (void)buildBankActivityRow;
- (void)setNoticeText:(id)arg1;
- (void)fetchSchduleListNotice;
- (id)properNoticeText;
- (void)refreshNoticeText;
- (void)refreshFavButtonWithState:(_Bool)arg1;
- (void)updateFillerSectionHeight;
- (double)totalContentHeight;
- (void)goForMemberCardType:(id)arg1;
- (void)goForMemberCard:(id)arg1;
- (void)setupFavItem;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)closeScheduleNotice:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)gotoMovieDetail:(id)arg1;
- (void)gotoCinemaDetail:(id)arg1;
- (void)toggleFav:(id)arg1;
- (void)fetchBannerAndUpdateInterface;
- (_Bool)scrollOffsetAfterFilmHeaderBar;
- (double)topLayoutGuideImmovableOffset;
- (double)collectionViewHeight;
- (double)contentHeightAboveFloatingView;
- (double)noticeRowHeight;
- (id)initWithMode:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

