//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton;

@interface MYYellowButton : UIView
{
    UIButton *_mainButton;
    UIActivityIndicatorView *_indicatorView;
}

- (void).cxx_destruct;
- (void)stopAnimation;
- (void)startAnimation;
- (void)setTitle:(id)arg1;
- (void)layoutSubviews;
- (id)initWithSize:(struct CGSize)arg1 target:(id)arg2 andSelector:(SEL)arg3;

@end

