//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NPHealthKitRequestHandler : NSObject
{
}

- (id)stepCountService;
- (void)handleShowGuide:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)handleShouldShowGuide:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)handleWriteStepCountLog:(id)arg1 appId:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)handleQueryStepCount:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)handleRegisterStepCountAuthorization:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)handleHasStepCountAuth:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)handler:(id)arg1 context:(id)arg2 callback:(CDUnknownBlockType)arg3;

@end

