//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (DJSegInfo)
+ (struct _NSRange)getSegmentRange:(id)arg1 segmentUnit:(unsigned long long)arg2;
+ (unsigned long long)getMaxSegmentPos:(id)arg1;
+ (unsigned long long)getNeedUploadedTotalBytesWithSegInfo:(id)arg1;
+ (unsigned long long)getMaxSegmentPosWithSegInfo:(id)arg1;
+ (id)segmentInfoArray:(id)arg1;
@end

