//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EnvelopePrizeInfoPB.h"

@class NSString;

@interface NYEnvelopeBackModel : EnvelopePrizeInfoPB
{
    NSString *_prizeType;
    NSString *_blessingBagMsg;
    NSString *_blessingBagBtnName;
    NSString *_blessingBagUrl;
}

@property(retain, nonatomic) NSString *blessingBagUrl; // @synthesize blessingBagUrl=_blessingBagUrl;
@property(retain, nonatomic) NSString *blessingBagBtnName; // @synthesize blessingBagBtnName=_blessingBagBtnName;
@property(retain, nonatomic) NSString *blessingBagMsg; // @synthesize blessingBagMsg=_blessingBagMsg;
@property(retain, nonatomic) NSString *prizeType; // @synthesize prizeType=_prizeType;
- (void).cxx_destruct;

@end

