//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NYButton, NYFuCard, NYFuCardFuView, UIButton, UILabel;

@interface NYFuCardEmptyView : UIImageView
{
    UIImageView *_nameBackgroundView;
    NYFuCardFuView *_fuView;
    NYButton *_begButton;
    UILabel *_tipLabel;
    UIButton *_endbutton;
    NYFuCard *_card;
    id <NYFuCardEmptyViewDelegate> _delegate;
}

@property(nonatomic) __weak id <NYFuCardEmptyViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NYFuCard *card; // @synthesize card=_card;
- (void).cxx_destruct;
- (void)pressBegFrendButton;
- (void)layoutSubviews;
- (void)setupEndButton;
- (id)initWithFrame:(struct CGRect)arg1;

@end

