//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSTimer, NYMainSceneModel;

@interface NYMainSceneManager : NSObject
{
    long long async_onceToken;
    _Bool didNotifiedFirstChangeScene;
    NSMutableArray *_sectionScenes;
    NYMainSceneModel *_currentScene;
    double _lastEggTextTime;
    NSDate *_currentDate;
    NSDictionary *_RPC_triggerConfig;
    double _RPC_triggerTime;
    long long _badgeNumber;
    NSDictionary *_spannerKeyConfig;
    NSArray *_sceneConfigs;
    long long _touchCount;
    NSDate *_lastTriggerDate;
    NSTimer *_eventTimer;
}

+ (id)variableString:(id)arg1 withPlaceholder:(id)arg2;
+ (void)mainSceneTimerEvent;
@property(retain, nonatomic) NSTimer *eventTimer; // @synthesize eventTimer=_eventTimer;
@property(retain, nonatomic) NSDate *lastTriggerDate; // @synthesize lastTriggerDate=_lastTriggerDate;
@property(nonatomic) long long touchCount; // @synthesize touchCount=_touchCount;
@property(retain, nonatomic) NSArray *sceneConfigs; // @synthesize sceneConfigs=_sceneConfigs;
@property(retain, nonatomic) NSDictionary *spannerKeyConfig; // @synthesize spannerKeyConfig=_spannerKeyConfig;
@property(nonatomic) long long badgeNumber; // @synthesize badgeNumber=_badgeNumber;
@property(nonatomic) double RPC_triggerTime; // @synthesize RPC_triggerTime=_RPC_triggerTime;
@property(retain, nonatomic) NSDictionary *RPC_triggerConfig; // @synthesize RPC_triggerConfig=_RPC_triggerConfig;
@property(retain, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(nonatomic) double lastEggTextTime; // @synthesize lastEggTextTime=_lastEggTextTime;
@property(retain, nonatomic) NYMainSceneModel *currentScene; // @synthesize currentScene=_currentScene;
@property(retain, nonatomic) NSMutableArray *sectionScenes; // @synthesize sectionScenes=_sectionScenes;
- (void).cxx_destruct;
- (void)startTimerEvent:(double)arg1;
- (void)currentSceneDidInvalidate:(id)arg1;
- (void)scheduleSceneTimerEvent:(id)arg1;
- (double)triggerTime:(id)arg1;
- (void)triggerPrizeRPC:(CDUnknownBlockType)arg1;
- (id)sceneFromConfig:(id)arg1;
- (void)configServiceUpdated;
- (void)buildScenes;
- (void)reloadScene;
- (void)cancelAllTimebasedTasks;
- (void)dealloc;
- (id)init;

@end

