//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NYMainSceneModel, ShoopShoopRespPB;

@interface NYMainPopupModel : NSObject
{
    unsigned long long _popupType;
    NSString *_content;
    NSDictionary *_popupConfig;
    NYMainSceneModel *_currentScene;
    ShoopShoopRespPB *_rpcResp;
}

+ (id)popupGroupsFromConfig:(id)arg1;
@property(retain, nonatomic) ShoopShoopRespPB *rpcResp; // @synthesize rpcResp=_rpcResp;
@property(retain, nonatomic) NYMainSceneModel *currentScene; // @synthesize currentScene=_currentScene;
@property(retain, nonatomic) NSDictionary *popupConfig; // @synthesize popupConfig=_popupConfig;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) unsigned long long popupType; // @synthesize popupType=_popupType;
- (void).cxx_destruct;

@end

