//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTViewController.h"

#import "APSKLaunchpadDelegate.h"
#import "NYSchemeProtocol.h"

@class APCustomNavigationView, APNavPopview, APSKLaunchpad, AVAudioPlayer, NSMutableArray, NSOperationQueue, NSString, NYCountDownView, NYDotLabel, NYMainSceneManager, NYMainTipView, NYNetworkErrorView, NYPopupManager, UIButton, UIImageView, UILabel, UINavigationController, UIView;

@interface NYMainController : DTViewController <NYSchemeProtocol, APSKLaunchpadDelegate>
{
    long long updateEnvelopeOnceToken;
    _Bool _visible;
    NYMainSceneManager *_sceneManager;
    UIButton *_xiuxiuButton;
    UIImageView *_xiuxiuLogo;
    UIView *_borderWaveView;
    UIImageView *_mainTitleView;
    UILabel *_statusView;
    UIButton *_luckyEntryButton;
    NYDotLabel *_luckyBadgeLabel;
    NYNetworkErrorView *_networkErroView;
    APNavPopview *_navPopupView;
    APSKLaunchpad *_launchPad;
    NYMainTipView *_mainTipView;
    NYCountDownView *_mainCountDownView;
    NYPopupManager *_popupManager;
    AVAudioPlayer *_xiuPlayer;
    NSOperationQueue *_xiuPlayerQueue;
    NSMutableArray *_xiuWaveImageList;
    UINavigationController *_weakNavigationController;
    APCustomNavigationView *_navigationView;
}

+ (unsigned long long)canInitWithOptions:(id)arg1;
@property(retain, nonatomic) APCustomNavigationView *navigationView; // @synthesize navigationView=_navigationView;
@property(nonatomic) __weak UINavigationController *weakNavigationController; // @synthesize weakNavigationController=_weakNavigationController;
@property(retain, nonatomic) NSMutableArray *xiuWaveImageList; // @synthesize xiuWaveImageList=_xiuWaveImageList;
@property(retain, nonatomic) NSOperationQueue *xiuPlayerQueue; // @synthesize xiuPlayerQueue=_xiuPlayerQueue;
@property(retain, nonatomic) AVAudioPlayer *xiuPlayer; // @synthesize xiuPlayer=_xiuPlayer;
@property(retain, nonatomic) NYPopupManager *popupManager; // @synthesize popupManager=_popupManager;
@property(retain, nonatomic) NYCountDownView *mainCountDownView; // @synthesize mainCountDownView=_mainCountDownView;
@property(retain, nonatomic) NYMainTipView *mainTipView; // @synthesize mainTipView=_mainTipView;
@property(retain, nonatomic) APSKLaunchpad *launchPad; // @synthesize launchPad=_launchPad;
@property(retain, nonatomic) APNavPopview *navPopupView; // @synthesize navPopupView=_navPopupView;
@property(retain, nonatomic) NYNetworkErrorView *networkErroView; // @synthesize networkErroView=_networkErroView;
@property(retain, nonatomic) NYDotLabel *luckyBadgeLabel; // @synthesize luckyBadgeLabel=_luckyBadgeLabel;
@property(retain, nonatomic) UIButton *luckyEntryButton; // @synthesize luckyEntryButton=_luckyEntryButton;
@property(retain, nonatomic) UILabel *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) UIImageView *mainTitleView; // @synthesize mainTitleView=_mainTitleView;
@property(retain, nonatomic) UIView *borderWaveView; // @synthesize borderWaveView=_borderWaveView;
@property(retain, nonatomic) UIImageView *xiuxiuLogo; // @synthesize xiuxiuLogo=_xiuxiuLogo;
@property(retain, nonatomic) UIButton *xiuxiuButton; // @synthesize xiuxiuButton=_xiuxiuButton;
@property(retain, nonatomic) NYMainSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(nonatomic) _Bool visible; // @synthesize visible=_visible;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)addMotionEffectForView:(id)arg1 relativeValue:(double)arg2;
- (id)entryButtonWithImage:(id)arg1 titleText:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)loadConfigService;
- (void)sublayersChanged;
- (void)observeSubviewsChange;
- (void)registerPopupClasses;
- (long long)customStatusBarStytle;
- (id)customNavigationBar;
- (_Bool)autohideNavigationBar;
- (void)viewWillDestroy;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (void)updateLuckyEntryBadge:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)popupEnvelopeEnding:(id)arg1;
- (void)currentSceneDidInvalidate:(id)arg1;
- (void)currentSceneDidChange:(id)arg1;
- (void)timerEventUpdate:(id)arg1;
- (void)microApplicationWillTerminate:(id)arg1;
- (void)microApplicationWillStart:(id)arg1;
- (void)addNotification:(id)arg1 selector:(SEL)arg2;
- (void)observeNotifications;
- (void)animateBorderWaveView;
- (void)setupAutolayout;
- (void)viewDidLayoutSubviews;
- (void)update_statusText;
- (void)update_envelopeNumber:(id)arg1 withHeaderName:(id)arg2;
- (void)animateChangeNumberString:(long long)arg1 animated:(_Bool)arg2;
- (id)gatewayHeaders:(id)arg1 orError:(id)arg2;
- (void)play_xiuSound;
- (id)createWaveView;
- (void)updateNoInteractiveStatus;
- (void)animateWaveView;
- (double)animateIntervalControl:(double)arg1;
- (void)popupRandEggs:(id)arg1;
- (void)sendRPC:(long long)arg1;
- (void)actionLuckyButtonTouched;
- (void)actionXiuxiuButtonTouched;
- (void)actionXiuxiuButtonTouchUp;
- (void)actionXiuxiuButtonBounce;
- (void)actionOpenRules;
- (void)actionShareNew:(id)arg1;
- (void)actionMore;
- (void)bindActions;
- (id)createShareMessageForChannel:(id)arg1;
- (void)shareToChannel:(id)arg1;
- (void)sharingLaunchpad:(id)arg1 didSelectChannel:(id)arg2;
- (void)onShareTapped:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

