//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NYFuBackgroundView, UIImage, UIImageView;

@interface NYPromptBgView : UIView
{
    UIImage *_image;
    NYFuBackgroundView *_backImageView1;
    UIImageView *_backImageView2;
}

@property(retain, nonatomic) UIImageView *backImageView2; // @synthesize backImageView2=_backImageView2;
@property(retain, nonatomic) NYFuBackgroundView *backImageView1; // @synthesize backImageView1=_backImageView1;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)setupCustomConstrains;
- (void)setupCustomView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

