//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BlessingLeaderboardVoPB, NYAreaExpandButton, UIImageView, UILabel, UIView;

@interface NYRandomFuTopListCell : UITableViewCell
{
    id <NYRandomFuTopListCellDelegate> _cellDelegate;
    BlessingLeaderboardVoPB *_topListData;
    UIImageView *_iconView;
    UILabel *_nameLabel;
    UILabel *_memoLabel;
    UILabel *_numLabel;
    UIImageView *_fuIcon;
    NYAreaExpandButton *_takeButton;
    UIView *_colorBackgroundView;
}

@property(retain, nonatomic) UIView *colorBackgroundView; // @synthesize colorBackgroundView=_colorBackgroundView;
@property(retain, nonatomic) NYAreaExpandButton *takeButton; // @synthesize takeButton=_takeButton;
@property(retain, nonatomic) UIImageView *fuIcon; // @synthesize fuIcon=_fuIcon;
@property(retain, nonatomic) UILabel *numLabel; // @synthesize numLabel=_numLabel;
@property(retain, nonatomic) UILabel *memoLabel; // @synthesize memoLabel=_memoLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) BlessingLeaderboardVoPB *topListData; // @synthesize topListData=_topListData;
@property(nonatomic) __weak id <NYRandomFuTopListCellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
- (void).cxx_destruct;
- (void)pressTakeButton;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

