//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSString, NYAreaExpandButton, REScratchView, UILabel;

@interface NYScratchCardView : UIImageView
{
    REScratchView *_scratchView;
    UIImageView *_scratchMaskView;
    NYAreaExpandButton *_splitButton;
    UILabel *_splitTipLabel;
    _Bool _scratched;
    _Bool _winning;
    _Bool _splited;
    NSString *_prizeBtnName;
    NSString *_prizeName;
    NSString *_prizeDesc;
    NSString *_prizeURL;
    NSString *_unPrizeTitle;
    NSString *_unPrizeDesc;
    id <NYScratchCardViewDelegate> _delegate;
    UIImageView *_successContentView;
    UIImageView *_failContentView;
}

@property(retain, nonatomic) UIImageView *failContentView; // @synthesize failContentView=_failContentView;
@property(retain, nonatomic) UIImageView *successContentView; // @synthesize successContentView=_successContentView;
@property(nonatomic) __weak id <NYScratchCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *unPrizeDesc; // @synthesize unPrizeDesc=_unPrizeDesc;
@property(copy, nonatomic) NSString *unPrizeTitle; // @synthesize unPrizeTitle=_unPrizeTitle;
@property(copy, nonatomic) NSString *prizeURL; // @synthesize prizeURL=_prizeURL;
@property(copy, nonatomic) NSString *prizeDesc; // @synthesize prizeDesc=_prizeDesc;
@property(copy, nonatomic) NSString *prizeName; // @synthesize prizeName=_prizeName;
@property(copy, nonatomic) NSString *prizeBtnName; // @synthesize prizeBtnName=_prizeBtnName;
@property(nonatomic) _Bool splited; // @synthesize splited=_splited;
@property(nonatomic) _Bool winning; // @synthesize winning=_winning;
@property(nonatomic) _Bool scratched; // @synthesize scratched=_scratched;
- (void).cxx_destruct;
- (void)pressPrizeActionButton;
- (id)scratchContentView;
- (void)pressSplitButton;
- (void)afterSplit;
- (void)spliting;
- (void)beforeSplit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

