//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NYSchemeProtocol.h"

@class DTRpcAsyncCaller, DTViewController, NSString;

@interface NYSchemeBaseController : NSObject <NYSchemeProtocol>
{
    NSString *_appId;
    DTViewController *_lastVCInProgress;
    DTRpcAsyncCaller *_asyncCaller;
    id _selfRetain;
}

+ (unsigned long long)canInitWithOptions:(id)arg1;
@property(retain, nonatomic) id selfRetain; // @synthesize selfRetain=_selfRetain;
@property(retain, nonatomic) DTRpcAsyncCaller *asyncCaller; // @synthesize asyncCaller=_asyncCaller;
@property(retain, nonatomic) DTViewController *lastVCInProgress; // @synthesize lastVCInProgress=_lastVCInProgress;
- (void).cxx_destruct;
- (void)appWillTerminate;
- (void)doNewAppWillStart:(id)arg1;
- (void)checkIfExitApp;
- (void)cancelRpc;
- (void)releaseSelf;
- (void)keepSelf;
- (void)dealloc;
- (id)initWithOptions:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

