//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NYUtils : NSObject
{
}

+ (void)voiceOverOnView:(id)arg1;
+ (void)handleCardNotExistError:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)openLuckeyListPage;
+ (id)navControllerForAppId:(id)arg1;
+ (id)formatErrorTip:(id)arg1;
+ (id)askFuCardRoute:(id)arg1;
+ (id)formatNumberByThreePos:(id)arg1;
+ (id)urlAppend:(id)arg1 andParams:(id)arg2;
+ (_Bool)isValidArray:(id)arg1;
+ (_Bool)isValidUrlString:(id)arg1;
+ (_Bool)isValidString:(id)arg1;
+ (id)appId;
+ (_Bool)isMarkXiuGot:(id)arg1;
+ (void)markXiuEGot:(id)arg1;
+ (id)fuCardShareThumb:(id)arg1 defaultLogo:(id)arg2;
+ (id)currentUser;
+ (void)openLinkUrl:(id)arg1 withParams:(id)arg2;
+ (void)openLinkUrl:(id)arg1;
+ (id)appendAppVersionForScheme:(id)arg1;
+ (void)playVideoWithId:(id)arg1 delegate:(id)arg2;
+ (void)unFollowPublicId:(id)arg1;
+ (_Bool)userFollowPublicId:(id)arg1;
+ (id)encodeUrl:(id)arg1;
+ (id)receiverType:(id)arg1;
+ (void)writeLogWithActionId:(id)arg1 extParams:(id)arg2 seed:(id)arg3;

@end

