//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NYWarmPopupView.h"

@class UIButton, UIImageView, UIView;

@interface NYWarmImagePopupView : NYWarmPopupView
{
    UIImageView *_imageView;
    UIButton *_videoPlayButton;
    UIView *_videoMaskView;
}

@property(retain, nonatomic) UIView *videoMaskView; // @synthesize videoMaskView=_videoMaskView;
@property(retain, nonatomic) UIButton *videoPlayButton; // @synthesize videoPlayButton=_videoPlayButton;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)buildCustomConstrains;
- (void)setupCustomViews;
- (void)setupContent;

@end

