//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OViewController.h"

#import "O2OCDPAdapterPromotionProtocol.h"
#import "O2OCommonSchemeProtocol.h"

@class APResultPageView, CDPSpaceView, NSAttributedString, NSMutableArray, NSString, O2OMyOrderListViewController, UILabel, UIScrollView, UIView;

@interface O2OCommentSuccessController : O2OViewController <O2OCDPAdapterPromotionProtocol, O2OCommonSchemeProtocol>
{
    _Bool _showToBeCommented;
    _Bool _didShowModel;
    UIScrollView *_scrollView;
    NSMutableArray *_barButtonItems;
    APResultPageView *_resultPage;
    UIView *_seperation;
    CDPSpaceView *_cdpView;
    UILabel *_tipLabel;
    O2OMyOrderListViewController *_toBeCommentedController;
    NSAttributedString *_aTipText;
}

+ (unsigned long long)canInitWithScheme:(id)arg1;
@property(nonatomic) _Bool didShowModel; // @synthesize didShowModel=_didShowModel;
@property(nonatomic) _Bool showToBeCommented; // @synthesize showToBeCommented=_showToBeCommented;
@property(copy, nonatomic) NSAttributedString *aTipText; // @synthesize aTipText=_aTipText;
@property(retain, nonatomic) O2OMyOrderListViewController *toBeCommentedController; // @synthesize toBeCommentedController=_toBeCommentedController;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) CDPSpaceView *cdpView; // @synthesize cdpView=_cdpView;
@property(retain, nonatomic) UIView *seperation; // @synthesize seperation=_seperation;
@property(retain, nonatomic) APResultPageView *resultPage; // @synthesize resultPage=_resultPage;
@property(retain, nonatomic) NSMutableArray *barButtonItems; // @synthesize barButtonItems=_barButtonItems;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)promotionViewDidFinishLoading:(id)arg1 spaceCode:(id)arg2;
- (void)promitionEnd;
- (void)promotionStart;
- (id)pageSpm;
- (void)goMyCommentAction;
- (void)close;
- (void)dealloc;
- (id)convertTipText:(id)arg1;
- (void)layout;
- (void)createSubViews;
- (id)initWithTipText:(id)arg1 showToBeCommented:(_Bool)arg2;
- (id)initWithScheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

