//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, O2OCDPSearchHotWord;

@interface O2OCDPSearchSpaceInfo : NSObject
{
    NSMutableArray *_spaceInfos;
    O2OCDPSearchHotWord *_hotWord;
}

@property(retain, nonatomic) O2OCDPSearchHotWord *hotWord; // @synthesize hotWord=_hotWord;
@property(retain, nonatomic) NSMutableArray *spaceInfos; // @synthesize spaceInfos=_spaceInfos;
- (void).cxx_destruct;

@end

