//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface O2OCommonSchemeManager : NSObject
{
}

+ (id)validViewControllerWithOptions:(id)arg1;
+ (_Bool)performSchemeRoutingWithOptions:(id)arg1 andAppId:(id)arg2;
+ (void)unregisterAll;
+ (void)unregisterClass:(Class)arg1;
+ (unsigned long long)registeredClassListCount;
+ (void)registerClass:(Class)arg1;

@end

