//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSString;

@interface O2OFilterTagItem : NSObject
{
    _Bool _isFocused;
    NSString *_text;
    NSIndexPath *_indexPath;
}

+ (id)parseWithMenuInfo:(id)arg1;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) _Bool isFocused; // @synthesize isFocused=_isFocused;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;

@end

