//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface O2OLikeCommentRequest : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasCommentId;
    _Bool _hasLikeCommentOption;
    _Bool _hasShopId;
    _Bool _likeCommentOption;
    NSString *_commentId;
    NSString *_shopId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
@property(nonatomic) _Bool likeCommentOption; // @synthesize likeCommentOption=_likeCommentOption;
@property(retain, nonatomic) NSString *commentId; // @synthesize commentId=_commentId;
@property(readonly) _Bool hasShopId; // @synthesize hasShopId=_hasShopId;
@property(readonly) _Bool hasLikeCommentOption; // @synthesize hasLikeCommentOption=_hasLikeCommentOption;
@property(readonly) _Bool hasCommentId; // @synthesize hasCommentId=_hasCommentId;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

