//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VZListItem.h"

@class MOBILECSAOrderExtendInfo, NSString;

@interface O2OMyOrderListItem : VZListItem
{
    _Bool _inCommentSuccess;
    int _isAlreadyComment;
    NSString *_orderId;
    NSString *_shopId;
    NSString *_shopLogo;
    NSString *_shopName;
    NSString *_orderConsumeAmountText;
    NSString *_orderSaveAmountText;
    long long _orderCreateDate;
    NSString *_endTime;
    NSString *_orderDetailUrl;
    MOBILECSAOrderExtendInfo *_orderExtendInfo;
    NSString *_orderBizType;
    NSString *_orderCreateDateString;
}

@property(retain, nonatomic) NSString *orderCreateDateString; // @synthesize orderCreateDateString=_orderCreateDateString;
@property(retain, nonatomic) NSString *orderBizType; // @synthesize orderBizType=_orderBizType;
@property(retain, nonatomic) MOBILECSAOrderExtendInfo *orderExtendInfo; // @synthesize orderExtendInfo=_orderExtendInfo;
@property(retain, nonatomic) NSString *orderDetailUrl; // @synthesize orderDetailUrl=_orderDetailUrl;
@property(retain, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(nonatomic) int isAlreadyComment; // @synthesize isAlreadyComment=_isAlreadyComment;
@property(nonatomic) long long orderCreateDate; // @synthesize orderCreateDate=_orderCreateDate;
@property(retain, nonatomic) NSString *orderSaveAmountText; // @synthesize orderSaveAmountText=_orderSaveAmountText;
@property(retain, nonatomic) NSString *orderConsumeAmountText; // @synthesize orderConsumeAmountText=_orderConsumeAmountText;
@property(retain, nonatomic) NSString *shopName; // @synthesize shopName=_shopName;
@property(retain, nonatomic) NSString *shopLogo; // @synthesize shopLogo=_shopLogo;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
@property(nonatomic) _Bool inCommentSuccess; // @synthesize inCommentSuccess=_inCommentSuccess;
- (void).cxx_destruct;

@end

