//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OMerchantCommonItem.h"

@class NSArray, NSDictionary, NSString;

@interface O2OMerchantNameItem : O2OMerchantCommonItem
{
    _Bool _hideComment;
    _Bool _taxiDiscount;
    NSString *_shopName;
    NSString *_averagePrice;
    NSString *_address;
    NSString *_mapUrl;
    NSArray *_telNos;
    NSString *_telNosStr;
    NSString *_tradeDesc;
    NSString *_taxiUrl;
    double _star;
    NSString *_score;
    NSDictionary *_monitorDic;
    NSString *_cuisineStyle;
    double _addressHeight;
    double _nameHeight;
}

+ (id)parseItemFromDic:(id)arg1 commonDic:(id)arg2 vc:(id)arg3;
@property(nonatomic) double nameHeight; // @synthesize nameHeight=_nameHeight;
@property(nonatomic) double addressHeight; // @synthesize addressHeight=_addressHeight;
@property(retain, nonatomic) NSString *cuisineStyle; // @synthesize cuisineStyle=_cuisineStyle;
@property(retain, nonatomic) NSDictionary *monitorDic; // @synthesize monitorDic=_monitorDic;
@property(retain, nonatomic) NSString *score; // @synthesize score=_score;
@property(nonatomic) _Bool taxiDiscount; // @synthesize taxiDiscount=_taxiDiscount;
@property(nonatomic) double star; // @synthesize star=_star;
@property(retain, nonatomic) NSString *taxiUrl; // @synthesize taxiUrl=_taxiUrl;
@property(retain, nonatomic) NSString *tradeDesc; // @synthesize tradeDesc=_tradeDesc;
@property(retain, nonatomic) NSString *telNosStr; // @synthesize telNosStr=_telNosStr;
@property(retain, nonatomic) NSArray *telNos; // @synthesize telNos=_telNos;
@property(retain, nonatomic) NSString *mapUrl; // @synthesize mapUrl=_mapUrl;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *averagePrice; // @synthesize averagePrice=_averagePrice;
@property(retain, nonatomic) NSString *shopName; // @synthesize shopName=_shopName;
@property(nonatomic) _Bool hideComment; // @synthesize hideComment=_hideComment;
- (void).cxx_destruct;
- (float)getItemHeight;

@end

