//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OMerchantCommonCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface O2OMerchantNameCell : O2OMerchantCommonCell
{
    UILabel *_nameLabel;
    UIImageView *_starViewGrey;
    UIImageView *_starViewYellow;
    UIImageView *_taxiDiscountImageView;
    UIButton *_taxiBtn;
    UIView *_addressTopLine;
    UIButton *_addressButton;
    UILabel *_addressLabel;
    UIView *_phoneTopLine;
    UIButton *_phoneButton;
    UILabel *_phoneLabel;
    UILabel *_scoreLabel;
    UILabel *_tradeDescLabel;
    UILabel *_cuisineStyleLabel;
}

- (void).cxx_destruct;
- (void)taxiView:(id)arg1;
- (void)addressMapView;
- (void)phone:(id)arg1;
- (void)setItem:(id)arg1;
- (void)copyaddress:(id)arg1;
- (void)showAddressCopyMenu:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

