//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol O2ONewTagListViewDelegate <NSObject>

@optional
- (void)onExceedMaxSelectedTags:(long long)arg1;
- (void)onNormalTagClicked:(id)arg1;
- (void)onDelTagClicked:(id)arg1;
- (void)onAddTagClicked;
- (void)onMoreTagClicked;
@end

