//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VZCollectionCell.h"

#import "VZFNodeHostingView.h"
#import "VZFNodeProvider.h"

@class NSString, O2OPopEyeCardView;

@interface O2OPopEyeBaseCardCell : VZCollectionCell <VZFNodeProvider, VZFNodeHostingView>
{
    O2OPopEyeCardView *_containterView;
}

+ (id)nodeForItem:(id)arg1 Store:(id)arg2 Context:(id)arg3;
+ (id)collectionView:(id)arg1 cellForRowAtIndexPath:(id)arg2 andItem:(id)arg3;
+ (id)cellReuseIdentifier;
@property(retain, nonatomic) O2OPopEyeCardView *containterView; // @synthesize containterView=_containterView;
- (void).cxx_destruct;
- (void)stopInfoCardAnimation;
- (void)stopImageCardAnimation;
- (void)startInfoCardAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)startImageCardAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)showEmptyView;
- (void)updateWithCellItem:(id)arg1 atIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

