//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OPResultHeaderView.h"

@class UILabel;

@interface O2OPRefundResultHeaderView : O2OPResultHeaderView
{
    UILabel *_amountLabel;
    UILabel *_couponTipsLabel;
    UILabel *_tipsLabel;
}

+ (float)cellHeightWithModel:(id)arg1;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UILabel *couponTipsLabel; // @synthesize couponTipsLabel=_couponTipsLabel;
@property(retain, nonatomic) UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setModel:(id)arg1;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

