//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "O2OPageMenuItemDelegate.h"

@class NSMutableArray, NSString, O2OPageMenuItem, O2OPageMenuProgressView, UIColor, UIScrollView;

@interface O2OPageMenuView : UIView <O2OPageMenuItemDelegate>
{
    _Bool _hasImage;
    id <O2OPageMenuViewDelegate> _delegate;
    NSMutableArray *_titles;
    NSMutableArray *_selectedImages;
    NSMutableArray *_normalImages;
    double _titleOnlyOneSize;
    double _titleNormalSize;
    double _titleSelectedSize;
    UIColor *_titleSelectedColor;
    UIColor *_titleNormalColor;
    double _itemMargin;
    double _imageMargin;
    NSMutableArray *_itemWidths;
    UIColor *_lineColor;
    double _lineHeight;
    UIColor *_menuBackgroundColor;
    unsigned long long _style;
    unsigned long long _animationStyle;
    UIScrollView *_scrollView;
    NSMutableArray *_frames;
    O2OPageMenuProgressView *_progressView;
    O2OPageMenuItem *_currentItem;
    UIView *_pageOneMenuView;
    NSString *_spm;
    struct CGSize _imageSize;
}

@property(retain, nonatomic) NSString *spm; // @synthesize spm=_spm;
@property(nonatomic, getter=hasImage) _Bool hasImage; // @synthesize hasImage=_hasImage;
@property(retain, nonatomic) UIView *pageOneMenuView; // @synthesize pageOneMenuView=_pageOneMenuView;
@property(nonatomic) __weak O2OPageMenuItem *currentItem; // @synthesize currentItem=_currentItem;
@property(nonatomic) __weak O2OPageMenuProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSMutableArray *frames; // @synthesize frames=_frames;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) unsigned long long animationStyle; // @synthesize animationStyle=_animationStyle;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIColor *menuBackgroundColor; // @synthesize menuBackgroundColor=_menuBackgroundColor;
@property(nonatomic) double lineHeight; // @synthesize lineHeight=_lineHeight;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(copy, nonatomic) NSMutableArray *itemWidths; // @synthesize itemWidths=_itemWidths;
@property(nonatomic) double imageMargin; // @synthesize imageMargin=_imageMargin;
@property(nonatomic) double itemMargin; // @synthesize itemMargin=_itemMargin;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(retain, nonatomic) UIColor *titleNormalColor; // @synthesize titleNormalColor=_titleNormalColor;
@property(retain, nonatomic) UIColor *titleSelectedColor; // @synthesize titleSelectedColor=_titleSelectedColor;
@property(nonatomic) double titleSelectedSize; // @synthesize titleSelectedSize=_titleSelectedSize;
@property(nonatomic) double titleNormalSize; // @synthesize titleNormalSize=_titleNormalSize;
@property(nonatomic) double titleOnlyOneSize; // @synthesize titleOnlyOneSize=_titleOnlyOneSize;
@property(copy, nonatomic) NSMutableArray *normalImages; // @synthesize normalImages=_normalImages;
@property(copy, nonatomic) NSMutableArray *selectedImages; // @synthesize selectedImages=_selectedImages;
@property(copy, nonatomic) NSMutableArray *titles; // @synthesize titles=_titles;
@property(nonatomic) __weak id <O2OPageMenuViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didSelectPageMenuItem:(id)arg1;
- (void)refreshSelectedItemPosition2CenterWithAnimation:(_Bool)arg1;
- (void)refreshSelectedItemPosition2Center;
- (void)selectItemAtPosition:(double)arg1;
- (void)scrollToProgress:(double)arg1 willDecelerate:(_Bool)arg2;
- (void)resetProgressView;
- (void)addProgressView;
- (double)calcuteItemWidth:(long long)arg1;
- (void)calcuteItemFrames;
- (void)addPageMenuItems;
- (void)resetMenuView;
- (void)addScollView;
- (void)addOnlyOneItemView;
- (void)initMenuStyleWithConfig:(id)arg1;
- (void)initMenuStyle;
- (void)setPageMenuTitles:(id)arg1;
- (void)setTitleNormalColor:(id)arg1 selectedColor:(id)arg2;
- (void)setTitleNormalSize:(double)arg1 selectedSize:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1 titles:(id)arg2 spm:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 titles:(id)arg2 normalImages:(id)arg3 selectedImages:(id)arg4 spm:(id)arg5;
- (id)initWithFrame:(struct CGRect)arg1 titles:(id)arg2 normalImages:(id)arg3 selectedImages:(id)arg4 spm:(id)arg5 configDic:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

