//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "O2OStarViewDelegate.h"

@class NSDictionary, NSString, O2OStarView, UILabel, UIView;

@interface O2OPResultStarViewTableViewCell : UITableViewCell <O2OStarViewDelegate>
{
    NSDictionary *_comment;
    UIView *_promotionFlag;
    CDUnknownBlockType _rating;
    UILabel *_titleView;
    O2OStarView *_starView;
    UIView *_lineView;
}

@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) O2OStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(copy, nonatomic) CDUnknownBlockType rating; // @synthesize rating=_rating;
@property(retain, nonatomic) UIView *promotionFlag; // @synthesize promotionFlag=_promotionFlag;
@property(retain, nonatomic) NSDictionary *comment; // @synthesize comment=_comment;
- (void).cxx_destruct;
- (void)ratingClickEnd:(float)arg1;
- (void)tapGestureEnded:(id)arg1;
- (void)panGestureEnded:(id)arg1;
- (void)starView:(id)arg1 scoreDidChange:(double)arg2;
- (void)updateStarView;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

