//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class O2OPResultModel, UIButton, UIImageView, UILabel;

@interface O2OPResultHeaderView : UIView
{
    O2OPResultModel *_model;
    CDUnknownBlockType _closeClicked;
    UIImageView *_iconView;
    UILabel *_resultDescLabel;
    UIButton *_closeBtn;
    UIView *_lineView;
}

@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UILabel *resultDescLabel; // @synthesize resultDescLabel=_resultDescLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(copy, nonatomic) CDUnknownBlockType closeClicked; // @synthesize closeClicked=_closeClicked;
@property(retain, nonatomic) O2OPResultModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)close;
- (void)initBaseView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

