//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VZListViewDelegate.h"

@interface O2OSearchResultViewDelegate : VZListViewDelegate
{
}

+ (long long)linesOfContent:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)createSearchSectionHeaderViewWithTitle:(id)arg1 tableView:(id)arg2 section:(long long)arg3;
- (id)createEmptySectionHeaderViewWithSize:(struct CGSize)arg1 title:(id)arg2;
- (id)createMRPSectionHeaderViewWithTitle:(id)arg1 tableView:(id)arg2 section:(long long)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;

@end

