//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OMistModel.h"

@class NSArray, NSString, O2OListViewController, O2OSearchModelCommonParams;

@interface O2OSearchResultListModel : O2OMistModel
{
    _Bool _isLoadOrLoadMore;
    long long _asyncSwitch;
    id <O2OSearchResultListModelDelegate> _searchDelegate;
    O2OListViewController *_vc;
    O2OSearchModelCommonParams *_commonParams;
    NSArray *_menuGroups;
    NSString *_title;
    NSString *_tab;
    NSString *_context;
    NSArray *_hiddenSections;
}

@property(copy, nonatomic) NSArray *hiddenSections; // @synthesize hiddenSections=_hiddenSections;
@property(nonatomic) _Bool isLoadOrLoadMore; // @synthesize isLoadOrLoadMore=_isLoadOrLoadMore;
@property(readonly, nonatomic) NSString *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSString *tab; // @synthesize tab=_tab;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSArray *menuGroups; // @synthesize menuGroups=_menuGroups;
@property(copy, nonatomic) O2OSearchModelCommonParams *commonParams; // @synthesize commonParams=_commonParams;
@property(nonatomic) __weak O2OListViewController *vc; // @synthesize vc=_vc;
@property(nonatomic) __weak id <O2OSearchResultListModelDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
@property(nonatomic) long long asyncSwitch; // @synthesize asyncSwitch=_asyncSwitch;
- (void).cxx_destruct;
- (id)operationType;
- (id)templateConfig;
- (_Bool)handleTemplatesCompletion:(id)arg1 failedItems:(id)arg2 err:(id)arg3;
- (void)receiveNewSection:(id)arg1;
- (_Bool)raise1002Exception;
- (_Bool)hasMore;
- (void)handleMallIgnoreGroup:(id)arg1;
- (id)responseObjects:(id)arg1;
- (id)parseHits:(id)arg1 groupId:(id)arg2 withDtLogMonitor:(id)arg3 resResponse:(id)arg4 tplId:(id)arg5 tplJson:(id)arg6 actionParams:(id)arg7;
- (SEL)selectorNameForRPCService;
- (Class)RPCServiceClass;
- (Class)RPCResponseClass;
- (Class)RPCRequestClass;
- (long long)pageSize;
- (id)rpcRequest;
- (struct requestConfig)requestConfig;
- (_Bool)hasCacheData;
- (id)cacheKey;
- (_Bool)loadMore;
- (void)load;
- (void)reset;
- (long long)pageStart;
- (void)addHiddenSections:(id)arg1;
- (id)mainKey;
- (_Bool)loadWithCache:(id)arg1;
- (_Bool)tryToRecoverHiddenSections;
- (_Bool)unfoldSection:(unsigned long long)arg1;

@end

