//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class O2OSearchResultListVC, O2OSegmentedControl;

@protocol O2OSerachResultListVCDelegate <NSObject>
- (O2OSegmentedControl *)searchResultListVCGetO2OSegmentedControl:(O2OSearchResultListVC *)arg1;
@end

