//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OHTTPListModel.h"

#import "O2OSearchResultFilterModelDelegate.h"
#import "O2OSearchResultListModelDelegate.h"
#import "VZModelDelegate.h"

@class NSArray, NSString, O2OSearchModelCommonParams, O2OSearchResultFilterModel, O2OSearchResultListModel;

@interface O2OSearchModel : O2OHTTPListModel <VZModelDelegate, O2OSearchResultListModelDelegate, O2OSearchResultFilterModelDelegate>
{
    _Bool _forceLoadAll;
    _Bool _isLoadOrLoadMore;
    _Bool _isUseCache;
    _Bool _isLoadAll;
    id <O2OSearchModelDelegate> _searchDelegate;
    O2OSearchModelCommonParams *_commonParams;
    NSArray *_menuGroups;
    NSString *_title;
    NSString *_tab;
    NSString *_context;
    NSString *_errorName;
    long long _failCode;
    O2OSearchResultFilterModel *_filterModel;
    O2OSearchResultListModel *_resultModel;
    double _lastLoadAllTime;
    NSArray *_hiddenSections;
    long long _loadingCount;
    double _rpcStartTime;
}

@property(nonatomic) double rpcStartTime; // @synthesize rpcStartTime=_rpcStartTime;
@property(nonatomic) long long loadingCount; // @synthesize loadingCount=_loadingCount;
@property(copy, nonatomic) NSArray *hiddenSections; // @synthesize hiddenSections=_hiddenSections;
@property(nonatomic) _Bool isLoadAll; // @synthesize isLoadAll=_isLoadAll;
@property(nonatomic) _Bool isUseCache; // @synthesize isUseCache=_isUseCache;
@property(nonatomic) double lastLoadAllTime; // @synthesize lastLoadAllTime=_lastLoadAllTime;
@property(retain, nonatomic) O2OSearchResultListModel *resultModel; // @synthesize resultModel=_resultModel;
@property(retain, nonatomic) O2OSearchResultFilterModel *filterModel; // @synthesize filterModel=_filterModel;
@property(readonly, nonatomic) long long failCode; // @synthesize failCode=_failCode;
@property(readonly, nonatomic) NSString *errorName; // @synthesize errorName=_errorName;
@property(readonly, nonatomic) NSString *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSString *tab; // @synthesize tab=_tab;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSArray *menuGroups; // @synthesize menuGroups=_menuGroups;
@property(nonatomic) _Bool isLoadOrLoadMore; // @synthesize isLoadOrLoadMore=_isLoadOrLoadMore;
@property(retain, nonatomic) O2OSearchModelCommonParams *commonParams; // @synthesize commonParams=_commonParams;
@property(nonatomic) _Bool forceLoadAll; // @synthesize forceLoadAll=_forceLoadAll;
@property(nonatomic) __weak id <O2OSearchModelDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
- (void).cxx_destruct;
- (_Bool)resultModelShouldRaise1002Exception:(id)arg1;
- (_Bool)modelShouldRaise1002Exception:(id)arg1;
- (_Bool)raise1002Exception;
- (id)operationType;
- (_Bool)isResponseObjectFromCache;
- (void)setObjects:(id)arg1;
- (id)objects;
- (void)setNeedLoadAll:(_Bool)arg1;
- (_Bool)needLoadAll;
- (_Bool)canLoadMore;
- (_Bool)hasMore;
- (_Bool)loadMore;
- (void)modelWillLoadMore:(id)arg1;
- (void)reset:(_Bool)arg1;
- (void)reset;
- (void)modelDidFail:(id)arg1 withError:(id)arg2;
- (_Bool)needRemoveCacheForErrorCode:(long long)arg1;
- (void)modelDidStart:(id)arg1;
- (void)modelDidFinish:(id)arg1;
- (void)recordRpcTime:(id)arg1;
- (void)loadSetState:(_Bool)arg1;
- (_Bool)hasShowingData;
- (id)cacheKey;
- (void)handleCacheData:(id)arg1;
- (void)loadWithoutCache;
- (_Bool)needReadWriteCache;
- (void)cancel;
- (_Bool)unfoldSection:(unsigned long long)arg1;
- (void)load:(_Bool)arg1 ignoreLoadCache:(_Bool)arg2;
- (void)reload;
- (void)load;
- (id)initWithViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

