//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface O2OSearchHotwordView : UIView
{
    CDUnknownBlockType _selectAction;
    NSArray *_hotwords;
    NSArray *_hotwordBtns;
    NSArray *_rowLines;
    NSArray *_columnLines;
}

@property(copy, nonatomic) NSArray *columnLines; // @synthesize columnLines=_columnLines;
@property(copy, nonatomic) NSArray *rowLines; // @synthesize rowLines=_rowLines;
@property(copy, nonatomic) NSArray *hotwordBtns; // @synthesize hotwordBtns=_hotwordBtns;
@property(copy, nonatomic) NSArray *hotwords; // @synthesize hotwords=_hotwords;
@property(copy, nonatomic) CDUnknownBlockType selectAction; // @synthesize selectAction=_selectAction;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)adjustLayout;
- (void)onWordBtnClicked:(id)arg1;
- (id)createNewHotwordBtn:(id)arg1;
- (void)createLines;
- (void)createBtns;
- (void)updateHotwords:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

