//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "O2OPResultViewController.h"

#import "O2OCDPAdapterPromotionProtocol.h"
#import "O2OPSchemeProtocol.h"

@class NSString, O2OPResultStarViewTableViewCell;

@interface O2OUsedResultViewController : O2OPResultViewController <O2OCDPAdapterPromotionProtocol, O2OPSchemeProtocol>
{
    O2OPResultStarViewTableViewCell *_starCell;
}

+ (unsigned long long)canInitWithScheme:(id)arg1;
@property(retain, nonatomic) O2OPResultStarViewTableViewCell *starCell; // @synthesize starCell=_starCell;
- (void).cxx_destruct;
- (id)pageSpm;
- (void)promotionDataDidFinishLoading:(id)arg1 spaceCode:(id)arg2;
- (void)promotionViewDidFinishLoading:(id)arg1 spaceCode:(id)arg2;
- (void)promitionEnd;
- (void)promotionStart;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)initHeaderView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithScheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

