//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTViewController.h"

#import "PECollectorFooterViewDelegate.h"
#import "PECollectorHeaderViewDelegate.h"
#import "PEPayAmountViewModelDelegate.h"
#import "SafePayDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class APAlertView, APInputBox, APTableView, NSString, PECollectorFooterView, PECollectorHeaderView, PELaunchArgment, PEPayAmountViewModel, TRANSFERPRODCreateMoneyBillRes, TRANSFERPRODQueryReceiverInfoResp;

@interface PEPayAmountViewController : DTViewController <UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, PECollectorFooterViewDelegate, SafePayDelegate, PEPayAmountViewModelDelegate, PECollectorHeaderViewDelegate>
{
    _Bool _defaultFundChannelReady;
    _Bool _hasConfirmed;
    _Bool _paySuccess;
    _Bool _confirmBtnPressed;
    PEPayAmountViewModel *_payVM;
    PELaunchArgment *_launchArgment;
    TRANSFERPRODQueryReceiverInfoResp *_payeeResp;
    TRANSFERPRODCreateMoneyBillRes *_billResp;
    APAlertView *_alertView;
    PECollectorHeaderView *_headerView;
    PECollectorFooterView *_footerView;
    APTableView *_formView;
    APInputBox *_amountBox;
}

@property(nonatomic) _Bool confirmBtnPressed; // @synthesize confirmBtnPressed=_confirmBtnPressed;
@property(retain, nonatomic) APInputBox *amountBox; // @synthesize amountBox=_amountBox;
@property(retain, nonatomic) APTableView *formView; // @synthesize formView=_formView;
@property(retain, nonatomic) PECollectorFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) PECollectorHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) APAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) TRANSFERPRODCreateMoneyBillRes *billResp; // @synthesize billResp=_billResp;
@property(retain, nonatomic) TRANSFERPRODQueryReceiverInfoResp *payeeResp; // @synthesize payeeResp=_payeeResp;
@property(retain, nonatomic) PELaunchArgment *launchArgment; // @synthesize launchArgment=_launchArgment;
@property(retain, nonatomic) PEPayAmountViewModel *payVM; // @synthesize payVM=_payVM;
@property(nonatomic) _Bool paySuccess; // @synthesize paySuccess=_paySuccess;
@property(nonatomic) _Bool hasConfirmed; // @synthesize hasConfirmed=_hasConfirmed;
@property(nonatomic) _Bool defaultFundChannelReady; // @synthesize defaultFundChannelReady=_defaultFundChannelReady;
- (void).cxx_destruct;
- (void)terminateEnter;
- (void)paySuccessNotification;
- (void)headerView:(id)arg1 profileTapped:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)tapForm;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)safepayForgetPassWord;
- (void)payAmountVMDidFinishCreateBill:(id)arg1 billResp:(id)arg2;
- (void)payAmountVMWillStartCreateBill:(id)arg1;
- (void)payAmountVMDidFinishLoadDefaultFundChannel:(id)arg1 error:(id)arg2;
- (void)payAmountVMWillStartLoadDefaultFundChannel:(id)arg1;
- (void)payAmountVMDidFinishQueryReciverInfo:(id)arg1 reciverInfo:(id)arg2;
- (void)payAmountVMWillStartQueryReciverInfo:(id)arg1;
- (void)safepayDidFinishWithResult:(struct MQPResult *)arg1;
- (void)confirmPay;
- (id)getPayAmount;
- (void)collectorFooterViewDidSubmit;
- (void)collectorFooterViewChangePayChannel;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldInputChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (id)getLanchArgment;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)addSepratorLine:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)buildFormFooterView;
- (void)buildFormHeaderView;
- (void)buildFormView;
- (_Bool)amountValid;
- (void)decideViewLayout;
- (id)getPayAmountVM;
- (void)clearMe;
- (void)initMe;
- (void)addKeyBoardNotification;
- (void)viewWillDestroy;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

