//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface PilferingBlessingRequestPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(nonatomic) _Bool friendTag; // @dynamic friendTag;
@property(readonly) _Bool hasFriendTag; // @dynamic hasFriendTag;
@property(readonly) _Bool hasPhoneContacts; // @dynamic hasPhoneContacts;
@property(readonly) _Bool hasPileringCardId; // @dynamic hasPileringCardId;
@property(readonly) _Bool hasToUserid; // @dynamic hasToUserid;
@property(nonatomic) _Bool phoneContacts; // @dynamic phoneContacts;
@property(retain, nonatomic) NSString *pileringCardId; // @dynamic pileringCardId;
@property(retain, nonatomic) NSString *toUserid; // @dynamic toUserid;

@end

