//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSMutableArray, NSString;

@interface QueryFeedsResp : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasResultStatus;
    _Bool _hasMemo;
    _Bool _hasHasMore;
    _Bool _hasLastFeedId;
    _Bool _hasMore;
    NSString *_resultStatus;
    NSString *_memo;
    NSMutableArray *_feeds;
    NSString *_lastFeedId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *lastFeedId; // @synthesize lastFeedId=_lastFeedId;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *feeds; // @synthesize feeds=_feeds;
@property(retain, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property(retain, nonatomic) NSString *resultStatus; // @synthesize resultStatus=_resultStatus;
@property(readonly) _Bool hasLastFeedId; // @synthesize hasLastFeedId=_hasLastFeedId;
@property(readonly) _Bool hasHasMore; // @synthesize hasHasMore=_hasHasMore;
@property(readonly) _Bool hasMemo; // @synthesize hasMemo=_hasMemo;
@property(readonly) _Bool hasResultStatus; // @synthesize hasResultStatus=_hasResultStatus;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addFeeds:(id)arg1;
- (void)setFeedsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

