//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface RenderReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasTradeNo;
    _Bool _hasExtInfo;
    NSString *_tradeNo;
    NSString *_extInfo;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *extInfo; // @synthesize extInfo=_extInfo;
@property(retain, nonatomic) NSString *tradeNo; // @synthesize tradeNo=_tradeNo;
@property(readonly) _Bool hasExtInfo; // @synthesize hasExtInfo=_hasExtInfo;
@property(readonly) _Bool hasTradeNo; // @synthesize hasTradeNo=_hasTradeNo;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

