//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RERandomMoney : NSObject
{
    NSString *_money;
    NSString *_remark;
}

@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(retain, nonatomic) NSString *money; // @synthesize money=_money;
- (void).cxx_destruct;

@end

