//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface REWrittingView : UIView
{
    struct CGPath *_path;
    int _strokesCount;
    UIColor *_brushColor;
    double _brushSize;
    CDUnknownBlockType _handler;
    struct CGPoint _currentPoint;
    struct CGPoint _previousPoint;
    struct CGPoint _previousPreviousPoint;
}

@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) struct CGPoint previousPreviousPoint; // @synthesize previousPreviousPoint=_previousPreviousPoint;
@property(nonatomic) struct CGPoint previousPoint; // @synthesize previousPoint=_previousPoint;
@property(nonatomic) struct CGPoint currentPoint; // @synthesize currentPoint=_currentPoint;
@property(nonatomic) double brushSize; // @synthesize brushSize=_brushSize;
@property(retain, nonatomic) UIColor *brushColor; // @synthesize brushColor=_brushColor;
@property(nonatomic) int strokesCount; // @synthesize strokesCount=_strokesCount;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)convertToImage;
- (void)refresh;
- (id)initWithFrame:(struct CGRect)arg1 brushColor:(id)arg2 brushSize:(double)arg3 handler:(CDUnknownBlockType)arg4;

@end

