//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RMTaskDownloaderDelegate.h"

@class NSLock, NSString, RMTaskDownloader;

@interface RMFileDownloader : NSObject <RMTaskDownloaderDelegate>
{
    NSLock *_downloadLock;
    RMTaskDownloader *_taskDownloader;
    double _lastLaunchTime;
}

+ (id)sharedInstance;
+ (void)uploadKeyLogWithResId:(id)arg1 status:(id)arg2 errorCode:(long long)arg3 request:(id)arg4;
+ (void)addAndUploadKeyLogWhenRepeatDownloadingOverMaxRepeat:(_Bool)arg1 ResourceRequest:(id)arg2 CurrentRepeatCount:(long long)arg3;
+ (void)addAndUploadKeyLogWhenStopDownloadingTask:(id)arg1 TargetNetType:(long long)arg2 CurrentNetType:(long long)arg3;
+ (void)addAndUploadKeyLogWhenExceptionInDownloading:(id)arg1;
+ (void)addAndUploadKeyLogWhenDownloadTaskInvalidWithTaskID:(id)arg1 Type:(id)arg2 ExpireTime:(id)arg3 canDownloadInCurrentNetType:(_Bool)arg4 isResourceExist:(_Bool)arg5 isDownloading:(_Bool)arg6;
+ (void)addAndUploadKeyLogWhenSyncDataErrorWithTaskID:(id)arg1 isExpire:(_Bool)arg2 isResourceExist:(_Bool)arg3 SKey:(id)arg4;
+ (void)addKeyLogWhenCancelDownloadWithDic:(id)arg1;
+ (void)uploadKeyLogWhenDidReceiveSyncData;
@property(nonatomic) double lastLaunchTime; // @synthesize lastLaunchTime=_lastLaunchTime;
@property(retain, nonatomic) RMTaskDownloader *taskDownloader; // @synthesize taskDownloader=_taskDownloader;
@property(retain, nonatomic) NSLock *downloadLock; // @synthesize downloadLock=_downloadLock;
- (void).cxx_destruct;
- (void)downloadError:(id)arg1;
- (void)imageDownloadSuccessful:(id)arg1;
- (void)fileDownloadSuccessful:(id)arg1;
- (void)taskShouldAddIntoDownloadingList:(id)arg1 ResourceManager:(id)arg2;
- (id)delayTimeFromConfig;
- (void)stopDownloadingTasksIfNeeded:(long long)arg1;
- (void)downloadIfNeeded;
- (_Bool)checkIfResourceValid:(id)arg1;
- (void)continueDownloadingWhenEnteringForeground;
- (void)continueDownloadingIfNeeded;
- (void)cancel;
- (void)reachabilityChanged:(id)arg1;
- (void)syncReceiverDidReceiveData:(id)arg1;
- (void)addObserverForEnterForeground;
- (void)addObserverForNetTypeChange;
- (void)addObserverForDidReceiveSyncData;
- (void)registerListener;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

