//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RMFileManager, RMImageManager;

@interface RMResourceManager : NSObject
{
    long long _downloadType;
    RMFileManager *_currentRMFileMgr;
    RMImageManager *_currentRMImgMgr;
}

+ (void)continueDownloadingIfNeeded;
+ (void)registerSyncListener;
+ (_Bool)hasLocalImage:(id)arg1;
+ (id)pathForResource:(id)arg1 inBundle:(id)arg2 ofBusinessType:(id)arg3;
+ (_Bool)hasLocalResource:(id)arg1;
@property(retain, nonatomic) RMImageManager *currentRMImgMgr; // @synthesize currentRMImgMgr=_currentRMImgMgr;
@property(retain, nonatomic) RMFileManager *currentRMFileMgr; // @synthesize currentRMFileMgr=_currentRMFileMgr;
@property(nonatomic) long long downloadType; // @synthesize downloadType=_downloadType;
- (void).cxx_destruct;
- (void)cancel;
- (void)loadImageWithRequest:(id)arg1 loadingBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)resourceWithRequest:(id)arg1 loadingBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

