//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface RouteCommandPbReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasToken;
    _Bool _hasCodeType;
    _Bool _hasChannelId;
    _Bool _hasExtData;
    _Bool _hasClientContext;
    NSString *_token;
    NSString *_codeType;
    NSString *_channelId;
    NSString *_extData;
    NSString *_clientContext;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *clientContext; // @synthesize clientContext=_clientContext;
@property(retain, nonatomic) NSString *extData; // @synthesize extData=_extData;
@property(retain, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
@property(retain, nonatomic) NSString *codeType; // @synthesize codeType=_codeType;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(readonly) _Bool hasClientContext; // @synthesize hasClientContext=_hasClientContext;
@property(readonly) _Bool hasExtData; // @synthesize hasExtData=_hasExtData;
@property(readonly) _Bool hasChannelId; // @synthesize hasChannelId=_hasChannelId;
@property(readonly) _Bool hasCodeType; // @synthesize hasCodeType=_hasCodeType;
@property(readonly) _Bool hasToken; // @synthesize hasToken=_hasToken;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

