//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SACLoginHelper : NSObject
{
    CDUnknownBlockType _completion;
    NSString *_navigateAppId;
    NSString *_navigateLoginId;
}

+ (id)shareLoginHelper;
- (void).cxx_destruct;
- (void)dealloc;
- (id)buildLoginOptionsWithLoginId:(id)arg1 password:(id)arg2 loginType:(unsigned long long)arg3 addNewAccount:(_Bool)arg4 startLoginAutoly:(_Bool)arg5 autoLoginResult:(id)arg6 extraInfo:(id)arg7;
- (_Bool)startLoginAppWithLoginId:(id)arg1 password:(id)arg2 loginType:(unsigned long long)arg3 addNewAccount:(_Bool)arg4 startLoginAutoly:(_Bool)arg5 autoLoginResult:(id)arg6 extraInfo:(id)arg7 animated:(_Bool)arg8;
- (void)loginFinishNotification:(id)arg1;
- (void)startYUEBAO;
- (void)startLogin:(id)arg1;
- (void)doStartLoginWithUserInfo:(id)arg1;
- (void)doCompletion:(id)arg1;
- (void)doLoginSucessWithCompletion:(CDUnknownBlockType)arg1 fromView:(id)arg2;
- (id)init;

@end

