//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTMicroApplication, UIViewController;

@interface SCBaseServiceProvider : NSObject
{
    id _parames;
    UIViewController *_returnVC;
    CDUnknownBlockType _resultCallback;
    DTMicroApplication *_microApp;
    UIViewController *_rootVC;
}

@property(retain, nonatomic) UIViewController *rootVC; // @synthesize rootVC=_rootVC;
@property(nonatomic) __weak DTMicroApplication *microApp; // @synthesize microApp=_microApp;
@property(copy, nonatomic) CDUnknownBlockType resultCallback; // @synthesize resultCallback=_resultCallback;
@property(retain, nonatomic) UIViewController *returnVC; // @synthesize returnVC=_returnVC;
@property(retain, nonatomic) id parames; // @synthesize parames=_parames;
- (void).cxx_destruct;
- (void)exitService:(int)arg1 extraInfo:(id)arg2;
- (id)startService:(id)arg1 returnViewController:(id)arg2 shouldContinue:(CDUnknownBlockType)arg3 resultCallback:(CDUnknownBlockType)arg4;

@end

