//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "NSCoding.h"
#import "UIScrollViewDelegate.h"

@class ALAsset, NSString, SCSimpleImageView, UIColor, UIImage, UIPanGestureRecognizer, UIScrollView;

@interface SCSimpleImageEditorView : UIView <NSCoding, UIScrollViewDelegate>
{
    id displayedInstance;
    ALAsset *asset;
    UIImage *image;
    SCSimpleImageView *imageView;
    UIView *overlayView;
    UIView *ratioView;
    UIView *ratioControlsView;
    unsigned long long ratioViewMovementType;
    double ratio;
    UIColor *ratioViewBorderColor;
    double ratioViewBorderWidth;
    UIColor *borderColor;
    double borderWidth;
    long long rotation;
    double animationDuration;
    struct CGRect cropRect;
    UIPanGestureRecognizer *panGestureRecognizer;
    CDUnknownBlockType didChangeCropRectBlock;
    CDUnknownBlockType didChangeRotationBlock;
    _Bool ratioControlsHidden;
    UIImage *editedImage;
    UIScrollView *scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView;
@property(copy, nonatomic) CDUnknownBlockType didChangeRotationBlock; // @synthesize didChangeRotationBlock;
@property(copy, nonatomic) CDUnknownBlockType didChangeCropRectBlock; // @synthesize didChangeCropRectBlock;
@property(retain, nonatomic) UIImage *editedImage; // @synthesize editedImage;
@property(nonatomic) double animationDuration; // @synthesize animationDuration;
@property(nonatomic) long long rotation; // @synthesize rotation;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double ratioViewBorderWidth; // @synthesize ratioViewBorderWidth;
@property(retain, nonatomic) UIColor *ratioViewBorderColor; // @synthesize ratioViewBorderColor;
@property(nonatomic) _Bool ratioControlsHidden; // @synthesize ratioControlsHidden;
@property(nonatomic) double ratio; // @synthesize ratio;
@property(copy, nonatomic) UIImage *image; // @synthesize image;
@property(copy, nonatomic) ALAsset *asset; // @synthesize asset;
@property(retain, nonatomic) UIView *ratioControlsView; // @synthesize ratioControlsView;
@property(retain, nonatomic) UIView *ratioView; // @synthesize ratioView;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView;
@property(retain, nonatomic) SCSimpleImageView *imageView; // @synthesize imageView;
- (void).cxx_destruct;
- (id)rotatedImage:(id)arg1;
- (struct CGSize)sizeForRotatedImage:(id)arg1;
- (struct CGRect)imageFrameFromImageViewWithAspectFitMode:(id)arg1;
- (void)overlayClipping;
- (void)resetRatioControls;
- (void)repositionImageView;
- (void)displayImage:(id)arg1;
- (void)redisplayImage;
- (id)imageFromInstance:(id)arg1;
- (void)rotateRight;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) UIImage *output;
- (void)setRotation:(long long)arg1 animated:(_Bool)arg2;
- (void)showOrHideTheRatioControls;
@property(nonatomic) struct CGRect cropRect;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithAsset:(id)arg1;
- (id)initWithAsset:(id)arg1 andImage:(id)arg2;
- (id)initWithAsset:(id)arg1 image:(id)arg2 andFrame:(struct CGRect)arg3;
- (void)initialize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

