//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString;

@interface SendBlessingRequestPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *cardId; // @dynamic cardId;
@property(retain, nonatomic) NSString *cardMId; // @dynamic cardMId;
@property(readonly) _Bool hasCardId; // @dynamic hasCardId;
@property(readonly) _Bool hasCardMId; // @dynamic hasCardMId;
@property(readonly) _Bool hasReceiverType; // @dynamic hasReceiverType;
@property(readonly) _Bool hasSource; // @dynamic hasSource;
@property(retain, nonatomic) NSString *receiverType; // @dynamic receiverType;
@property(retain, nonatomic) NSArray *receivers; // @dynamic receivers;
@property(retain, nonatomic) NSString *source; // @dynamic source;

@end

