//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface SFAStockInfoListItem : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *actionUrl; // @dynamic actionUrl;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(readonly) _Bool hasActionUrl; // @dynamic hasActionUrl;
@property(readonly) _Bool hasContent; // @dynamic hasContent;
@property(readonly) _Bool hasIconUrl; // @dynamic hasIconUrl;
@property(readonly) _Bool hasInfoId; // @dynamic hasInfoId;
@property(readonly) _Bool hasMediaName; // @dynamic hasMediaName;
@property(readonly) _Bool hasTimeStampUnit; // @dynamic hasTimeStampUnit;
@property(readonly) _Bool hasTimeStampValue; // @dynamic hasTimeStampValue;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(retain, nonatomic) NSString *infoId; // @dynamic infoId;
@property(retain, nonatomic) NSString *mediaName; // @dynamic mediaName;
@property(retain, nonatomic) NSString *timeStampUnit; // @dynamic timeStampUnit;
@property(retain, nonatomic) NSString *timeStampValue; // @dynamic timeStampValue;

@end

