//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class EnvelopePrizeInfoPB, FucardPrizeInfoPB, NSString;

@interface ShoopShoopRespPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;
- (id)description;

// Remaining properties
@property(retain, nonatomic) EnvelopePrizeInfoPB *envelopePrizeInfo; // @dynamic envelopePrizeInfo;
@property(retain, nonatomic) NSString *followAction; // @dynamic followAction;
@property(retain, nonatomic) FucardPrizeInfoPB *fucardPrizeInfo; // @dynamic fucardPrizeInfo;
@property(readonly) _Bool hasEnvelopePrizeInfo; // @dynamic hasEnvelopePrizeInfo;
@property(readonly) _Bool hasFollowAction; // @dynamic hasFollowAction;
@property(readonly) _Bool hasFucardPrizeInfo; // @dynamic hasFucardPrizeInfo;
@property(readonly) _Bool hasNeedCount; // @dynamic hasNeedCount;
@property(readonly) _Bool hasPrizeType; // @dynamic hasPrizeType;
@property(readonly) _Bool hasRetCode; // @dynamic hasRetCode;
@property(readonly) _Bool hasRetMsg; // @dynamic hasRetMsg;
@property(readonly) _Bool hasSuccess; // @dynamic hasSuccess;
@property(nonatomic) _Bool needCount; // @dynamic needCount;
@property(retain, nonatomic) NSString *prizeType; // @dynamic prizeType;
@property(retain, nonatomic) NSString *retCode; // @dynamic retCode;
@property(retain, nonatomic) NSString *retMsg; // @dynamic retMsg;
@property(nonatomic) _Bool success; // @dynamic success;

@end

