//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface SimplePassListReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasTimeStatus;
    _Bool _hasRowSize;
    _Bool _hasUpdateFlag;
    _Bool _hasPageSize;
    _Bool _hasIsFromMsg;
    _Bool _hasLongitude;
    _Bool _hasLatitude;
    _Bool _hasExtParam;
    _Bool _hasCityAdCode;
    _Bool _hasDtLogMonitor;
    _Bool _isFromMsg;
    int _rowSize;
    int _pageSize;
    NSString *_timeStatus;
    NSString *_updateFlag;
    NSString *_longitude;
    NSString *_latitude;
    NSString *_extParam;
    NSString *_cityAdCode;
    NSString *_dtLogMonitor;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *dtLogMonitor; // @synthesize dtLogMonitor=_dtLogMonitor;
@property(retain, nonatomic) NSString *cityAdCode; // @synthesize cityAdCode=_cityAdCode;
@property(retain, nonatomic) NSString *extParam; // @synthesize extParam=_extParam;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(nonatomic) _Bool isFromMsg; // @synthesize isFromMsg=_isFromMsg;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(retain, nonatomic) NSString *updateFlag; // @synthesize updateFlag=_updateFlag;
@property(nonatomic) int rowSize; // @synthesize rowSize=_rowSize;
@property(retain, nonatomic) NSString *timeStatus; // @synthesize timeStatus=_timeStatus;
@property(readonly) _Bool hasDtLogMonitor; // @synthesize hasDtLogMonitor=_hasDtLogMonitor;
@property(readonly) _Bool hasCityAdCode; // @synthesize hasCityAdCode=_hasCityAdCode;
@property(readonly) _Bool hasExtParam; // @synthesize hasExtParam=_hasExtParam;
@property(readonly) _Bool hasLatitude; // @synthesize hasLatitude=_hasLatitude;
@property(readonly) _Bool hasLongitude; // @synthesize hasLongitude=_hasLongitude;
@property(readonly) _Bool hasIsFromMsg; // @synthesize hasIsFromMsg=_hasIsFromMsg;
@property(readonly) _Bool hasPageSize; // @synthesize hasPageSize=_hasPageSize;
@property(readonly) _Bool hasUpdateFlag; // @synthesize hasUpdateFlag=_hasUpdateFlag;
@property(readonly) _Bool hasRowSize; // @synthesize hasRowSize=_hasRowSize;
@property(readonly) _Bool hasTimeStatus; // @synthesize hasTimeStatus=_hasTimeStatus;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

