//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class LFCPBObjectInfo, NSString;

@interface SubmitPraisePBReq : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasObjectInfo;
    _Bool _hasClientId;
    _Bool _hasExtend;
    LFCPBObjectInfo *_objectInfo;
    NSString *_clientId;
    NSString *_extend;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *extend; // @synthesize extend=_extend;
@property(retain, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
@property(retain, nonatomic) LFCPBObjectInfo *objectInfo; // @synthesize objectInfo=_objectInfo;
@property(readonly) _Bool hasExtend; // @synthesize hasExtend=_hasExtend;
@property(readonly) _Bool hasClientId; // @synthesize hasClientId=_hasClientId;
@property(readonly) _Bool hasObjectInfo; // @synthesize hasObjectInfo=_hasObjectInfo;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

