//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"

@class AVCaptureVideoPreviewLayer, NSMutableDictionary, NSString, TBScanCamCaptureManager, TBScanResult, UIPopoverController, UIView;

@interface TBScanViewController : UIViewController <UIImagePickerControllerDelegate, UIPopoverControllerDelegate, UINavigationControllerDelegate, UIAlertViewDelegate>
{
    unsigned int _soundID;
    unsigned int _takePhotoSoundID;
    _Bool _torchOff;
    double cameraWidth;
    double cameraHeight;
    double initCameraTime;
    int localResultType;
    TBScanResult *localResult;
    _Bool viewHadAppear;
    _Bool _tryAutoFocus;
    _Bool _bPlaySound;
    _Bool _bPreciseScan;
    _Bool _bSaveBarcodeQRImage;
    _Bool _bResumeScanAtViewAppear;
    int _scanType;
    int _bTakePhotos;
    int _bScanPaused;
    int _scanCount;
    id <TBScanViewControllerDelegate> _delegate;
    double _focusInterval;
    double _cameraWidthPercent;
    NSString *_cameraPermissionDeniedTitle;
    NSString *_cameraPermissionDeniedMsg;
    NSString *_cameraPermissionDeniedCancelTitle;
    NSString *_scanPhotoFailedMsg;
    NSString *_scanPhotoFailedCancelTitle;
    NSMutableDictionary *_pluginDict;
    TBScanCamCaptureManager *_captureManager;
    UIView *_videoPreviewView;
    AVCaptureVideoPreviewLayer *_captureVideoPreviewLayer;
    double _cameraWidth2ScreenWidth;
    UIPopoverController *_popoverView;
    double _firstScanTime;
    long long _setupResult;
    double _lastFocusTime;
    struct CGRect _rectOfInterest;
}

@property(nonatomic) double lastFocusTime; // @synthesize lastFocusTime=_lastFocusTime;
@property(nonatomic) long long setupResult; // @synthesize setupResult=_setupResult;
@property(nonatomic) double firstScanTime; // @synthesize firstScanTime=_firstScanTime;
@property(nonatomic) int scanCount; // @synthesize scanCount=_scanCount;
@property(retain, nonatomic) UIPopoverController *popoverView; // @synthesize popoverView=_popoverView;
@property(nonatomic) double cameraWidth2ScreenWidth; // @synthesize cameraWidth2ScreenWidth=_cameraWidth2ScreenWidth;
@property(nonatomic) int bScanPaused; // @synthesize bScanPaused=_bScanPaused;
@property(nonatomic) int bTakePhotos; // @synthesize bTakePhotos=_bTakePhotos;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureVideoPreviewLayer; // @synthesize captureVideoPreviewLayer=_captureVideoPreviewLayer;
@property(retain, nonatomic) UIView *videoPreviewView; // @synthesize videoPreviewView=_videoPreviewView;
@property(retain, nonatomic) TBScanCamCaptureManager *captureManager; // @synthesize captureManager=_captureManager;
@property(retain, nonatomic) NSMutableDictionary *pluginDict; // @synthesize pluginDict=_pluginDict;
@property(retain, nonatomic) NSString *scanPhotoFailedCancelTitle; // @synthesize scanPhotoFailedCancelTitle=_scanPhotoFailedCancelTitle;
@property(retain, nonatomic) NSString *scanPhotoFailedMsg; // @synthesize scanPhotoFailedMsg=_scanPhotoFailedMsg;
@property(retain, nonatomic) NSString *cameraPermissionDeniedCancelTitle; // @synthesize cameraPermissionDeniedCancelTitle=_cameraPermissionDeniedCancelTitle;
@property(retain, nonatomic) NSString *cameraPermissionDeniedMsg; // @synthesize cameraPermissionDeniedMsg=_cameraPermissionDeniedMsg;
@property(retain, nonatomic) NSString *cameraPermissionDeniedTitle; // @synthesize cameraPermissionDeniedTitle=_cameraPermissionDeniedTitle;
@property(nonatomic) _Bool bResumeScanAtViewAppear; // @synthesize bResumeScanAtViewAppear=_bResumeScanAtViewAppear;
@property(nonatomic) _Bool bSaveBarcodeQRImage; // @synthesize bSaveBarcodeQRImage=_bSaveBarcodeQRImage;
@property(nonatomic) _Bool bPreciseScan; // @synthesize bPreciseScan=_bPreciseScan;
@property(nonatomic) _Bool bPlaySound; // @synthesize bPlaySound=_bPlaySound;
@property(nonatomic) double cameraWidthPercent; // @synthesize cameraWidthPercent=_cameraWidthPercent;
@property(nonatomic) _Bool tryAutoFocus; // @synthesize tryAutoFocus=_tryAutoFocus;
@property(nonatomic) double focusInterval; // @synthesize focusInterval=_focusInterval;
@property(nonatomic) struct CGRect rectOfInterest; // @synthesize rectOfInterest=_rectOfInterest;
@property(nonatomic) int scanType; // @synthesize scanType=_scanType;
@property(nonatomic) __weak id <TBScanViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)avCaptureInputPortFormatDescriptionDidChangeNotification:(id)arg1;
- (void)continueScan;
- (void)cameraStarted:(id)arg1;
- (void)scanLocalPhotoError;
- (void)showLocalPhotoResult;
- (void)scanUIImage:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)scanPhotoLibrary:(struct CGRect)arg1 permittedArrowDirections:(unsigned long long)arg2 with:(id)arg3;
- (void)scanPhotoLibrary;
- (_Bool)isScanPaused;
- (double)getCameraHeight;
- (double)getCameraWidth;
- (_Bool)canSetSession:(id)arg1;
- (void)playSound;
- (_Bool)getTakePhotosState;
- (_Bool)isUsingFrontCamera;
- (void)onTorch;
- (void)exitScan;
- (void)pauseScan;
- (void)resumeScan;
- (void)captureStillImage:(CDUnknownBlockType)arg1;
- (void)resumeCaptureSession;
- (void)pauseCaptureSession;
- (void)initCamera4LayoutSubviews;
- (void)onDismiss;
- (void)processPreview:(struct opaqueCMSampleBuffer *)arg1;
- (void)barCodeQRRecognized;
- (void)setPreviewRectByPreset;
- (void)setCameraWidth:(double)arg1;
- (double)getCameraWidth2ScreenWidth;
- (struct CGSize)cameraSizeForCameraInput:(id)arg1;
- (void)initCameraSize:(struct CGSize)arg1;
- (void)processPlugin:(int)arg1 withInfo:(id)arg2;
- (void)registerPlugin:(id)arg1 withType:(int)arg2;
- (id)getPluginByType:(int)arg1;
- (void)focusOnInterval;
- (void)releaseMemory;
- (void)checkAuthorized;
- (void)resetTakePhotoState;
- (void)setScanOn;
- (void)setTorchImage;
- (_Bool)checkPhotoLibrary;
- (void)setupView;
- (void)setupCamera;
- (void)initMemory;
- (void)updateView;
- (void)becomeActive;
- (void)initCritical;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewWillLayoutSubviews;
- (void)viewWillHide;
- (void)viewWillShow;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

