//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APNavItemView.h"

@interface TFNavItemView : APNavItemView
{
    id <TFNavItemViewDelegate> _delegate;
}

@property(nonatomic) __weak id <TFNavItemViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onClicked;

@end

