//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TFToAccountSucceedViewController, TFTransferRequest, TFTransferToAccount, UIImageView, UILabel;

@interface TFToAccountSucceedMemoView : UIView
{
    _Bool _isUncertifiedReceiver;
    _Bool _isAmountLimitedPayer;
    TFToAccountSucceedViewController *_successdViewController;
    UIImageView *_zhiIconView;
    UIImageView *_bgImageView;
    TFTransferRequest *_transferRequest;
    UILabel *_memoLabel;
    UILabel *_amountLabel;
    UILabel *_hintLabel;
    UIImageView *_hintImageView;
    TFTransferToAccount *_account;
}

@property(retain, nonatomic) TFTransferToAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) UIImageView *hintImageView; // @synthesize hintImageView=_hintImageView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(nonatomic) _Bool isAmountLimitedPayer; // @synthesize isAmountLimitedPayer=_isAmountLimitedPayer;
@property(nonatomic) _Bool isUncertifiedReceiver; // @synthesize isUncertifiedReceiver=_isUncertifiedReceiver;
@property(retain, nonatomic) UILabel *amountLabel; // @synthesize amountLabel=_amountLabel;
@property(retain, nonatomic) UILabel *memoLabel; // @synthesize memoLabel=_memoLabel;
@property(retain, nonatomic) TFTransferRequest *transferRequest; // @synthesize transferRequest=_transferRequest;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIImageView *zhiIconView; // @synthesize zhiIconView=_zhiIconView;
@property(nonatomic) __weak TFToAccountSucceedViewController *successdViewController; // @synthesize successdViewController=_successdViewController;
- (void).cxx_destruct;
- (void)unceritfiedRecevierHintLabelShow:(_Bool)arg1;
- (void)refreshWithMemo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 isUncertifiedReceiver:(_Bool)arg2 isAmountLimitedPayer:(_Bool)arg3 transferRequest:(id)arg4;
- (void)initUIElement;
- (id)initWithFrame:(struct CGRect)arg1;

@end

