//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol.h"

@class NSString;

@interface TranslateRequest : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasUid;
    _Bool _hasSrcText;
    _Bool _hasTargetLan;
    NSString *_uid;
    NSString *_srcText;
    NSString *_targetLan;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *targetLan; // @synthesize targetLan=_targetLan;
@property(retain, nonatomic) NSString *srcText; // @synthesize srcText=_srcText;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(readonly) _Bool hasTargetLan; // @synthesize hasTargetLan=_hasTargetLan;
@property(readonly) _Bool hasSrcText; // @synthesize hasSrcText=_hasSrcText;
@property(readonly) _Bool hasUid; // @synthesize hasUid=_hasUid;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

