//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEEFunctionTableController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class APExceptionView, NSArray, NSString, TZBHomeAssetCell, TZBHomeDataModel, TZBPorfitNumbersCell, UIButton, UIImageView;

@interface TZBHomeViewController : BEEFunctionTableController <UITableViewDataSource, UITableViewDelegate>
{
    UIButton *_transferOutButton;
    TZBHomeAssetCell *_assetCell;
    UIImageView *_bannerImageView;
    TZBPorfitNumbersCell *_porfitNumbersCell;
    TZBHomeDataModel *_homeModel;
    APExceptionView *_exceptView;
    NSArray *_cellWillLayout;
    NSString *_instid;
}

@property(retain, nonatomic) NSString *instid; // @synthesize instid=_instid;
- (void).cxx_destruct;
- (void)onRecordClicked;
- (void)onXiaoBaoBtn;
- (void)didClickTransferInBtn:(id)arg1;
- (void)didClickTransferOutBtn:(id)arg1;
- (void)onBackViewClicked;
- (void)showTransferChannel:(id)arg1 isTransferIn:(_Bool)arg2;
- (id)homeDeclareCell:(long long)arg1;
- (id)profitNumbersCell;
- (id)bannerCell;
- (id)declareImageCell;
- (id)homeAssetCell;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (struct CGSize)homeBannerSize;
- (void)setupToolBar;
- (void)setupTableView;
- (void)updateTZBHomeAssetCell;
- (void)updateYuEBaoHomeWithModel:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadException:(int)arg1 info:(id)arg2 retry:(_Bool)arg3;
- (void)loadEnded:(id)arg1;
- (id)loadData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

