//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface TZBPriceVolume : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *amount; // @dynamic amount;
@property(readonly) _Bool hasAmount; // @dynamic hasAmount;
@property(readonly) _Bool hasName; // @dynamic hasName;
@property(readonly) _Bool hasPrice; // @dynamic hasPrice;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSString *price; // @dynamic price;

@end

