//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BEEFunctionTableController.h"

@class APExceptionView, NSString, TZBTransferListModel;

@interface TZBTransferListViewController : BEEFunctionTableController
{
    long long _currentQueryType;
    TZBTransferListModel *_model;
    APExceptionView *_msgEmptyView;
    NSString *_rpcDate;
    long long _orginalDetailType;
}

@property(nonatomic) long long orginalDetailType; // @synthesize orginalDetailType=_orginalDetailType;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)hideEmptyPage;
- (void)showEmptyPageWithDesc:(id)arg1;
- (void)updateTableView;
- (void)changeTradeType:(long long)arg1;
- (void)segmentedControlTradeTypeDidChanged:(id)arg1;
- (_Bool)hasNextPage;
- (void)loadException:(int)arg1 info:(id)arg2 retry:(_Bool)arg3;
- (void)loadInMode:(long long)arg1;
- (void)loadEnded:(id)arg1;
- (id)loadData;
- (void)setupTableView;
- (void)setupSegment;
- (void)viewDidLoad;
- (id)init;

@end

