//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewDataSource.h"

@class NSIndexPath, VZCollectionItem, VZHTTPListModel;

@protocol VZCollectionViewDataSource <UICollectionViewDataSource>
- (void)collectionViewControllerDidLoadModel:(VZHTTPListModel *)arg1;
- (VZCollectionItem *)itemForCellAtIndexPath:(NSIndexPath *)arg1;
- (Class)cellClassForItem:(VZCollectionItem *)arg1 AtIndex:(NSIndexPath *)arg2;
@end

