//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "VZFNodeBackingViewInterface.h"

@class NSArray, NSString, NSTimer, UICollectionViewFlowLayout, UIPageControl, VZFCollectionView;

@interface VZFPagingView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, VZFNodeBackingViewInterface>
{
    UICollectionViewFlowLayout *_flowLayout;
    NSArray *_childViews;
    NSTimer *_timer;
    _Bool _isActive;
    _Bool _isVisible;
    _Bool _autoScrollAnimated;
    double _lastContentOffset;
    _Bool _pageControlEnabled;
    _Bool _scroll;
    _Bool _loopScroll;
    _Bool _vertical;
    VZFCollectionView *_collectionView;
    UIPageControl *_pageControl;
    double _autoScroll;
    long long _currentPage;
    id <VZFActionWrapper> _switched;
}

@property(retain, nonatomic) id <VZFActionWrapper> switched; // @synthesize switched=_switched;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) _Bool vertical; // @synthesize vertical=_vertical;
@property(nonatomic) _Bool loopScroll; // @synthesize loopScroll=_loopScroll;
@property(nonatomic) double autoScroll; // @synthesize autoScroll=_autoScroll;
@property(nonatomic) _Bool scroll; // @synthesize scroll=_scroll;
@property(nonatomic) _Bool pageControlEnabled; // @synthesize pageControlEnabled=_pageControlEnabled;
@property(readonly, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(readonly, nonatomic) VZFCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)resetState;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)updateCurrentPage:(id)arg1;
- (long long)indexForCellIndex:(long long)arg1;
- (void)scrollToPage:(long long)arg1;
- (void)scrollToNextItem;
- (void)scrollToPreviousItem;
- (_Bool)loopScrollEnabled;
- (_Bool)autoScrollEnabled;
- (_Bool)scrollEnabled;
- (void)stopTimer;
- (void)resetTimer;
- (void)setChildrenViews:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)willMoveToWindow:(id)arg1;
- (void)didBecomeActive;
- (void)willResignActive;
- (void)dealloc;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

