//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WEALTHToString.h"

@class NSString;

@interface WEALTHProfitQueryReq : WEALTHToString
{
    int _pageCount;
    NSString *_oprType;
}

@property(nonatomic) int pageCount; // @synthesize pageCount=_pageCount;
@property(retain, nonatomic) NSString *oprType; // @synthesize oprType=_oprType;
- (void).cxx_destruct;

@end

