//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WEALTHToString.h"

@class NSString;

@interface WEALTHCcrRemindSetReq : WEALTHToString
{
    NSString *_remindDbId;
    NSString *_cardIndexNo;
    NSString *_remindSwith;
    NSString *_remindDate;
    NSString *_instId;
    NSString *_holderName;
}

@property(retain, nonatomic) NSString *holderName; // @synthesize holderName=_holderName;
@property(retain, nonatomic) NSString *instId; // @synthesize instId=_instId;
@property(retain, nonatomic) NSString *remindDate; // @synthesize remindDate=_remindDate;
@property(retain, nonatomic) NSString *remindSwith; // @synthesize remindSwith=_remindSwith;
@property(retain, nonatomic) NSString *cardIndexNo; // @synthesize cardIndexNo=_cardIndexNo;
@property(retain, nonatomic) NSString *remindDbId; // @synthesize remindDbId=_remindDbId;
- (void).cxx_destruct;

@end

