//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WEALTHFUNDBaseUniformProdResult.h"

@class NSArray;

@interface WEALTHFUNDQueryMfundBillResult : WEALTHFUNDBaseUniformProdResult
{
    _Bool _hasNextPage;
    int _pageSize;
    int _currentPage;
    int _totalSize;
    int _totalPage;
    NSArray *_fundRecordList;
    long long _endTime;
}

+ (Class)fundRecordListElementClass;
@property(nonatomic) _Bool hasNextPage; // @synthesize hasNextPage=_hasNextPage;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) int totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) int totalSize; // @synthesize totalSize=_totalSize;
@property(nonatomic) int currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) int pageSize; // @synthesize pageSize=_pageSize;
@property(retain, nonatomic) NSArray *fundRecordList; // @synthesize fundRecordList=_fundRecordList;
- (void).cxx_destruct;

@end

