//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WEALTHCommonResult.h"

#import "NSCoding.h"

@class NSArray, NSDictionary, WEALTHBankCard;

@interface WEALTHBankCardDetailV920Result : WEALTHCommonResult <NSCoding>
{
    _Bool _enableRepayment;
    _Bool _hasSimplePassword;
    _Bool _supIcDelete;
    WEALTHBankCard *_bankCard;
    NSArray *_repayBizItems;
    NSArray *_selfBizItems;
    NSArray *_bankBizItems;
    NSDictionary *_extraInfo;
}

+ (Class)extraInfoElementClass;
+ (Class)bankBizItemsElementClass;
+ (Class)selfBizItemsElementClass;
+ (Class)repayBizItemsElementClass;
@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(nonatomic) _Bool supIcDelete; // @synthesize supIcDelete=_supIcDelete;
@property(nonatomic) _Bool hasSimplePassword; // @synthesize hasSimplePassword=_hasSimplePassword;
@property(retain, nonatomic) NSArray *bankBizItems; // @synthesize bankBizItems=_bankBizItems;
@property(retain, nonatomic) NSArray *selfBizItems; // @synthesize selfBizItems=_selfBizItems;
@property(retain, nonatomic) NSArray *repayBizItems; // @synthesize repayBizItems=_repayBizItems;
@property(nonatomic) _Bool enableRepayment; // @synthesize enableRepayment=_enableRepayment;
@property(retain, nonatomic) WEALTHBankCard *bankCard; // @synthesize bankCard=_bankCard;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

