//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XMMusicPlayerItem.h"

#import "AVAssetResourceLoaderDelegate.h"
#import "NSURLConnectionDataDelegate.h"

@class APMHttpResponse, NSData, NSString;

@interface XMATSMusicPlayerItem : XMMusicPlayerItem <AVAssetResourceLoaderDelegate, NSURLConnectionDataDelegate>
{
    NSData *_receivedData;
    NSString *_massRequestID;
    APMHttpResponse *_response;
}

@property(retain, nonatomic) APMHttpResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSString *massRequestID; // @synthesize massRequestID=_massRequestID;
@property(retain, nonatomic) NSData *receivedData; // @synthesize receivedData=_receivedData;
- (void).cxx_destruct;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (_Bool)respondWithDataForRequest:(id)arg1;
- (void)fillInContentInformation:(id)arg1;
- (void)processPendingRequests;
- (void)didFinishLoadingWitgData:(id)arg1;
- (void)didReceiveData:(id)arg1;
- (void)didReceiveResponse:(id)arg1;
- (void)didFailWithError:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

