//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVPlayerItem.h"

#import "AVAssetResourceLoaderDelegate.h"

@class NSMutableArray, NSString;

@interface XMMusicPlayerItem : AVPlayerItem <AVAssetResourceLoaderDelegate>
{
    id <XMMusicPlayerItemDelegate> _delegate;
    NSString *_songId;
    NSMutableArray *_pendingRequests;
}

+ (id)urlWithCustomScheme:(id)arg1 url:(id)arg2;
+ (id)instanceWithUrl:(id)arg1 songId:(id)arg2;
@property(readonly, nonatomic) NSMutableArray *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
@property(retain, nonatomic) NSString *songId; // @synthesize songId=_songId;
@property(nonatomic) __weak id <XMMusicPlayerItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

